eqn_src = [
  {
    mml1: '<math>  <mo> &lt; </mo>  <msub>  <mi> f </mi>  <mrow>  <mi> f </mi>  <mi> l </mi>  <mi> a </mi>  <mi> r </mi>  <mi> e </mi>  </mrow>  </msub>  <mo> &gt;= </mo>  <mstyle displaystyle="true" scriptlevel="0">  <mrow>  <mfrac>  <mrow>  <msubsup>  <mo> &#x222B; <!-- â\x88« -->  </mo>  <mrow>  <mn> 1 </mn>  <mspace width="thinmathspace" />  <mrow>  <mi> C </mi>  <mi> r </mi>  <mi> a </mi>  <mi> b </mi>  </mrow>  </mrow>  <mrow>  <msub>  <mi> F </mi>  <mrow>  <mi> l </mi>  <mi> i </mi>  <mi> m </mi>  </mrow>  </msub>  </mrow>  </msubsup>  <mi> x </mi>  <mspace width="thinmathspace" />  <mi> f </mi>  <mo> ( </mo>  <mi> x </mi>  <mo> ) </mo>  <mspace width="thinmathspace" />  <mi> d </mi>  <mi> x </mi>  </mrow>  <mrow>  <msubsup>  <mo> &#x222B; <!-- â\x88« -->  </mo>  <mrow>  <mn> 1 </mn>  <mspace width="thinmathspace" />  <mrow>  <mi> C </mi>  <mi> r </mi>  <mi> a </mi>  <mi> b </mi>  </mrow>  </mrow>  <mrow>  <msub>  <mi> F </mi>  <mrow>  <mi> l </mi>  <mi> i </mi>  <mi> m </mi>  </mrow>  </msub>  </mrow>  </msubsup>  <mi> f </mi>  <mo> ( </mo>  <mi> x </mi>  <mo> ) </mo>  <mspace width="thinmathspace" />  <mi> d </mi>  <mi> x </mi>  </mrow>  </mfrac>  </mrow>  </mstyle>  </math> \n',
    mml2: '<math>  <mo> &lt; </mo>  <msub>  <mi> f </mi>  <mrow>  <mi> f </mi>  <mi> l </mi>  <mi> a </mi>  <mi> r </mi>  <mi> e </mi>  </mrow>  </msub>  <mo> &gt;= </mo>   <mstyle>   <mrow>  <mfrac>  <mrow>  <msubsup>  <mo> &#x222B; <!-- â\x88« -->  </mo>  <mrow>  <mn> 1 </mn>   <mstyle>   <mrow>  <mi> C </mi>  <mi> r </mi>  <mi> a </mi>  <mi> b </mi>  </mrow>  </mrow>  <mrow>  <msub>  <mi> F </mi>  <mrow>  <mi> l </mi>  <mi> i </mi>  <mi> m </mi>  </mrow>  </msub>  </mrow>  </msubsup>  <mi> x </mi>   <mstyle>   <mi> f </mi>  <mo> ( </mo>  <mi> x </mi>  <mo> ) </mo>   <mstyle>   <mi> d </mi>  <mi> x </mi>  </mrow>  <mrow>  <msubsup>  <mo> &#x222B; <!-- â\x88« -->  </mo>  <mrow>  <mn> 1 </mn>   <mstyle>   <mrow>  <mi> C </mi>  <mi> r </mi>  <mi> a </mi>  <mi> b </mi>  </mrow>  </mrow>  <mrow>  <msub>  <mi> F </mi>  <mrow>  <mi> l </mi>  <mi> i </mi>  <mi> m </mi>  </mrow>  </msub>  </mrow>  </msubsup>  <mi> f </mi>  <mo> ( </mo>  <mi> x </mi>  <mo> ) </mo>   <mstyle>   <mi> d </mi>  <mi> x </mi>  </mrow>  </mfrac>  </mrow>  </mstyle>  </math> \n'
  },
  {
    mml1: '<math>  <msub>  <mi> X </mi>  <mrow>  <mi> i </mi>  </mrow>  </msub>  <mo> ( </mo>  <mi> s </mi>  <mo> ) </mo>  <mo> = </mo>  <msub>  <mi> X </mi>  <mrow>  <mi> i </mi>  </mrow>  </msub>  <mo> ( </mo>  <mn> 0 </mn>  <mo> ) </mo>  <msup>  <mi> e </mi>  <mrow>  <mo> &#x2212; <!-- â\x88\x92 -->  </mo>  <mrow>  <mover>  <mi> b </mi>  <mo> &#x007E; <!-- ~ -->  </mo>  </mover>  </mrow>  <mo> ( </mo>  <mi> s </mi>  <mo> ) </mo>  </mrow>  </msup>  <mo> + </mo>  <msup>  <mi> e </mi>  <mrow>  <mo> &#x2212; <!-- â\x88\x92 -->  </mo>  <mrow>  <mover>  <mi> b </mi>  <mo> &#x007E; <!-- ~ -->  </mo>  </mover>  </mrow>  <mo> ( </mo>  <mi> s </mi>  <mo> ) </mo>  </mrow>  </msup>  <msubsup>  <mo> &#x222B; <!-- â\x88« -->  </mo>  <mrow>  <mn> 0 </mn>  </mrow>  <mrow>  <mi> s </mi>  </mrow>  </msubsup>  <msup>  <mi> e </mi>  <mrow>  <mrow>  <mover>  <mi> b </mi>  <mo> &#x007E; <!-- ~ -->  </mo>  </mover>  </mrow>  <mo> ( </mo>  <mi> v </mi>  <mo> ) </mo>  </mrow>  </msup>  <msup>  <mi> &#x03D6; <!-- Ï\x96 -->  </mi>  <mn> 2 </mn>  </msup>  <mo> ( </mo>  <mi> v </mi>  <mo> ) </mo>  <mspace width="thinmathspace" />  <mrow>  <mi> d </mi>  </mrow>  </math> \n',
    mml2: '<math>  <msub>  <mi> X </mi>  <mrow>  <mi> i </mi>  </mrow>  </msub>  <mo> ( </mo>  <mi> s </mi>  <mo> ) </mo>  <mo> = </mo>  <msub>  <mi> X </mi>  <mrow>  <mi> i </mi>  </mrow>  </msub>  <mo> ( </mo>  <mn> 0 </mn>  <mo> ) </mo>  <msup>  <mi> e </mi>  <mrow>  <mo> &#x2212; <!-- â\x88\x92 -->  </mo>  <mrow>  <mover>  <mi> b </mi>  <mo> &#x007E; <!-- ~ -->  </mo>  </mover>  </mrow>  <mo> ( </mo>  <mi> s </mi>  <mo> ) </mo>  </mrow>  </msup>  <mo> + </mo>  <msup>  <mi> e </mi>  <mrow>  <mo> &#x2212; <!-- â\x88\x92 -->  </mo>  <mrow>  <mover>  <mi> b </mi>  <mo> &#x007E; <!-- ~ -->  </mo>  </mover>  </mrow>  <mo> ( </mo>  <mi> s </mi>  <mo> ) </mo>  </mrow>  </msup>  <msubsup>  <mo> &#x222B; <!-- â\x88« -->  </mo>  <mrow>  <mn> 0 </mn>  </mrow>  <mrow>  <mi> s </mi>  </mrow>  </msubsup>  <msup>  <mi> e </mi>  <mrow>  <mrow>  <mover>  <mi> b </mi>  <mo> &#x007E; <!-- ~ -->  </mo>  </mover>  </mrow>  <mo> ( </mo>  <mi> v </mi>  <mo> ) </mo>  </mrow>  </msup>  <msup>  <mi> &#x03D6; <!-- Ï\x96 -->  </mi>  <mn> 2 </mn>  </msup>  <mo> ( </mo>  <mi> v </mi>  <mo> ) </mo>   <mi>   <mrow>  <mi> d </mi>  </mrow>  </math> \n'
  },
  {
    mml1: '<math>  <mrow>  <mrow>  <mi> e </mi>  </mrow>  </mrow>  <mrow>  <mi> &#x03B5; <!-- Îµ -->  </mi>  </mrow>  <msub>  <mi> u </mi>  <mrow>  <mi> &#x03B5; <!-- Îµ -->  </mi>  </mrow>  </msub>  <mrow>  <mi> i </mi>  <mi> n </mi>  </mrow>  <mi> D </mi>  <mo> ( </mo>  <msub>  <mi> &#x2202; <!-- â\x88\x82 -->  </mi>  <mrow>  <mn> 1 </mn>  <mo> , </mo>  <mi> c </mi>  </mrow>  </msub>  <mo> ) </mo>  </math> \n',
    mml2: '<math>  <mrow>  <mrow>  <mi> e </mi>  </mrow>  </mrow>  <mrow>  <mi> &#x03B5; <!-- Îµ -->  </mi>  </mrow>  <msub>  <mi> u </mi>  <mrow>  <mi> &#x03B5; <!-- Îµ -->  </mi>  </mrow>  </msub>  <mrow>  <mi> i </mi>  <mi> n </mi>  </mrow>  <mi> D </mi>  <mo> ( </mo>  <msub>  <mi> &#x2202; <!-- â\x88\x82 -->  </mi>  <mrow>  <mn> 1 </mn>  <mo> , </mo>  <mi> c </mi>  </mrow>  </msub>  <mo> ) </mo>  </math> \n'
  },
  {
    mml1: '<math>  <msub>  <mi> C </mi>  <mi> A </mi>  </msub>  <mo> ( </mo>  <mi> p </mi>  <mo> &#x2248; <!-- â\x89\x88 -->  </mo>  <mi> q </mi>  <mo> ) </mo>  </math> \n',
    mml2: '<math>  <msub>  <mi> C </mi>  <mi> A </mi>  </msub>  <mo> ( </mo>  <mi> p </mi>  <mo> &#x2248; <!-- â\x89\x88 -->  </mo>  <mi> q </mi>  <mo> ) </mo>  </math> \n'
  },
  {
    mml1: '<math>  <mrow>  <mover>  <mi> W </mi>  <mo> &#x007E; <!-- ~ -->  </mo>  </mover>  </mrow>  <mo> ( </mo>  <mn> 2 </mn>  <msub>  <mi> k </mi>  <mi> F </mi>  </msub>  <mrow>  <mo> | </mo>  </mrow>  <mrow>  <mi> s </mi>  <mi> i </mi>  <mi> n </mi>  </mrow>  <mo> ( </mo>  <mi> &#x03D1; <!-- Ï\x91 -->  </mi>  <mrow>  <mo> / </mo>  </mrow>  <mn> 2 </mn>  <mo> ) </mo>  <mrow>  <mo> | </mo>  </mrow>  <mo> ) </mo>  <mo> &#x2261; <!-- â\x89¡ -->  </mo>  <mi> W </mi>  <mo> ( </mo>  <mi> &#x03D1; <!-- Ï\x91 -->  </mi>  <mo> ) </mo>  </math> \n',
    mml2: '<math>  <mrow>  <mover>  <mi> W </mi>  <mo> &#x007E; <!-- ~ -->  </mo>  </mover>  </mrow>  <mo> ( </mo>  <mn> 2 </mn>  <msub>  <mi> k </mi>  <mi> F </mi>  </msub>  <mrow>  <mo> | </mo>  </mrow>  <mrow>  <mi> s </mi>  <mi> i </mi>  <mi> n </mi>  </mrow>  <mo> ( </mo>  <mi> &#x03D1; <!-- Ï\x91 -->  </mi>  <mrow>  <mo> / </mo>  </mrow>  <mn> 2 </mn>  <mo> ) </mo>  <mrow>  <mo> | </mo>  </mrow>  <mo> ) </mo>  <mo> &#x2261; <!-- â\x89¡ -->  </mo>  <mi> W </mi>  <mo> ( </mo>  <mi> &#x03D1; <!-- Ï\x91 -->  </mi>  <mo> ) </mo>  </math> \n'
  },
  {
    mml1: '<math>  <msubsup>  <mi> z </mi>  <mrow>  <mo> + </mo>  <mo> , </mo>  <mi> j </mi>  </mrow>  <mi> n </mi>  </msubsup>  <mo> = </mo>  <msubsup>  <mi> z </mi>  <mrow>  <mo> &#x2212; <!-- â\x88\x92 -->  </mo>  <mo> , </mo>  <mi> j </mi>  </mrow>  <mi> n </mi>  </msubsup>  </math> \n',
    mml2: '<math>  <msubsup>  <mi> z </mi>  <mrow>  <mo> + </mo>  <mo> , </mo>  <mi> j </mi>  </mrow>  <mi> n </mi>  </msubsup>  <mo> = </mo>  <msubsup>  <mi> z </mi>  <mrow>  <mo> &#x2212; <!-- â\x88\x92 -->  </mo>  <mo> , </mo>  <mi> j </mi>  </mrow>  <mi> n </mi>  </msubsup>  </math> \n'
  },
  {
    mml1: '<math>  <msub>  <mi> f </mi>  <mi> a </mi>  </msub>  <mo> = </mo>  <msub>  <mi> x </mi>  <mi> a </mi>  </msub>  </math> \n',
    mml2: '<math>  <msub>  <mi> f </mi>  <mi> a </mi>  </msub>  <mo> = </mo>  <msub>  <mi> x </mi>  <mi> a </mi>  </msub>  </math> \n'
  },
  {
    mml1: '<math>  <mi> h </mi>  <mo> = </mo>  <mstyle displaystyle="true" scriptlevel="0">  <mrow>  <mfrac>  <mn> 1 </mn>  <mn> 2 </mn>  </mfrac>  </mrow>  </mstyle>  </math> \n',
    mml2: '<math>  <mi> h </mi>  <mo> = </mo>   <mstyle>   <mrow>  <mfrac>  <mn> 1 </mn>  <mn> 2 </mn>  </mfrac>  </mrow>  </mstyle>  </math> \n'
  },
  {
    mml1: '<math>  <munder>  <mrow>  <munder>  <mi> lim </mi>  <mo> &#x2190; <!-- â\x86\x90 -->  </mo>  </munder>  </mrow>  <mrow>  <mi> r </mi>  <mo> &#x2193; <!-- â\x86\x93 -->  </mo>  <mn> 0 </mn>  </mrow>  </munder>  <mstyle displaystyle="true" scriptlevel="0">  <mrow>  <mfrac>  <mrow>  <mi> f </mi>  <mo> ( </mo>  <msup>  <mi> j </mi>  <mrow>  <mo> &#x2212; <!-- â\x88\x92 -->  </mo>  <mn> 1 </mn>  </mrow>  </msup>  <mo> ( </mo>  <msub>  <mi> g </mi>  <mrow>  <msub>  <mi> i </mi>  <mi> y </mi>  </msub>  </mrow>  </msub>  <mo> ( </mo>  <mi> r </mi>  <mi> p </mi>  <mo> ) </mo>  <mo> ) </mo>  <mo> ) </mo>  <mo> &#x2212; <!-- â\x88\x92 -->  </mo>  <mi> f </mi>  <mo> ( </mo>  <mi> x </mi>  <mo> ) </mo>  </mrow>  <mrow>  <msub>  <mi> d </mi>  <mi> X </mi>  </msub>  <mo> ( </mo>  <msup>  <mi> j </mi>  <mrow>  <mo> &#x2212; <!-- â\x88\x92 -->  </mo>  <mn> 1 </mn>  </mrow>  </msup>  <mo> ( </mo>  <msub>  <mi> g </mi>  <mrow>  <msub>  <mi> i </mi>  <mi> y </mi>  </msub>  </mrow>  </msub>  <mo> ( </mo>  <mi> r </mi>  <mi> p </mi>  <mo> ) </mo>  <mo> ) </mo>  <mo> , </mo>  <mi> x </mi>  <mo> ) </mo>  </mrow>  </mfrac>  </mrow>  </mstyle>  </math> \n',
    mml2: '<math>  <munder>  <mrow>  <munder>  <mi> lim </mi>  <mo> &#x2190; <!-- â\x86\x90 -->  </mo>  </munder>  </mrow>  <mrow>  <mi> r </mi>  <mo> &#x2193; <!-- â\x86\x93 -->  </mo>  <mn> 0 </mn>  </mrow>  </munder>   <mstyle>   <mrow>  <mfrac>  <mrow>  <mi> f </mi>  <mo> ( </mo>  <msup>  <mi> j </mi>  <mrow>  <mo> &#x2212; <!-- â\x88\x92 -->  </mo>  <mn> 1 </mn>  </mrow>  </msup>  <mo> ( </mo>  <msub>  <mi> g </mi>  <mrow>  <msub>  <mi> i </mi>  <mi> y </mi>  </msub>  </mrow>  </msub>  <mo> ( </mo>  <mi> r </mi>  <mi> p </mi>  <mo> ) </mo>  <mo> ) </mo>  <mo> ) </mo>  <mo> &#x2212; <!-- â\x88\x92 -->  </mo>  <mi> f </mi>  <mo> ( </mo>  <mi> x </mi>  <mo> ) </mo>  </mrow>  <mrow>  <msub>  <mi> d </mi>  <mi> X </mi>  </msub>  <mo> ( </mo>  <msup>  <mi> j </mi>  <mrow>  <mo> &#x2212; <!-- â\x88\x92 -->  </mo>  <mn> 1 </mn>  </mrow>  </msup>  <mo> ( </mo>  <msub>  <mi> g </mi>  <mrow>  <msub>  <mi> i </mi>  <mi> y </mi>  </msub>  </mrow>  </msub>  <mo> ( </mo>  <mi> r </mi>  <mi> p </mi>  <mo> ) </mo>  <mo> ) </mo>  <mo> , </mo>  <mi> x </mi>  <mo> ) </mo>  </mrow>  </mfrac>  </mrow>  </mstyle>  </math> \n'
  },
  {
    mml1: '<math>  <mi> j </mi>  <mo> = </mo>  <mn> 10 </mn>  </math> \n',
    mml2: '<math>  <mi> j </mi>  <mo> = </mo>  <mn> 10 </mn>  </math> \n'
  },
  {
    mml1: '<math>  <mrow>  <mo> | </mo>  </mrow>  <mi> &#x03BE; <!-- Î¾ -->  </mi>  <mrow>  <mo> | </mo>  </mrow>  <mi> g </mi>  <mn> 1 </mn>  </math> \n',
    mml2: '<math>  <mrow>  <mo> | </mo>  </mrow>  <mi> &#x03BE; <!-- Î¾ -->  </mi>  <mrow>  <mo> | </mo>  </mrow>  <mi> g </mi>  <mn> 1 </mn>  </math> \n'
  },
  {
    mml1: '<math>  <msub>  <mi> E </mi>  <mrow>  <mi> t </mi>  <mi> o </mi>  <mi> t </mi>  </mrow>  </msub>  <mo> = </mo>  <msub>  <mi> E </mi>  <mrow>  <mi> s </mi>  </mrow>  </msub>  <mo> + </mo>  <msub>  <mi> E </mi>  <mrow>  <mi> r </mi>  </mrow>  </msub>  </math> \n',
    mml2: '<math>  <msub>  <mi> E </mi>  <mrow>  <mi> t </mi>  <mi> o </mi>  <mi> t </mi>  </mrow>  </msub>  <mo> = </mo>  <msub>  <mi> E </mi>  <mrow>  <mi> s </mi>  </mrow>  </msub>  <mo> + </mo>  <msub>  <mi> E </mi>  <mrow>  <mi> r </mi>  </mrow>  </msub>  </math> \n'
  },
  {
    mml1: '<math>  <mn> 4 </mn>  <mi> &#x03C0; <!-- Ï\x80 -->  </mi>  <msubsup>  <mo> &#x222B; <!-- â\x88« -->  </mo>  <mrow>  <mn> 0 </mn>  </mrow>  <mrow>  <mi> &#x221E; <!-- â\x88\x9e -->  </mi>  </mrow>  </msubsup>  <mstyle scriptlevel="0">  <mrow>  <mo maxsize="2.047em" minsize="2.047em"> ( </mo>  </mrow>  </mstyle>  <mrow>  <mrow>  <mrow>  <msub>  <mi> K </mi>  <mrow>  <mi> X </mi>  <mo> , </mo>  <mrow>  <mi> h </mi>  <mi> y </mi>  <mi> p </mi>  </mrow>  </mrow>  </msub>  </mrow>  </mrow>  </mrow>  <mo> &#x2061; <!-- â\x81¡ -->  </mo>  <mo> ( </mo>  <mi> t </mi>  <mo> ; </mo>  <mi> z </mi>  <mo> , </mo>  <mi> z </mi>  <mo> ) </mo>  <mo> &#x2212; <!-- â\x88\x92 -->  </mo>  <msub>  <mi> K </mi>  <mrow>  <mrow>  <mi mathvariant="double-struck"> H </mi>  </mrow>  </mrow>  </msub>  <mo> ( </mo>  <mi> t </mi>  <mo> ; </mo>  <mn> 0 </mn>  <mo> ) </mo>  <mo> &#x2212; <!-- â\x88\x92 -->  </mo>  <mstyle displaystyle="true" scriptlevel="0">  <mrow>  <mfrac>  <mn> 1 </mn>  <mrow>  <mrow>  <mrow>  <mi> v </mi>  <mi> o </mi>  <msub>  <mi> l </mi>  <mrow>  <mrow>  <mi> h </mi>  <mi> y </mi>  <mi> p </mi>  </mrow>  </mrow>  </msub>  </mrow>  </mrow>  <mo> &#x2061; <!-- â\x81¡ -->  </mo>  <mo> ( </mo>  <mi> X </mi>  <mo> ) </mo>  </mrow>  </mfrac>  </mrow>  <mstyle scriptlevel="0">  <mrow>  <mo maxsize="2.047em" minsize="2.047em"> ) </mo>  </mrow>  </mstyle>  <mi> d </mi>  <mi> t </mi>  </mstyle>  </math> \n',
    mml2: '<math>  <mn> 4 </mn>  <mi> &#x03C0; <!-- Ï\x80 -->  </mi>  <msubsup>  <mo> &#x222B; <!-- â\x88« -->  </mo>  <mrow>  <mn> 0 </mn>  </mrow>  <mrow>  <mi> &#x221E; <!-- â\x88\x9e -->  </mi>  </mrow>  </msubsup>  <mstyle scriptlevel="0">  <mrow>   <mi>  ( </mo>  </mrow>  </mstyle>  <mrow>  <mrow>  <mrow>  <msub>  <mi> K </mi>  <mrow>  <mi> X </mi>  <mo> , </mo>  <mrow>  <mi> h </mi>  <mi> y </mi>  <mi> p </mi>  </mrow>  </mrow>  </msub>  </mrow>  </mrow>  </mrow>  <mo> &#x2061; <!-- â\x81¡ -->  </mo>  <mo> ( </mo>  <mi> t </mi>  <mo> ; </mo>  <mi> z </mi>  <mo> , </mo>  <mi> z </mi>  <mo> ) </mo>  <mo> &#x2212; <!-- â\x88\x92 -->  </mo>  <msub>  <mi> K </mi>  <mrow>  <mrow>   <mi>  H </mi>  </mrow>  </mrow>  </msub>  <mo> ( </mo>  <mi> t </mi>  <mo> ; </mo>  <mn> 0 </mn>  <mo> ) </mo>  <mo> &#x2212; <!-- â\x88\x92 -->  </mo>   <mstyle>   <mrow>  <mfrac>  <mn> 1 </mn>  <mrow>  <mrow>  <mrow>  <mi> v </mi>  <mi> o </mi>  <msub>  <mi> l </mi>  <mrow>  <mrow>  <mi> h </mi>  <mi> y </mi>  <mi> p </mi>  </mrow>  </mrow>  </msub>  </mrow>  </mrow>  <mo> &#x2061; <!-- â\x81¡ -->  </mo>  <mo> ( </mo>  <mi> X </mi>  <mo> ) </mo>  </mrow>  </mfrac>  </mrow>  <mstyle scriptlevel="0">  <mrow>   <mi>  ) </mo>  </mrow>  </mstyle>  <mi> d </mi>  <mi> t </mi>  </mstyle>  </math> \n'
  },
  {
    mml1: '<math>  <mi> &#x2113; <!-- â\x84\x93 -->  </mi>  <mo> = </mo>  <mn> 1 </mn>  </math> \n',
    mml2: '<math>  <mi> &#x2113; <!-- â\x84\x93 -->  </mi>  <mo> = </mo>  <mn> 1 </mn>  </math> \n'
  },
  {
    mml1: '<math>  <munder>  <mo movablelimits="true" form="prefix"> min </mo>  <mrow>  <mn> 1 </mn>  <mo> &#x2A7D; <!-- â©½ -->  </mo>  <mi> j </mi>  <mo> &#x2A7D; <!-- â©½ -->  </mo>  <mi> N </mi>  </mrow>  </munder>  </math> \n',
    mml2: '<math>  <munder>   <mi>  min </mo>  <mrow>  <mn> 1 </mn>  <mo> &#x2A7D; <!-- â©½ -->  </mo>  <mi> j </mi>  <mo> &#x2A7D; <!-- â©½ -->  </mo>  <mi> N </mi>  </mrow>  </munder>  </math> \n'
  },
  {
    mml1: '<math>  <mrow>  <mover>  <mi> G </mi>  <mo> &#x02C7; <!-- Ë\x87 -->  </mo>  </mover>  </mrow>  <mo> &#x2248; <!-- â\x89\x88 -->  </mo>  </math> \n',
    mml2: '<math>  <mrow>  <mover>  <mi> G </mi>  <mo> &#x02C7; <!-- Ë\x87 -->  </mo>  </mover>  </mrow>  <mo> &#x2248; <!-- â\x89\x88 -->  </mo>  </math> \n'
  },
  {
    mml1: '<math>  <mn> 1 </mn>  <mo> &#x2212; <!-- â\x88\x92 -->  </mo>  <mi> V </mi>  <mo> ( </mo>  <mi> y </mi>  <mo> ) </mo>  <mo> + </mo>  <mi> V </mi>  <mo> ( </mo>  <mo> &#x2212; <!-- â\x88\x92 -->  </mo>  <mi> y </mi>  <mo> ) </mo>  <mo> &#x223C; <!-- â\x88¼ -->  </mo>  <msup>  <mi> y </mi>  <mrow>  <mo> &#x2212; <!-- â\x88\x92 -->  </mo>  <mn> 1 </mn>  </mrow>  </msup>  </math> \n',
    mml2: '<math>  <mn> 1 </mn>  <mo> &#x2212; <!-- â\x88\x92 -->  </mo>  <mi> V </mi>  <mo> ( </mo>  <mi> y </mi>  <mo> ) </mo>  <mo> + </mo>  <mi> V </mi>  <mo> ( </mo>  <mo> &#x2212; <!-- â\x88\x92 -->  </mo>  <mi> y </mi>  <mo> ) </mo>  <mo> &#x223C; <!-- â\x88¼ -->  </mo>  <msup>  <mi> y </mi>  <mrow>  <mo> &#x2212; <!-- â\x88\x92 -->  </mo>  <mn> 1 </mn>  </mrow>  </msup>  </math> \n'
  },
  {
    mml1: '<math>  <mrow>  <mo> [ </mo>  <mrow>  <mo> { </mo>  <mi> a </mi>  <mo> } </mo>  </mrow>  <mo> , </mo>  <mspace width="thinmathspace" />  <mrow>  <mo> [ </mo>  <mi> b </mi>  <mo> , </mo>  <mspace width="thinmathspace" />  <mi> c </mi>  <mo> ] </mo>  </mrow>  <mo> ] </mo>  </mrow>  <mo> = </mo>  <mrow>  <mo> [ </mo>  <mrow>  <mo> [ </mo>  <mi> a </mi>  <mo> , </mo>  <mspace width="thinmathspace" />  <mi> b </mi>  <mo> ] </mo>  </mrow>  <mo> , </mo>  <mspace width="thinmathspace" />  <mrow>  <mo> { </mo>  <mi> c </mi>  <mo> } </mo>  </mrow>  <mo> ] </mo>  </mrow>  <mspace width="thinmathspace" />  </math> \n',
    mml2: '<math>  <mrow>  <mo> [ </mo>  <mrow>  <mo> { </mo>  <mi> a </mi>  <mo> } </mo>  </mrow>  <mo> , </mo>   <mstyle>   <mrow>  <mo> [ </mo>  <mi> b </mi>  <mo> , </mo>   <mstyle>   <mi> c </mi>  <mo> ] </mo>  </mrow>  <mo> ] </mo>  </mrow>  <mo> = </mo>  <mrow>  <mo> [ </mo>  <mrow>  <mo> [ </mo>  <mi> a </mi>  <mo> , </mo>   <mstyle>   <mi> b </mi>  <mo> ] </mo>  </mrow>  <mo> , </mo>   <mstyle>   <mrow>  <mo> { </mo>  <mi> c </mi>  <mo> } </mo>  </mrow>  <mo> ] </mo>  </mrow>   <mstyle>   </math> \n'
  },
  {
    mml1: '<math>  <mi> x </mi>  <mo> &lt; </mo>  <mn> 4.5 </mn>  </math> \n',
    mml2: '<math>  <mi> x </mi>  <mo> &lt; </mo>  <mn> 4.5 </mn>  </math> \n'
  },
  {
    mml1: '<math>  <mo> ( </mo>  <msup>  <mi> &#x039B; <!-- Î\x9b -->  </mi>  <mrow>  <mn> 4 </mn>  <mo> &#x22C5; <!-- â\x8b\x85 -->  </mo>  <msup>  <mn> 2 </mn>  <mi> m </mi>  </msup>  </mrow>  </msup>  <mo> + </mo>  <msup>  <mi> &#x039B; <!-- Î\x9b -->  </mi>  <mrow>  <mo> &#x2212; <!-- â\x88\x92 -->  </mo>  <mn> 4 </mn>  <mo> &#x22C5; <!-- â\x8b\x85 -->  </mo>  <msup>  <mn> 2 </mn>  <mi> m </mi>  </msup>  </mrow>  </msup>  <mo> ) </mo>  <mrow>  <mi mathvariant="bold-italic"> u </mi>  </mrow>  <mo> = </mo>  </math> \n',
    mml2: '<math>  <mo> ( </mo>  <msup>  <mi> &#x039B; <!-- Î\x9b -->  </mi>  <mrow>  <mn> 4 </mn>  <mo> &#x22C5; <!-- â\x8b\x85 -->  </mo>  <msup>  <mn> 2 </mn>  <mi> m </mi>  </msup>  </mrow>  </msup>  <mo> + </mo>  <msup>  <mi> &#x039B; <!-- Î\x9b -->  </mi>  <mrow>  <mo> &#x2212; <!-- â\x88\x92 -->  </mo>  <mn> 4 </mn>  <mo> &#x22C5; <!-- â\x8b\x85 -->  </mo>  <msup>  <mn> 2 </mn>  <mi> m </mi>  </msup>  </mrow>  </msup>  <mo> ) </mo>  <mrow>   <mi>  u </mi>  </mrow>  <mo> = </mo>  </math> \n'
  },
];