eqn_src = [
  {
    eqn_num: 0,
    mml1: '<math>  <mi> h </mi>  <mrow>  <mi> i </mi>  <mi> n </mi>  </mrow>  <msup>  <mrow>  <mrow>   <mi>  R </mi>  </mrow>  </mrow>  <mrow>  <mi> m </mi>  </mrow>  </msup>  </math> \n',
    mml2: '<math> <mi> h </mi> <mrow> <mi> i </mi> <mi> n </mi> </mrow> <msup> <mrow> <mi> R </mi> </mrow> <mi> m </mi> </msup> </math>\n'
  },
  {
    eqn_num: 1,
    mml1: '<math>  <mrow>  <mover>  <mi> G </mi>  <mo> &#x02C7; <!-- Ë\x87 -->  </mo>  </mover>  </mrow>  <mo> = </mo>   <mstyle>   <mrow>  <mfrac>  <mn> 1 </mn>  <mi> &#x03C0; <!-- Ï\x80 -->  </mi>  </mfrac>  </mrow>  <msubsup>  <mo> &#x222B; <!-- â\x88« -->  </mo>  <mrow>  <mo> &#x2212; <!-- â\x88\x92 -->  </mo>  <mi> &#x221E; <!-- â\x88\x9e -->  </mi>  </mrow>  <mi> &#x221E; <!-- â\x88\x9e -->  </mi>  </msubsup>  </mstyle>  </math> \n',
    mml2: '<math> <mover> <mi> G </mi> <mo> &#x00AF; <!-- Â¯ --> </mo> </mover> <mo> = </mo> <mstyle> <mrow> <mfrac> <mn> 1 </mn> <mstyle> <mrow> <msub> <mi> p </mi> <mi> i </mi> </msub> </mrow> </mstyle> </mfrac> </mrow> <msubsup> <mo> &#x222B; <!-- â\x88« --> </mo> <mrow> <mo> &#x2212; <!-- â\x88\x92 --> </mo> <mi> &#x221E; <!-- â\x88\x9e --> </mi> </mrow> <mrow> <mi> &#x221E; <!-- â\x88\x9e --> </mi> </mrow> </msubsup> </mstyle> </math>\n'
  },
  {
    eqn_num: 2,
    mml1: '<math>   <mo>  &#x27E8; <!-- â\x9f¨ -->  </mo>  <mrow>  <msub>  <mi> &#x03BE; <!-- Î¾ -->  </mi>  <mn> 1 </mn>  </msub>  <msubsup>  <mi> x </mi>  <mn> 2 </mn>  <mn> 3 </mn>  </msubsup>   <mo>  &#x27E9; <!-- â\x9f© -->  </mo>  </mrow>  <mo> = </mo>   <mstyle>   <mrow>  <mfrac>  <mn> 3 </mn>  <mrow>  <mn> 16 </mn>  <mi> i </mi>  </mrow>  </mfrac>  </mrow>  <mo> ( </mo>  <msub>  <mi> z </mi>  <mn> 1 </mn>  </msub>  <msub>  <mi> z </mi>  <mn> 2 </mn>  </msub>  <msubsup>  <mover>  <mi> z </mi>  <mo> &#x00AF; <!-- Â¯ -->  </mo>  </mover>  <mn> 2 </mn>  <mn> 2 </mn>  </msubsup>  <mo> &#x2212; <!-- â\x88\x92 -->  </mo>  <msub>  <mover>  <mi> z </mi>  <mo> &#x00AF; <!-- Â¯ -->  </mo>  </mover>  <mn> 1 </mn>  </msub>  <msub>  <mover>  <mi> z </mi>  <mo> &#x00AF; <!-- Â¯ -->  </mo>  </mover>  <mn> 2 </mn>  </msub>  <msubsup>  <mi> z </mi>  <mn> 2 </mn>  <mn> 2 </mn>  </msubsup>  <mo> ) </mo>  <mo> = </mo>  <mo> &#x2212; <!-- â\x88\x92 -->  </mo>   <mstyle>   <mrow>  <mfrac>  <mn> 3 </mn>  <mn> 2 </mn>  </mfrac>  </mrow>  <msubsup>  <mi> &#x03F1; <!-- Ï± -->  </mi>  <mn> 1 </mn>  <mrow>  <mn> 1 </mn>  <mrow>  <mo> / </mo>  </mrow>  <mn> 2 </mn>  </mrow>  </msubsup>  <msubsup>  <mi> &#x03F1; <!-- Ï± -->  </mi>  <mn> 2 </mn>  <mrow>  <mn> 3 </mn>  <mrow>  <mo> / </mo>  </mrow>  <mn> 2 </mn>  </mrow>  </msubsup>  </mstyle>  </mstyle>  </math> \n',
    mml2: '<math> <mo> &#x27E8; <!-- â\x9f¨ --> </mo> <msub> <mi> &#x03BE; <!-- Î¾ --> </mi> <mn> 1 </mn> </msub> <msubsup> <mi> x </mi> <mn> 2 </mn> <mn> 3 </mn> </msubsup> <mo> &#x27E9; <!-- â\x9f© --> </mo> <mo> = </mo> <mstyle> <mrow> <mfrac> <mn> 3 </mn> <mrow> <mn> 16 </mn> <mi> i </mi> </mrow> </mfrac> </mrow> <mo> ( </mo> <msub> <mi> z </mi> <mn> 1 </mn> </msub> <msub> <mi> z </mi> <mn> 2 </mn> </msub> <msubsup> <mover> <mi> z </mi> <mo> &#x00AF; <!-- Â¯ --> </mo> </mover> <mn> 2 </mn> <mn> 2 </mn> </msubsup> <mo> &#x2212; <!-- â\x88\x92 --> </mo> <msub> <mover> <mi> z </mi> <mo> &#x00AF; <!-- Â¯ --> </mo> </mover> <mn> 1 </mn> </msub> <msub> <mover> <mi> z </mi> <mo> &#x00AF; <!-- Â¯ --> </mo> </mover> <mn> 2 </mn> </msub> <msubsup> <mi> z </mi> <mn> 2 </mn> <mn> 2 </mn> </msubsup> <mo> ) </mo> <mo> = </mo> <mo> &#x2212; <!--\n'
  },
  {
    eqn_num: 3,
    mml1: '<math>  <msub>  <mrow>   <mi>  P </mi>  </mrow>  <mrow>  <msub>  <mi> x </mi>  <mn> 0 </mn>  </msub>  </mrow>  </msub>  <mstyle scriptlevel="0">  <mrow>   <mi>  ( </mo>  </mrow>  </mstyle>   <mstyle>   <mrow>  <mfrac>  <mn> 1 </mn>  <mi> n </mi>  </mfrac>  </mrow>  <munder>  <mo> &#x2211; <!-- â\x88\x91 -->  </mo>  <mrow>  <mi> u </mi>  <mrow>  <mi> i </mi>  <mi> n </mi>  </mrow>  <mi> &#x039B; <!-- Î\x9b -->  </mi>  </mrow>  </munder>  <mi> sign </mi>  <mo> &#x2061; <!-- â\x81¡ -->  </mo>  <mo> ( </mo>  <msub>  <mi> R </mi>  <mrow>  <mi> t </mi>  </mrow>  </msub>  <mo> ( </mo>  <mi> u </mi>  <mo> , </mo>  <msub>  <mi> x </mi>  <mn> 0 </mn>  </msub>  <mo> ) </mo>  <mo> ) </mo>  <msub>  <mi> X </mi>  <mrow>  <mi> t </mi>  </mrow>  </msub>  <mo> ( </mo>  <mi> u </mi>  <mo> ) </mo>  <mo> &gt; </mo>   <mstyle>   <mrow>  <mfrac>  <mn> 1 </mn>  <mrow>  <mn> 2 </mn>  <msub>  <mi> a </mi>  <mi> n </mi>  </msub>  </mrow>  </mfrac>  </mrow>  <mstyle scriptlevel="0">  <mrow>   <mi>  ) </mo>  </mrow>  </mstyle>  <mo> &#x2192; <!-- â\x86\x92 -->  </mo>  <mn> 1 </mn>   <mi>   </mstyle>  </mstyle>  </math> \n',
    mml2: '<math> <msub> <mrow> <mi> P </mi> </mrow> <mrow> <msub> <mi> x </mi> <mn> 0 </mn> </msub> </mrow> </msub> <mstyle scriptlevel="0"> <mrow> <mi> ( </mo> </mrow> </mstyle> <mstyle> <mrow> <mfrac> <mn> 1 </mn> <mi> n </mi> </mfrac> </mrow> <munder> <mo> &#x2211; <!-- â\x88\x91 --> </mo> <mrow> <mi> u </mi> <mrow> <mi> i </mi> <mi> n </mi> </mrow> <mi> &#x039B; <!-- Î\x9b --> </mi> </mrow> </munder> <mrow> <mi> s </mi> <mi> i </mi> <mi> g </mi> <mi> n </mi> </mrow> <mo> ( </mo> <msub> <mi> R </mi> <mi> t </mi> </msub> <mo> ( </mo> <mi> u </mi> <mo> , </mo> <msub> <mi> x </mi> <mn> 0 </mn> </msub> <mo> ) </mo> <mo> ) </mo> <msub> <mi> X </mi> <mi> t </mi> </msub> <mo> ( </mo> <mi> u </mi> <mo> ) </mo> <mo> &gt; </mo> <mstyle> <mrow> <mfrac> <mn> 1 </mn> <mrow> <mn> 2 </mn> <msub> <mi> a </mi> <mi> n </mi> </msub>\n'
  },
  {
    eqn_num: 4,
    mml1: '<math>  <msup>  <mrow>  <mover>  <mi> &#x03A8; <!-- Î¨ -->  </mi>  <mo> &#x007E; <!-- ~ -->  </mo>  </mover>  </mrow>  <mi> &#x03B5; <!-- Îµ -->  </mi>  </msup>  <mo> ( </mo>  <mi> t </mi>  <mo> , </mo>  <mi> x </mi>  <mo> , </mo>  <mi> y </mi>  <mo> ) </mo>  <mo> = </mo>   <mstyle>   <mrow>  <mfrac>  <mn> 1 </mn>  <msqrt>  <mn> 2 </mn>   <mstyle>   <mrow>  <msub>  <mi> p </mi>  <mi> i </mi>  </msub>  </mrow>  </mstyle>  <mi> &#x03B5; <!-- Îµ -->  </mi>  </msqrt>  </mfrac>  </mrow>  <msub>  <mo> &#x222B; <!-- â\x88« -->  </mo>  <mrow>  <msub>  <mi> K </mi>  <mn> 0 </mn>  </msub>  </mrow>  </msub>  <munderover>  <mo> &#x2211; <!-- â\x88\x91 -->  </mo>  <mrow>  <mi> n </mi>  <mo> = </mo>  <mn> 1 </mn>  </mrow>  <mi> N </mi>  </munderover>  <msubsup>  <mrow>  <mover>  <mi> &#x03A8; <!-- Î¨ -->  </mi>  <mo> &#x007E; <!-- ~ -->  </mo>  </mover>  </mrow>  <mrow>  <mi> G </mi>  <mi> B </mi>  </mrow>  <mrow>  <mi> &#x03B5; <!-- Îµ -->  </mi>  <mi> n </mi>  </mrow>  </msubsup>  <mo> ( </mo>  <mi> t </mi>  <mo> , </mo>  <mi> x </mi>  <mo> , </mo>  <mi> y </mi>  <mo> , </mo>  <msub>  <mi> x </mi>  <mn> 0 </mn>  </msub>  <mo> ) </mo>  <mi> d </mi>  <msub>  <mi> x </mi>  <mn> 0 </mn>  </msub>  </mstyle>  </math> \n',
    mml2: '<math> <msup> <mrow> <mover> <mi> &#x03A8; <!-- Î¨ --> </mi> <mo> &#x007E; <!-- ~ --> </mo> </mover> </mrow> <mrow> <mi> &#x03B5; <!-- Îµ --> </mi> </mrow> </msup> <mo> ( </mo> <mi> t </mi> <mo> , </mo> <mi> x </mi> <mo> , </mo> <mi> y </mi> <mo> ) </mo> <mo> = </mo> <mstyle> <mrow> <mfrac> <mn> 1 </mn> <msqrt> <mn> 2 </mn> <mstyle> <mrow> <msub> <mi> p </mi> <mi> i </mi> </msub> </mrow> </mstyle> <mi> &#x03B5; <!-- Îµ --> </mi> </msqrt> </mfrac> </mrow> <msub> <mo> &#x222B; <!-- â\x88« --> </mo> <mrow> <msub> <mi> K </mi> <mrow> <mn> 0 </mn> </mrow> </msub> </mrow> </msub> <munderover> <mo> &#x2211; <!-- â\x88\x91 --> </mo> <mrow> <mi> n </mi> <mo> = </mo> <mn> 1 </mn> </mrow> <mrow> <mi> N </mi> </mrow> </munderover> <msubsup> <mrow> <mover> <mi> &#x03A8; <!-- Î¨ --> </mi> <mo> &#x007E; <!-- ~ --> </mo> </mover> </mrow> <mrow> <mi> G </mi> <mi> B </mi>\n'
  },
  {
    eqn_num: 5,
    mml1: '<math>  <msub>  <mi> A </mi>  <mrow>  <mi> &#x03B4; <!-- Î´ -->  </mi>  </mrow>  </msub>  <mo> = </mo>   <mstyle>   <mrow>  <mfrac>  <mn> 1 </mn>  <msup>  <mi> q </mi>  <mi> k </mi>  </msup>  </mfrac>  </mrow>  <munder>  <mo> &#x2211; <!-- â\x88\x91 -->  </mo>  <mrow>  <munder>  <mi> s </mi>  <mo> &#x005F; <!-- _ -->  </mo>  </munder>  </mrow>  </munder>  <msub>  <mi> A </mi>  <mrow>  <mi> &#x03B4; <!-- Î´ -->  </mi>  <mrow>  <mo> | </mo>  </mrow>  <munder>  <mi> s </mi>  <mo> &#x005F; <!-- _ -->  </mo>  </munder>  </mrow>  </msub>  </mstyle>  </math> \n',
    mml2: '<math> <msub> <mi> A </mi> <mi> &#x03B4; <!-- Î´ --> </mi> </msub> <mo> = </mo> <mstyle> <mrow> <mfrac> <mn> 1 </mn> <msup> <mi> q </mi> <mi> k </mi> </msup> </mfrac> </mrow> <munder> <mo> &#x2211; <!-- â\x88\x91 --> </mo> <mi> z </mi> </munder> <msub> <mi> A </mi> <mrow> <mi> &#x03B4; <!-- Î´ --> </mi> <mrow> <mo> | </mo> </mrow> <mi> S </mi> </mrow> </msub> </mstyle> </math>\n'
  },
  {
    eqn_num: 6,
    mml1: '<math>  <msubsup>  <mi> &#x03B3; <!-- Î³ -->  </mi>  <mi> m </mi>  <mrow>  <mo> &#x2192; <!-- â\x86\x92 -->  </mo>  </mrow>  </msubsup>  <mo> = </mo>  <msub>  <mi> &#x03B3; <!-- Î³ -->  </mi>  <mi> m </mi>  </msub>   <mstyle>   <mrow>  <mfrac>  <msubsup>  <mi> &#x03F1; <!-- Ï± -->  </mi>  <mi> m </mi>  <mrow> \n',
    mml2: '<math> <msubsup> <mi> &#x03B3; <!-- Î³ --> </mi> <mi> m </mi> <mo> &#x2212; <!-- â\x88\x92 --> </mo> </msubsup> <mo> = </mo> <msub> <mi> &#x03B3; <!-- Î³ --> </mi> <mi> m </mi> </msub> <mstyle> <mrow> <mfrac> <msub> <mi> &#x03F1; <!-- Ï± --> </mi> <mi> m </mi> </msub> <mi> &#x03F1; <!-- Ï± --> </mi> </mfrac> </mrow> </mstyle> </math>\n'
  },
  {
    eqn_num: 7,
    mml1: '<math>  <msup>  <mi> u </mi>  <mrow>  <mn> 0 </mn>  </mrow>  </msup>  <mrow>  <mi> i </mi>  <mi> n </mi>  </mrow>  <mrow>   <mi>  R </mi>  </mrow>  </math> \n',
    mml2: '<math> <msup> <mi> u </mi> <mn> 0 </mn> </msup> <mrow> <mi> i </mi> <mi> n </mi> </mrow> <mrow> <mi> R </mi> </mrow> </math>\n'
  },
  {
    eqn_num: 8,
    mml1: '<math>  <mi> P </mi>  <mrow>   <mo>   <mtext> &#x29F8; </mtext>   <mo>   </mrow>  <mrow>  <mi> i </mi>  <mi> n </mi>  </mrow>  <mi> l </mi>  </math> \n',
    mml2: '<math> <mi> P </mi> <mrow> <mstyle> <mtext> &#x29F8; </mtext> <mstyle> </mrow> <mrow> <mi> i </mi> <mi> n </mi> </mrow> <mi> l </mi> </math>\n'
  },
  {
    eqn_num: 9,
    mml1: '<math>  <msub>  <mi> &#x03B1; <!-- Î± -->  </mi>  <mi> &#x2113; <!-- â\x84\x93 -->  </mi>  </msub>  <mo> = </mo>  <mi> &#x03B1; <!-- Î± -->  </mi>  </math> \n',
    mml2: '<math> <msub> <mi> &#x03B1; <!-- Î± --> </mi> <mrow> <mi> &#x2113; <!-- â\x84\x93 --> </mi> </mrow> </msub> <mo> = </mo> <mi> &#x03B1; <!-- Î± --> </mi> </math>\n'
  },
  {
    eqn_num: 10,
    mml1: '<math>  <mrow>  <mrow>   <mi>  P </mi>  </mrow>  </mrow>  <mrow>  <mo> [ </mo>  <mrow>  <mi> S </mi>  <mo> = </mo>  <mn> 1 </mn>  </mrow>  <mo> ] </mo>  </mrow>  <mo> = </mo>  <mrow>  <mrow>   <mi>  P </mi>  </mrow>  </mrow>  <mrow>  <mo> [ </mo>  <mrow>  <mi> S </mi>  <mo> = </mo>  <mn> 0 </mn>  </mrow>  <mo> ] </mo>  </mrow>  <mo> = </mo>  <mn> 1 </mn>  <mrow>  <mo> / </mo>  </mrow>  <mn> 2 </mn>  </math> \n',
    mml2: '<math> <mrow> <mi> P </mi> </mrow> <mrow> <mo> [ </mo> <mi> S </mi> <mo> = </mo> <mn> 1 </mn> <mo> ] </mo> </mrow> <mo> = </mo> <mrow> <mi> P </mi> </mrow> <mrow> <mo> [ </mo> <mi> S </mi> <mo> = </mo> <mn> 0 </mn> <mo> ] </mo> </mrow> <mo> = </mo> <mn> 1 </mn> <mrow> <mo> / </mo> </mrow> <mn> 2 </mn> </math>\n'
  },
  {
    eqn_num: 11,
    mml1: '<math>  <msubsup>  <mi> &#x03C9; <!-- Ï\x89 -->  </mi>  <mrow>  <mo> + </mo>  <mo> &#x2212; <!-- â\x88\x92 -->  </mo>  </mrow>  <mrow>  <mn> 1 </mn>  </mrow>  </msubsup>  <mo> = </mo>  <mrow>  <mphantom>  <mo> &#x2212; <!-- â\x88\x92 -->  </mo>  </mphantom>  </mrow>  <mi> &#x03A9; <!-- Î© -->  </mi>  <mo> + </mo>  <mi> &#x03C9; <!-- Ï\x89 -->  </mi>  <mo> &gt; </mo>  <mn> 0 </mn>  </math> \n',
    mml2: '<math> <msubsup> <mi> &#x03C9; <!-- Ï\x89 --> </mi> <mrow> <mo> + </mo> <mo> &#x2212; <!-- â\x88\x92 --> </mo> </mrow> <mn> 1 </mn> </msubsup> <mo> = </mo> <mtext> &#xA0; </mtext> <mtext> &#xA0; </mtext> <mi> &#x03A9; <!-- Î© --> </mi> <mo> + </mo> <mi> &#x03C9; <!-- Ï\x89 --> </mi> <mo> &gt; </mo> <mn> 0 </mn> </math>\n'
  },
  {
    eqn_num: 12,
    mml1: '<math>  <mi> &#x0394; <!-- Î\x94 -->  </mi>  <msub>  <mi> s </mi>  <mrow>  <mi> t </mi>  <mi> o </mi>  <mi> t </mi>  </mrow>  </msub>  <mo> [ </mo>  <mrow>   <mi>  X </mi>  </mrow>  <mo> , </mo>  <mrow>  <msub>   <mi>  X </mi>  <mo> &#x2212; <!-- â\x88\x92 -->  </mo>  </msub>  </mrow>  <mo> ] </mo>  <mo> &#x2261; <!-- â\x89¡ -->  </mo>  <mi> &#x0394; <!-- Î\x94 -->  </mi>  <msub>  <mi> s </mi>  <mi> m </mi>  </msub>  <mo> [ </mo>  <mrow>   <mi>  X </mi>  </mrow>  <mo> , </mo>  <mrow>  <msub>   <mi>  X </mi>  <mo> &#x2212; <!-- â\x88\x92 -->  </mo>  </msub>  </mrow>  <mo> ] </mo>  <mo> + </mo>  <mi> ln </mi>  <mo> &#x2061; <!-- â\x81¡ -->  </mo>  <msub>  <mi> p </mi>  <mrow>  <mi> s </mi>  <mi> t </mi>  </mrow>  </msub>  <mo> ( </mo>  <msub>  <mrow>   <mi>  x </mi>  </mrow>  <mi> i </mi>  </msub>  <mo> ) </mo>  <mrow>  <mo> / </mo>  </mrow>  <msub>  <mi> p </mi>  <mrow>  <mi> s </mi>  <mi> t </mi>  </mrow>  </msub>  <mo> ( </mo>  <msubsup>  <mrow>   <mi>  x </mi>  </mrow>  <mi> i </mi>  <mo> &#x2020; <!-- â\x80\xa0 -->  </mo>  </msubsup>  <mo> ) </mo>  </math> \n',
    mml2: '<math> <mi> &#x0394; <!-- Î\x94 --> </mi> <msub> <mi> s </mi> <mrow> <mi> t </mi> <mi> o </mi> <mi> t </mi> </mrow> </msub> <mo> [ </mo> <mrow> <mi> X </mi> </mrow> <mo> , </mo> <msub> <mrow> <mi> X </mi> </mrow> <mo> &#x2212; <!-- â\x88\x92 --> </mo> </msub> <mo> ] </mo> <mo> &#x2261; <!-- â\x89¡ --> </mo> <mi> &#x0394; <!-- Î\x94 --> </mi> <msub> <mi> s </mi> <mi> m </mi> </msub> <mo> [ </mo> <mrow> <mi> X </mi> </mrow> <mo> , </mo> <msub> <mrow> <mi> X </mi> </mrow> <mo> &#x2212; <!-- â\x88\x92 --> </mo> </msub> <mo> ] </mo> <mo> + </mo> <mi> ln </mi> <mo> &#x2061; <!-- â\x81¡ --> </mo> <msub> <mi> p </mi> <mrow> <mi> s </mi> <mi> t </mi> </mrow> </msub> <mo> ( </mo> <msub> <mrow> <mi> x </mi> </mrow> <mi> i </mi> </msub> <mo> ) </mo> <mrow> <mo> / </mo> </mrow> <msub> <mi> p </mi> <mrow> <mi> s\n'
  },
  {
    eqn_num: 13,
    mml1: '<math>  <mrow>  <mo> { </mo>  <mi> f </mi>  <mo> , </mo>   <mstyle>   <mi> g </mi>  <mo> , </mo>   <mstyle>   <mi> p </mi>  <msup>  <mi> f </mi>  <mrow>  <mi> &#x2032; <!-- â\x80² -->  </mi>  </mrow>  </msup>  <mo> , </mo>   <mstyle>   <mi> p </mi>  <msup>  <mi> g </mi>  <mrow>  <mi> &#x2032; <!-- â\x80² -->  </mi>  </mrow>  </msup>  <mo> } </mo>  </mrow>  <mo> &#x2286; <!-- â\x8a\x86 -->  </mo>  <msup>  <mi> C </mi>  <mrow>  <mn> 1 </mn>  </mrow>  </msup>  <mo> [ </mo>  <mi> a </mi>  <mo> , </mo>  <mi> b </mi>  <mo> ] </mo>  </math> \n',
    mml2: '<math> <mo> { </mo> <mi> f </mi> <mo> , </mo> <mstyle> <mi> g </mi> <mo> , </mo> <mstyle> <mi> p </mi> <msup> <mi> f </mi> <mo> &#x2032; </mo> </msup> <mo> , </mo> <mstyle> <mi> p </mi> <msup> <mi> g </mi> <mo> &#x2032; </mo> </msup> <mo> } </mo> <mo> &#x2286; <!-- â\x8a\x86 --> </mo> <msup> <mi> C </mi> <mn> 1 </mn> </msup> <mo> [ </mo> <mi> a </mi> <mo> , </mo> <mi> b </mi> <mo> ] </mo> </math>\n'
  },
  {
    eqn_num: 14,
    mml1: '<math>  <mi> b </mi>  <mo> ( </mo>  <mi> g </mi>  <mi> h </mi>  <mo> ) </mo>  <mo> = </mo>  <mi> c </mi>  <mo> ( </mo>  <mi> g </mi>  <mi> h </mi>  <msub>  <mi> x </mi>  <mn> 0 </mn>  </msub>  <mo> , </mo>  <msub>  <mi> x </mi>  <mn> 0 </mn>  </msub>  <mo> ) </mo>  <mo> = </mo>  <mi> c </mi>  <mo> ( </mo>  <mi> g </mi>  <mi> h </mi>  <msub>  <mi> x </mi>  <mn> 0 </mn>  </msub>  <mo> , </mo>  <mi> g </mi>  <msub>  <mi> x </mi>  <mn> 0 </mn>  </msub>  <mo> ) </mo>  <mo> + </mo>  <mi> c </mi>  <mo> ( </mo>  <mi> g </mi>  <msub>  <mi> x </mi>  <mn> 0 </mn>  </msub>  <mo> , </mo>  <msub>  <mi> x </mi>  <mn> 0 </mn>  </msub>  <mo> ) </mo>  <mo> = </mo>  <mi> &#x03C0; <!-- Ï\x80 -->  </mi>  <mo> ( </mo>  <mi> g </mi>  <mo> ) </mo>  <mi> b </mi>  <mo> ( </mo>  <mi> h </mi>  <mo> ) </mo>  <mo> + </mo>  <mi> b </mi>  <mo> ( </mo>  <mi> g </mi>  <mo> ) </mo>  </math> \n',
    mml2: '<math> <mi> b </mi> <mo> ( </mo> <mi> g </mi> <mi> h </mi> <mo> ) </mo> <mo> = </mo> <mi> c </mi> <mo> ( </mo> <mi> g </mi> <mi> h </mi> <msub> <mi> x </mi> <mn> 0 </mn> </msub> <mo> , </mo> <msub> <mi> x </mi> <mn> 0 </mn> </msub> <mo> ) </mo> <mo> = </mo> <mi> c </mi> <mo> ( </mo> <mi> g </mi> <mi> h </mi> <msub> <mi> x </mi> <mn> 0 </mn> </msub> <mo> , </mo> <mi> g </mi> <msub> <mi> x </mi> <mn> 0 </mn> </msub> <mo> ) </mo> <mo> + </mo> <mi> c </mi> <mo> ( </mo> <mi> g </mi> <msub> <mi> x </mi> <mn> 0 </mn> </msub> <mo> , </mo> <msub> <mi> x </mi> <mn> 0 </mn> </msub> <mo> ) </mo> <mo> = </mo> <mstyle> <mrow> <msub> <mi> p </mi> <mi> i </mi> </msub> </mrow> </mstyle> <mo> ( </mo> <mi> g </mi> <mo> )\n'
  },
  {
    eqn_num: 15,
    mml1: '<math>  <msub>  <mi> T </mi>  <mrow>  <mn> 00 </mn>  </mrow>  </msub>  <mo> = </mo>  <mi> &#x03F1; <!-- Ï± -->  </mi>   <mo>   <mo> , </mo>  </math> \n',
    mml2: '<math> <msub> <mi> T </mi> <mrow> <mn> 00 </mn> </mrow> </msub> <mo> = </mo> <mi> &#x03F1; <!-- Ï± --> </mi> <mtext> &#xA0; </mtext> <mo> , </mo> <mstyle> </math>\n'
  },
  {
    eqn_num: 16,
    mml1: '<math>  <msub>  <mi> J </mi>  <mn> 2 </mn>  </msub>  <mo> &#x2A7D; <!-- â©½ -->  </mo>  <mi> C </mi>  <mstyle scriptlevel="0">  <mrow>   <mi>  &#x2016; </mo>  </mrow>  </mstyle>  <mstyle scriptlevel="0">  <mrow>   <mi>  ( </mo>  </mrow>  </mstyle>  <munder>  <mo> &#x2211; <!-- â\x88\x91 -->  </mo>  <mrow>  <mi> j </mi>  </mrow>  </munder>  <mi> big </mi>  <mo> &#x2061; <!-- â\x81¡ -->  </mo>  <mrow>  <mo> | </mo>  </mrow>  <msub>  <mi> f </mi>  <mi> j </mi>  </msub>  <mi> big </mi>  <mo> &#x2061; <!-- â\x81¡ -->  </mo>  <msup>  <mrow>  <mo> | </mo>  </mrow>  <mn> 2 </mn>  </msup>  <msup>  <mstyle scriptlevel="0">  <mrow>   <mi>  ) </mo>  </mrow>  </mstyle>  <mrow>  <mn> 1 </mn>  <mrow>  <mo> / </mo>  </mrow>  <mn> 2 </mn>  </mrow>  </msup>  <msub>  <mstyle scriptlevel="0">  <mrow>   <mi>  &#x2016; </mo>  </mrow>  </mstyle>  <mrow>  <msup>  <mi> L </mi>  <mrow>  <mi> p </mi>  <mo> , </mo>  <mi> &#x03A6; <!-- Î¦ -->  </mi>  </mrow>  </msup>  </mrow>  </msub>  </math> \n',
    mml2: '<math> <msub> <mi> J </mi> <mn> 2 </mn> </msub> <mo> &#x2A7D; <!-- â©½ --> </mo> <mi> C </mi> <mstyle scriptlevel="0"> <mrow> <mi> &#x2016; </mo> </mrow> </mstyle> <mstyle scriptlevel="0"> <mrow> <mi> ( </mo> </mrow> </mstyle> <munder> <mo> &#x2211; <!-- â\x88\x91 --> </mo> <mi> j </mi> </munder> <msup> <mrow> <mo> | </mo> <msub> <mi> f </mi> <mi> j </mi> </msub> <mo> | </mo> </mrow> <mn> 2 </mn> </msup> <msup> <mstyle scriptlevel="0"> <mrow> <mi> ) </mo> </mrow> </mstyle> <mrow> <mn> 1 </mn> <mrow> <mo> / </mo> </mrow> <mn> 2 </mn> </mrow> </msup> <msub> <mstyle scriptlevel="0"> <mrow> <mi> &#x2016; </mo> </mrow> </mstyle> <mrow> <msup> <mi> L </mi> <mrow> <mi> p </mi> <mo> , </mo> <mi> &#x03A6; <!-- Î¦ --> </mi> </mrow> </msup> </mrow> </msub> </math>\n'
  },
  {
    eqn_num: 17,
    mml1: '<math>  <msup>  <mi> G </mi>  <mrow>  <mo> ( </mo>  <mn> 3 </mn>  <mo> ) </mo>  </mrow>  </msup>  <mo> ( </mo>  <mi> A </mi>  <mo> ; </mo>  <mn> 1 </mn>  <mo> , </mo>  <mo> &#x2026; <!-- â\x80¦ -->  </mo>  <mo> , </mo>  <mi> A </mi>  <mo> &#x2212; <!-- â\x88\x92 -->  </mo>  <mn> 1 </mn>  <mo> ) </mo>  <mo> = </mo>  <munderover>  <mo> &#x2211; <!-- â\x88\x91 -->  </mo>  <mrow>  <mi> i </mi>  <mo> &#x2260; </mo>  <mi> &#x2205; <!-- â\x88\x85 -->  </mi>  <mi> j </mi>  <mo> &#x2260; </mo>  <mi> &#x2205; <!-- â\x88\x85 -->  </mi>  <mi> k </mi>  <mo> = </mo>  <mn> 1 </mn>  </mrow>  <mrow>  <mi> A </mi>  <mo> &#x2212; <!-- â\x88\x92 -->  </mo>  <mn> 1 </mn>  </mrow>  </munderover>  </math> \n',
    mml2: '<math> <msup> <mi> G </mi> <mrow> <mo> ( </mo> <mn> 3 </mn> <mo> ) </mo> </mrow> </msup> <mo> ( </mo> <mi> A </mi> <mo> ; </mo> <mn> 1 </mn> <mo> &#x2026; <!-- â\x80¦ --> </mo> <mi> A </mi> <mo> &#x2212; <!-- â\x88\x92 --> </mo> <mn> 1 </mn> <mo> ) </mo> <mo> = </mo> <munderover> <mo> &#x2211; <!-- â\x88\x91 --> </mo> <mrow> <mi> i </mi> <mo> &#x2260; <!-- â\x89 --> </mo> <mi> j </mi> <mo> &#x2260; <!-- â\x89 --> </mo> <mi> k </mi> <mo> = </mo> <mn> 1 </mn> </mrow> <mrow> <mi> A </mi> <mo> &#x2212; <!-- â\x88\x92 --> </mo> <mn> 1 </mn> </mrow> </munderover> </math>\n'
  },
  {
    eqn_num: 18,
    mml1: '<math>  <munder>   <mi>  max </mo>  <mrow>  <mrow>   <mi>  y </mi>  </mrow>  </mrow>  </munder>   <mi>   <msup>  <mrow>   <mi>  w </mi>  </mrow>  <mi> T </mi>  </msup>  <mrow>   <mi>  y </mi>  </mrow>  <mo> , </mo>   <mi>    <mi>   </math> \n',
    mml2: '<math> <munder> <mi> max </mo> <mrow> <mrow> <mi> y </mi> </mrow> </mrow> </munder> <mtext> &#xA0; </mtext> <msup> <mrow> <mi> w </mi> </mrow> <mrow> <mi> T </mi> </mrow> </msup> <mrow> <mi> y </mi> </mrow> <mo> , </mo> <mstyle> </math>\n'
  },
  {
    eqn_num: 19,
    mml1: '<math>  <mi> n </mi>  <mo> = </mo>  <mn> 1 </mn>  <mo> , </mo>  <mn> 2 </mn>  <mo> , </mo>  <mo> &#x2026; <!-- â\x80¦ -->  </mo>  </math> \n',
    mml2: '<math> <mi> n </mi> <mo> = </mo> <mn> 1 </mn> <mo> , </mo> <mn> 2 </mn> <mo> , </mo> <mo> , </mo> <mo> &#x2026; <!-- â\x80¦ --> </mo> <mo> , </mo> </math>\n'
  },
  {
    eqn_num: 20,
    mml1: '<math>  <mover>  <mrow>  <mi> &#x03C6; <!-- Ï\x86 -->  </mi>  <mtext> &#xA0; </mtext>  </mrow>  <mo> &#x22C5; <!-- â\x8b\x85 -->  </mo>  </mover>  <mo> = </mo>  <mrow>  <mo> ( </mo>   <mstyle>   <mrow>  <mfrac>  <mrow>  <mi> d </mi>  <mi> &#x03C6; <!-- Ï\x86 -->  </mi>  </mrow>  <mrow>  <mi> d </mi>  <mi> &#x03C4; <!-- Ï\x84 -->  </mi>  </mrow>  </mfrac>  </mrow>  </mstyle>  <mo> ) </mo>  </mrow>  <mo> = </mo>  </math> \n',
    mml2: '<math> <mi> &#x03C6; <!-- Ï\x86 --> </mi> <mtext> &#xA0; </mtext> <mo> = </mo> <mrow> <mo> ( </mo> <mstyle> <mrow> <mfrac> <mrow> <mi> d </mi> <mi> &#x03C6; <!-- Ï\x86 --> </mi> </mrow> <mrow> <mi> d </mi> <mi> &#x03C4; <!-- Ï\x84 --> </mi> </mrow> </mfrac> </mrow> </mstyle> <mo> ) </mo> </mrow> <mo> = </mo> </math>\n'
  },
  {
    eqn_num: 21,
    mml1: '<math>  <msub>  <mi> y </mi>  <mn> 1 </mn>  </msub>  <msup>  <mi> e </mi>  <mrow>  <msub>  <mi> y </mi>  <mn> 1 </mn>  </msub>  </mrow>  </msup>   <mi>    <mstyle>   <mfrac>  <mrow>  <mn> 2 </mn>  <msub>  <mi> y </mi>  <mn> 2 </mn>  </msub>  </mrow>  <mrow>  <mi> sin </mi>  <mo> &#x2061; <!-- â\x81¡ -->  </mo>  <mo> ( </mo>  <msub>  <mi> y </mi>  <mn> 2 </mn>  </msub>  <mo> ) </mo>  </mrow>  </mfrac>  </mstyle>  <mo> = </mo>  <mi> &#x03BB; <!-- Î» -->  </mi>  </math> \n',
    mml2: '<math> <msub> <mi> y </mi> <mn> 1 </mn> </msub> <msup> <mi> e </mi> <mrow> <msub> <mi> y </mi> <mn> 1 </mn> </msub> </mrow> </msup> <mstyle> <mstyle> <mrow> <mfrac> <mrow> <mn> 2 </mn> <msub> <mi> y </mi> <mn> 2 </mn> </msub> </mrow> <mrow> <mrow> <mi> s </mi> <mi> i </mi> <mi> n </mi> </mrow> <mo> ( </mo> <msub> <mi> y </mi> <mn> 2 </mn> </msub> <mo> ) </mo> </mrow> </mfrac> </mrow> <mo> = </mo> <mi> &#x03BB; <!-- Î» --> </mi> </mstyle> </math>\n'
  },
  {
    eqn_num: 22,
    mml1: '<math>  <msub>  <mi> &#x03A9; <!-- Î© -->  </mi>  <mtext> tg </mtext>  </msub>  <mo> = </mo>  <mn> 0.05 </mn>  <mi> &#x03C9; <!-- Ï\x89 -->  </mi>  </math> \n',
    mml2: '<math> <msub> <mi> &#x03A9; <!-- Î© --> </mi> <mrow> <mi> i </mi> <mi> g </mi> </mrow> </msub> <mo> = </mo> <mn> 0.05 </mn> <mi> &#x03C9; <!-- Ï\x89 --> </mi> </math>\n'
  },
  {
    eqn_num: 23,
    mml1: '<math>  <mrow>  <mi> I </mi>  </mrow>  <msub>  <mi> g </mi>  <mrow>  <mi> r </mi>  </mrow>  </msub>  <mo> ( </mo>  <mi> x </mi>  <mo> ) </mo>   <mstyle>   <mo> &#x2A7E; <!-- â©¾ -->  </mo>   <mstyle>   <msub>  <mi> c </mi>  <mrow>  <mn> 3 </mn>  </mrow>  </msub>  <msup>  <mi> r </mi>  <mrow>  <mo> &#x2212; <!-- â\x88\x92 -->  </mo>  <mi> &#x03B1; <!-- Î± -->  </mi>  </mrow>  </msup>  </math> \n',
    mml2: '<math> <mrow> <mi> I </mi> </mrow> <msub> <mi> g </mi> <mi> r </mi> </msub> <mo> ( </mo> <mi> x </mi> <mo> ) </mo> <mtext> &#xA0; </mtext> <mo> &#x2A7E; <!-- â©¾ --> </mo> <mtext> &#xA0; </mtext> <msub> <mi> c </mi> <mn> 3 </mn> </msub> <msup> <mi> r </mi> <mrow> <mo> &#x2212; <!-- â\x88\x92 --> </mo> <mi> &#x03B1; <!-- Î± --> </mi> </mrow> </msup> </math>\n'
  },
  {
    eqn_num: 24,
    mml1: '<math>  <msub>  <mrow>   <mi>  s </mi>  </mrow>  <mo> = </mo>  </msub>  <munder>  <mrow>  <mi> a </mi>  <mi> r </mi>  <mi> g </mi>   <mo>   <mi> m </mi>  <mi> a </mi>  <mi> x </mi>  </mrow>  <mrow>  <mrow>   <mi>  s </mi>  </mrow>  <mrow>  <mi> i </mi>  <mi> n </mi>  </mrow>  <msubsup>  <mrow>  <mi> A </mi>  </mrow>  <mi> M </mi>  <mi> N </mi>  </msubsup>  </mrow>  </munder>   <mstyle>   <mrow>  <mfrac>  <mrow>  <msup>  <mrow>   <mi>  s </mi>  </mrow>  <mrow>  <mi> H </mi>  </mrow>  </msup>  <mrow>   <mi>  V </mi>  </mrow>  <msup>  <mrow>   <mi>  V </mi>  </mrow>  <mrow>  <mi> H </mi>  </mrow>  </msup>  <mrow>   <mi>  s </mi>  </mrow>  </mrow>  <mrow>  <msup>  <mrow>   <mi>  s </mi>  </mrow>  <mrow>  <mi> H </mi>  </mrow>  </msup>  <mrow>   <mi>  s </mi>  </mrow>  </mrow>  </mfrac>  </mrow>  </mstyle>  </math> \n',
    mml2: '<math> <msub> <mrow> <mi> s </mi> </mrow> <mo> = </mo> </msub> <munder> <mi> argmin </mo> <mrow> <mi> s </mi> <mrow> <mi> i </mi> <mi> n </mi> </mrow> <msubsup> <mrow> <mi> A </mi> </mrow> <mi> M </mi> <mi> N </mi> </msubsup> </mrow> </munder> <mstyle> <mrow> <mfrac> <mrow> <msup> <mrow> <mi> s </mi> </mrow> <mrow> <mrow> <mi> H </mi> </mrow> </mrow> </msup> <mrow> <mi> V </mi> </mrow> <msup> <mrow> <mi> V </mi> </mrow> <mrow> <mi> H </mi> </mrow> </msup> <mrow> <mi> s </mi> </mrow> </mrow> <mrow> <msup> <mrow> <mi> s </mi> </mrow> <mrow> <mrow> <mi> H </mi> </mrow> </mrow> </msup> <mrow> <mi> s </mi> </mrow> </mrow> </mfrac> </mrow> </mstyle> </math>\n'
  },
  {
    eqn_num: 25,
    mml1: '<math>  <msub>  <mi> d </mi>  <mn> 1 </mn>  </msub>   <mi>   <mo> = </mo>   <mi>   <mn> 0 </mn>  </math> \n',
    mml2: '<math> <msub> <mi> d </mi> <mn> 1 </mn> </msub> <mstyle> <mo> = </mo> <mstyle> <mn> 0 </mn> </math>\n'
  },
  {
    eqn_num: 26,
    mml1: '<math>  <mo> ( </mo>  <mi> Z </mi>  <mrow>  <mo> / </mo>  </mrow>  <mi> X </mi>  <msub>  <mo> ) </mo>  <mrow>  <mo> &#x2299; <!-- â\x8a\x99 -->  </mo>  </mrow>  </msub>  <mo> = </mo>  <mn> 0.0178 </mn>  </math> \n',
    mml2: '<math> <mo> ( </mo> <mi> Z </mi> <mrow> <mo> / </mo> </mrow> <mi> X </mi> <msub> <mo> ) </mo> <mo> &#x2299; <!-- â\x8a\x99 --> </mo> </msub> <mo> = </mo> <mn> <unk> </mn> </math>\n'
  },
  {
    eqn_num: 27,
    mml1: '<math>  <msubsup>  <mi> &#x03C6; <!-- Ï\x86 -->  </mi>  <mrow>  <msub>  <mi> J </mi>  <mrow>  <mi> &#x03C4; <!-- Ï\x84 -->  </mi>  </mrow>  </msub>  <msub>  <mi> M </mi>  <mrow>  <mi> &#x03C4; <!-- Ï\x84 -->  </mi>  </mrow>  </msub>  </mrow>  <mrow>  <mo> ( </mo>  <mi> g </mi>  <mo> ) </mo>  </mrow>  </msubsup>  <mo> = </mo>  <msubsup>  <mi> N </mi>  <mrow>  <msub>  <mi> J </mi>  <mrow>  <mi> &#x03C4; <!-- Ï\x84 -->  </mi>  </mrow>  </msub>  </mrow>  <mrow>  <mo> ( </mo>  <mi> g </mi>  <mo> ) </mo>  </mrow>  </msubsup>  <msubsup>  <mi> P </mi>  <mrow>  <msub>  <mi> M </mi>  <mrow>  <mi> &#x03C4; <!-- Ï\x84 -->  </mi>  </mrow>  </msub>  <mn> 0 </mn>  </mrow>  <mrow>  <msub>  <mi> J </mi>  <mrow>  <mi> &#x03C4; <!-- Ï\x84 -->  </mi>  </mrow>  </msub>  </mrow>  </msubsup>  <msub>  <mi> &#x03A8; <!-- Î¨ -->  </mi>  <mrow>  <mi> &#x03C4; <!-- Ï\x84 -->  </mi>  </mrow>  </msub>  </math> \n',
    mml2: '<math> <msubsup> <mi> &#x03C6; <!-- Ï\x86 --> </mi> <mrow> <mi> J </mi> <mi> &#x03C4; <!-- Ï\x84 --> </mi> <msub> <mi> M </mi> <mi> &#x03C4; <!-- Ï\x84 --> </mi> </msub> </mrow> <mrow> <mo> ( </mo> <mi> g </mi> <mo> ) </mo> </mrow> </msubsup> <mo> = </mo> <msubsup> <mi> N </mi> <mrow> <msub> <mi> J </mi> <mi> r </mi> </msub> </mrow> <mrow> <mo> ( </mo> <mi> g </mi> <mo> ) </mo> </mrow> </msubsup> <msubsup> <mi> P </mi> <mrow> <msub> <mi> M </mi> <mi> r </mi> </msub> <mo> , </mo> <mn> 0 </mn> </mrow> <mrow> <mi> J </mi> <mo> , </mo> </mrow> </msubsup> <msub> <mi> &#x03A8; <!-- Î¨ --> </mi> <mi> &#x03C4; <!-- Ï\x84 --> </mi> </msub> </math>\n'
  },
  {
    eqn_num: 28,
    mml1: '<math>  <mi> &#x03B2; <!-- Î² -->  </mi>  <msub>  <mi> f </mi>  <mi> v </mi>  </msub>  <mo> ( </mo>  <mi> &#x03BE; <!-- Î¾ -->  </mi>  <mo> , </mo>  <mi> z </mi>  <mo> ) </mo>  <mo> + </mo>  <mi> &#x03B1; <!-- Î± -->  </mi>  <mrow>  <mo> ( </mo>  <munderover>  <mo> &#x2211; <!-- â\x88\x91 -->  </mo>  <mrow>  <mi> k </mi>  <mo> = </mo>  <mn> 0 </mn>  </mrow>  <mrow>  <msub>  <mi> d </mi>  <mi> u </mi>  </msub>  </mrow>  </munderover>  <msubsup>  <mi> c </mi>  <mi> k </mi>  <mo> &#x2032; </mo>  </msubsup>  <mo> ( </mo>  <mi> z </mi>  <mo> ) </mo>  <msup>  <mi> a </mi>  <mi> k </mi>  </msup>  <mo> ) </mo>  </mrow>  <msub>  <mi> f </mi>  <mi> u </mi>  </msub>  <mo> ( </mo>  <mi> &#x03BE; <!-- Î¾ -->  </mi>  <mo> , </mo>  <mi> z </mi>  <mo> ) </mo>  <mo> &#x2261; <!-- â\x89¡ -->  </mo>  <mrow>  <mo> ( </mo>  <mi> &#x03B7; <!-- Î· -->  </mi>  <mo> &#x2212; <!-- â\x88\x92 -->  </mo>  <munderover>  <mo> &#x2211; <!-- â\x88\x91 -->  </mo>  <mrow>  <mi> k </mi>  <mo> = </mo>  <mn> 0 </mn>  </mrow>  <mrow>  <msub>  <mi> d </mi>  <mi> u </mi>  </msub>  </mrow>  </munderover>  <msub>  <mi> c </mi>  <mi> k </mi>  </msub>  <mo> ( </mo>  <mi> z </mi>  <mo> ) </mo>  <msup>  <mi> a </mi>  <mi> k </mi>  </msup>  <mo> ) </mo>  </mrow>  <mi> h </mi>  <mo> ( </mo>  <mi> z </mi>  <mo> ) </mo>  </math> \n',
    mml2: '<math> <mi> &#x03B2; <!-- Î² --> </mi> <msub> <mi> f </mi> <mi> v </mi> </msub> <mo> ( </mo> <mi> &#x03BE; <!-- Î¾ --> </mi> <mo> , </mo> <mi> z </mi> <mo> ) </mo> <mo> + </mo> <mi> &#x03B1; <!-- Î± --> </mi> <mrow> <mo> ( </mo> <munderover> <mo> &#x2211; <!-- â\x88\x91 --> </mo> <mrow> <mi> k </mi> <mo> = </mo> <mn> 0 </mn> </mrow> <mrow> <msub> <mi> d </mi> <mi> u </mi> </msub> </mrow> </munderover> <msubsup> <mi> c </mi> <mi> k </mi> <mo> &#x2032; </mo> </msubsup> <mo> ( </mo> <mi> z </mi> <mo> ) </mo> <msup> <mi> a </mi> <mi> k </mi> </msup> <mo> ) </mo> </mrow> <msub> <mi> f </mi> <mi> u </mi> </msub> <mo> ( </mo> <mi> &#x03BE; <!-- Î¾ --> </mi> <mo> , </mo> <mi> z </mi> <mo> ) </mo> <mo> &#x2261; <!-- â\x89¡ --> </mo> <mrow> <mo> ( </mo> <mi> &#x03B7; <!-- Î· --> </mi> <mo>\n'
  },
  {
    eqn_num: 29,
    mml1: '<math>  <msub>  <mi> J </mi>  <mrow>  <mi> &#x03BB; <!-- Î» -->  </mi>  <mo> , </mo>  <msub>  <mi> &#x03B5; <!-- Îµ -->  </mi>  <mrow>  <mi> n </mi>  </mrow>  </msub>  </mrow>  </msub>  <mo> ( </mo>  <msubsup>  <mi> u </mi>  <mrow>  <mi> l </mi>  </mrow>  <mrow>  <mi> n </mi>  </mrow>  </msubsup>  <mo> ) </mo>   <mi>   </math> \n',
    mml2: '<math> <msub> <mi> J </mi> <mrow> <mi> &#x03BB; <!-- Î» --> </mi> <mo> , </mo> <msub> <mi> &#x03B5; <!-- Îµ --> </mi> <mi> n </mi> </msub> </mrow> </msub> <mo> ( </mo> <msubsup> <mi> u </mi> <mi> l </mi> <mi> n </mi> </msubsup> <mo> ) </mo> </math>\n'
  },
  {
    eqn_num: 30,
    mml1: '<math>  <mi> ln </mi>  <mo> &#x2061; <!-- â\x81¡ -->  </mo>  <mi> M </mi>  <mo> = </mo>  <mn> 8.59 </mn>  <mo> , </mo>  <mn> 8.89 </mn>  </math> \n',
    mml2: '<math> <mi> ln </mi> <mo> &#x2061; <!-- â\x81¡ --> </mo> <mi> M </mi> <mo> = </mo> <mn> <unk> </mn> <mo> , </mo> <mn> <unk> </mn> </math>\n'
  },
  {
    eqn_num: 31,
    mml1: '<math>  <msub>  <mi> S </mi>  <mrow>  <mi> W </mi>  <mi> Z </mi>  <mi> W </mi>  </mrow>  </msub>  <mo> ( </mo>  <mi> &#x03C6; <!-- Ï\x86 -->  </mi>  <mo> ) </mo>  <mo> = </mo>   <mstyle>   <mrow>  <mfrac>  <mn> 1 </mn>  <mrow>  <mn> 16 </mn>  <msup>   <mstyle>   <mrow>  <msub>  <mi> p </mi>  <mi> i </mi>  </msub>  </mrow>  </mstyle>  <mn> 2 </mn>  </msup>  </mrow>  </mfrac>  </mrow>  <msub>  <mo> &#x222B; <!-- â\x88« -->  </mo>  <mi> D </mi>  </msub>  <mi> big </mi>  <mo> &#x2061; <!-- â\x81¡ -->  </mo>  <mo> [ </mo>   <mo>  &#x27E8; <!-- â\x9f¨ -->  </mo>  <mi> &#x0394; <!-- Î\x94 -->  </mi>  <mi> &#x03C6; <!-- Ï\x86 -->  </mi>  <mo> , </mo>  <mi> &#x0394; <!-- Î\x94 -->  </mi>  <mi> &#x03C6; <!-- Ï\x86 -->  </mi>   <mo>  &#x27E9; <!-- â\x9f© -->  </mo>  <mo> + </mo>  <mn> 16 </mn>  <msup>   <mstyle>   <mrow>  <msub>  <mi> p </mi>  <mi> i </mi>  </msub>  </mrow>  </mstyle>  <mn> 2 </mn>  </msup>  <mi> &#x03BC; <!-- Î¼ -->  </mi>  <msup>  <mi> e </mi>  <mrow>  <mi> &#x03B3; <!-- Î³ -->  </mi>  <mi> &#x03C6; <!-- Ï\x86 -->  </mi>  </mrow>  </msup>  <mi> big </mi>  <mo> ] </mo>   <mstyle>   <mi> &#x03BB; <!-- Î» -->  </mi>  <mo> ( </mo>  <mrow>  <mi> d </mi>  </mrow>  <mi> x </mi>  <mo> ) </mo>  </mstyle>  </math> \n',
    mml2: '<math> <msub> <mi> S </mi> <mrow> <mi> W </mi> <mi> Z </mi> <mi> W </mi> </mrow> </msub> <mo> ( </mo> <mi> &#x03C6; <!-- Ï\x86 --> </mi> <mo> ) </mo> <mo> = </mo> <mstyle> <mrow> <mfrac> <mn> 1 </mn> <mrow> <mn> 16 </mn> <msup> <mstyle> <mrow> <msub> <mi> p </mi> <mi> i </mi> </msub> </mrow> </mstyle> <mn> 2 </mn> </msup> </mrow> </mfrac> </mrow> <msub> <mo> &#x222B; <!-- â\x88« --> </mo> <mi> D </mi> </msub> <mrow> <mo> [ </mo> <mo> &#x27E8; <!-- â\x9f¨ --> </mo> <mi> &#x0394; <!-- Î\x94 --> </mi> <mi> &#x03C6; <!-- Ï\x86 --> </mi> <mo> , </mo> <mi> &#x0394; <!-- Î\x94 --> </mi> <mi> &#x03C6; <!-- Ï\x86 --> </mi> <mo> &#x27E9; <!-- â\x9f© --> </mo> <mo> + </mo> <mn> 16 </mn> <msup> <mstyle> <mrow> <msub> <mi> p </mi> <mi> i </mi> </msub> </mrow> </mstyle> <mn> 2 </mn> </msup> <mi> &#x03BC; <!-- Î¼ --> </mi> <msup> <mi> e </mi> <mrow>\n'
  },
  {
    eqn_num: 32,
    mml1: '<math>  <mo> ( </mo>  <mn> 3 </mn>  <mo> ) </mo>   <mo>    <mo>    <mo>    <mo>   </math> \n',
    mml2: '<math> <mo> ( </mo> <mn> 3 </mn> <mo> ) </mo> </math>\n'
  },
  {
    eqn_num: 33,
    mml1: '<math>  <msub>  <mi> &#x03B1; <!-- Î± -->  </mi>  <mi> m </mi>  </msub>  <mo> ( </mo>  <mi> u </mi>  <mo> , </mo>  <mi> &#x03BC; <!-- Î¼ -->  </mi>  <mo> ) </mo>  <mo> = </mo>  <msup>  <mi> u </mi>  <mi> i </mi>  </msup>   <mstyle>   <mrow>  <mfrac>  <mi> &#x2202; <!-- â\x88\x82 -->  </mi>  <mrow>  <mi> &#x2202; <!-- â\x88\x82 -->  </mi>  <msup>  <mi> x </mi>  <mi> i </mi>  </msup>  </mrow>  </mfrac>  </mrow>  <mo> + </mo>  <msup>  <mi> &#x03BC; <!-- Î¼ -->  </mi>  <mi> j </mi>  </msup>   <mstyle>   <mrow>  <mfrac>  <mi> &#x2202; <!-- â\x88\x82 -->  </mi>  <mrow>  <mi> &#x2202; <!-- â\x88\x82 -->  </mi>  <msup>  <mi> &#x03C8; <!-- Ï\x88 -->  </mi>  <mi> j </mi>  </msup>  </mrow>  </mfrac>  </mrow>  <mo> , </mo>   <mstyle>   <msubsup>  <mi> &#x03B1; <!-- Î± -->  </mi>  <mi> m </mi>  <mo> &#x2217; <!-- â\x88\x97 -->  </mo>  </msubsup>  <mo> ( </mo>  <mi> p </mi>  <mo> , </mo>  <mi> y </mi>  <mo> , </mo>  <mi> &#x03B6; <!-- Î¶ -->  </mi>  <mo> ) </mo>  <mo> = </mo>  <msub>  <mi> y </mi>  <mi> i </mi>  </msub>  <mi> d </mi>  <msup>  <mi> u </mi>  <mi> i </mi>  </msup>  <mo> + </mo>  <msub>  <mi> &#x03B6; <!-- Î¶ -->  </mi>  <mi> j </mi>  </msub>  <mi> d </mi>  <msup>  <mi> &#x03BC; <!-- Î¼ -->  </mi>  <mi> j </mi>  </msup>  </mstyle>  </mstyle>  </math> \n',
    mml2: '<math> <msub> <mi> &#x03B1; <!-- Î± --> </mi> <mi> m </mi> </msub> <mo> ( </mo> <mi> u </mi> <mo> , </mo> <mi> &#x03BC; <!-- Î¼ --> </mi> <mo> ) </mo> <mo> = </mo> <msup> <mi> u </mi> <mi> i </mi> </msup> <mstyle> <mrow> <mfrac> <mi> &#x2202; <!-- â\x88\x82 --> </mi> <mrow> <mi> &#x2202; <!-- â\x88\x82 --> </mi> <msup> <mi> x </mi> <mi> i </mi> </msup> </mrow> </mfrac> </mrow> <mo> + </mo> <msup> <mi> &#x03BC; <!-- Î¼ --> </mi> <mi> j </mi> </msup> <mstyle> <mrow> <mfrac> <mi> &#x2202; <!-- â\x88\x82 --> </mi> <mrow> <mi> &#x2202; <!-- â\x88\x82 --> </mi> <msup> <mi> &#x03C8; <!-- Ï\x88 --> </mi> <mi> j </mi> </msup> </mrow> </mfrac> </mrow> <mo> , </mo> <mstyle> <msubsup> <mi> &#x03B1; <!-- Î± --> </mi> <mi> m </mi> <mo> &#x2217; <!-- â\x88\x97 --> </mo> </msubsup> <mo> ( </mo> <mi> p </mi> <mo> , </mo> <mi> y </mi> <mo> , </mo> <mi> &#x03B6;\n'
  },
  {
    eqn_num: 34,
    mml1: '<math>  <mtext> &#xA0; </mtext>  <mi> Re </mi>  <mo> &#x2061; <!-- â\x81¡ -->  </mo>  <msup>  <mi> Z </mi>  <mrow>  <mo> ( </mo>  <mn> 2 </mn>  <mo> ) </mo>  </mrow>  </msup>  <mo> = </mo>  <mn> 0 </mn>  </math> \n',
    mml2: '<math> <mrow> <mi> R </mi> <mi> e </mi> </mrow> <mstyle> <msup> <mi> Z </mi> <mrow> <mo> ( </mo> <mn> 2 </mn> <mo> ) </mo> </mrow> </msup> <mo> = </mo> <mn> 0 </mn> </math>\n'
  },
  {
    eqn_num: 35,
    mml1: '<math>  <mo> ( </mo>  <msub>  <mi> v </mi>  <mrow>  <mover>  <mi> t </mi>  <mo> &#x00AF; <!-- Â¯ -->  </mo>  </mover>  </mrow>  </msub>  <mo> , </mo>  <mi> &#x03C6; <!-- Ï\x86 -->  </mi>  <mo> ( </mo>  <mover>  <mi> t </mi>  <mo> &#x00AF; <!-- Â¯ -->  </mo>  </mover>  <mo> ) </mo>  <mo> ) </mo>  <mo> = </mo>  <mo> ( </mo>  <mi> &#x03C6; <!-- Ï\x86 -->  </mi>  <mo> ( </mo>  <msub>  <mi> a </mi>  <mn> 1 </mn>  </msub>  <mo> ) </mo>  <mo> , </mo>  <mi> &#x03C6; <!-- Ï\x86 -->  </mi>  <mo> ( </mo>  <mover>  <mi> t </mi>  <mo> &#x00AF; <!-- Â¯ -->  </mo>  </mover>  <mo> ) </mo>  <mo> ) </mo>  </math> \n',
    mml2: '<math> <mo> ( </mo> <msub> <mi> v </mi> <mi> t </mi> </msub> <mo> , </mo> <mi> &#x03C6; <!-- Ï\x86 --> </mi> <mo> ( </mo> <mi> t </mi> <mo> ) </mo> <mo> ) </mo> <mo> = </mo> <mo> ( </mo> <mi> &#x03C6; <!-- Ï\x86 --> </mi> <mo> ( </mo> <msub> <mi> a </mi> <mn> 1 </mn> </msub> <mo> ) </mo> <mo> , </mo> <mi> &#x03C6; <!-- Ï\x86 --> </mi> <mo> ( </mo> <mi> t </mi> <mo> ) </mo> <mo> ) </mo> </math>\n'
  },
  {
    eqn_num: 36,
    mml1: '<math>  <msubsup>  <mi> K </mi>  <mi> e </mi>  <mi> n </mi>  </msubsup>  <mo> = </mo>  <msub>  <mi> K </mi>  <mrow>  <mi> e </mi>  </mrow>  </msub>  <mo> ( </mo>  <msub>  <mi> t </mi>  <mrow>  <mi> n </mi>  </mrow>  </msub>  <mo> ) </mo>  </math> \n',
    mml2: '<math> <msubsup> <mi> K </mi> <mi> e </mi> <mi> n </mi> </msubsup> <mo> = </mo> <msub> <mi> K </mi> <mi> e </mi> </msub> <mo> ( </mo> <msub> <mi> t </mi> <mi> n </mi> </msub> <mo> ) </mo> </math>\n'
  },
  {
    eqn_num: 37,
    mml1: '<math>  <munder>  <mo> &#x2211; <!-- â\x88\x91 -->  </mo>  <mrow>  <mi> &#x03C4; <!-- Ï\x84 -->  </mi>  <mrow>  <mi> i </mi>  <mi> n </mi>  </mrow>  <mo> [ </mo>  <mn> 0 </mn>  <mo> , </mo>  <mi> T </mi>  <mo> ) </mo>  </mrow>  </munder>  <munder>  <mo> &#x2211; <!-- â\x88\x91 -->  </mo>  <mrow>  <mi> m </mi>  <mrow>  <mi> i </mi>  <mi> n </mi>  </mrow>  <mrow>  <mi> M </mi>  </mrow>  </mrow>  </munder>  <munder>  <mo> &#x2211; <!-- â\x88\x91 -->  </mo>  <mrow>  <mi> i </mi>  <mrow>  <mi> i </mi>  <mi> n </mi>  </mrow>  <mrow>  <mi> E </mi>  </mrow>  </mrow>  </munder>  <mi> V </mi>  <mrow>   <mi>  E </mi>  </mrow>  <mo> ( </mo>  <mi> U </mi>  <mo> ( </mo>  <msub>  <mi> &#x03B7; <!-- Î· -->  </mi>  <mrow>  <mi> m </mi>  <mi> i </mi>  </mrow>  </msub>  <mo> ( </mo>  <mi> n </mi>  <mi> T </mi>  <mo> + </mo>  <mi> &#x03C4; <!-- Ï\x84 -->  </mi>  <mo> ) </mo>  <mo> &#x22C5; <!-- â\x8b\x85 -->  </mo>  <msub>  <mi> s </mi>  <mi> m </mi>  </msub>  <mo> ) </mo>  <mo> &#x2212; <!-- â\x88\x92 -->  </mo>  <mi> &#x03B2; <!-- Î² -->  </mi>  <msub>  <mi> d </mi>  <mrow>  <mi> m </mi>  <mi> i </mi>  </mrow>  </msub>  <mo> ( </mo>  <mi> n </mi>  <mi> T </mi>  <mo> + </mo>  <mi> &#x03C4; <!-- Ï\x84 -->  </mi>  <mo> ) </mo>  <msub>  <mi> s </mi>  <mi> m </mi>  </msub>  <mo> ) </mo>   <mi>   </math> \n',
    mml2: '<math> <munder> <mo> &#x2211; <!-- â\x88\x91 --> </mo> <mrow> <mi> &#x03C4; <!-- Ï\x84 --> </mi> <mrow> <mi> i </mi> <mi> n </mi> </mrow> <mo> [ </mo> <mn> 0 </mn> <mo> , </mo> <mi> T </mi> <mo> ) </mo> </mrow> </munder> <munder> <mo> &#x2211; <!-- â\x88\x91 --> </mo> <mrow> <mi> m </mi> <mrow> <mi> i </mi> <mi> n </mi> </mrow> <mrow> <mi> M </mi> </mrow> </mrow> </munder> <munder> <mo> &#x2211; <!-- â\x88\x91 --> </mo> <mrow> <mi> i </mi> <mrow> <mi> i </mi> <mi> n </mi> </mrow> <mrow> <mi> E </mi> </mrow> </mrow> </munder> <mi> V </mi> <mrow> <mi> E </mi> </mrow> <mo> ( </mo> <mi> U </mi> <mo> ( </mo> <msub> <mi> &#x03B7; <!-- Î· --> </mi> <mrow> <mi> m </mi> <mi> i </mi> </mrow> </msub> <mo> ( </mo> <mi> n </mi> <mi> T </mi> <mo> + </mo> <mi> &#x03C4; <!-- Ï\x84 --> </mi> <mo> ) </mo> <mo> &#x22C5; <!-- â\x8b\n'
  },
  {
    eqn_num: 38,
    mml1: '<math>  <mi> x </mi>  <mo> = </mo>  <mo> ( </mo>  <msub>  <mi> x </mi>  <mn> 1 </mn>  </msub>  <mo> , </mo>  <mo> , </mo>  <mo> &#x2026; <!-- â\x80¦ -->  </mo>  <mo> , </mo>  <mo> , </mo>  <msub>  <mi> x </mi>  <mrow>  <mi> j </mi>  </mrow>  </msub>  <mo> ) </mo>  <mrow>  <mi> i </mi>  <mi> n </mi>  </mrow>  <msub>  <mi> V </mi>  <mrow>  <mi> j </mi>  </mrow>  </msub>  <mo> , </mo>   <mi>   <mi> y </mi>  <mo> = </mo>  <mo> ( </mo>  <msub>  <mi> y </mi>  <mn> 1 </mn>  </msub>  <mo> , </mo>  <mo> , </mo>  <mo> &#x2026; <!-- â\x80¦ -->  </mo>  <mo> , </mo>  <mo> , </mo>  <msub>  <mi> y </mi>  <mrow>  <mi> k </mi>  </mrow>  </msub>  <mo> ) </mo>  <mrow>  <mi> i </mi>  <mi> n </mi>  </mrow>  <msub>  <mi> V </mi>  <mrow>  <mi> k </mi>  </mrow>  </msub>  </math> \n',
    mml2: '<math> <mi> x </mi> <mo> = </mo> <mo> ( </mo> <msub> <mi> x </mi> <mn> 1 </mn> </msub> <mo> , </mo> <mo> &#x2026; <!-- â\x80¦ --> </mo> <mo> , </mo> <msub> <mi> x </mi> <mi> j </mi> </msub> <mo> ) </mo> <mrow> <mi> i </mi> <mi> n </mi> </mrow> <msub> <mi> V </mi> <mi> j </mi> </msub> <mo> , </mo> <mo> <mi> y </mi> <mo> = </mo> <mo> ( </mo> <msub> <mi> y </mi> <mn> 1 </mn> </msub> <mo> , </mo> <mo> &#x2026; <!-- â\x80¦ --> </mo> <mo> , </mo> <msub> <mi> y </mi> <mi> k </mi> </msub> <mo> ) </mo> <mrow> <mi> i </mi> <mi> n </mi> </mrow> <msub> <mi> V </mi> <mi> k </mi> </msub> </math>\n'
  },
  {
    eqn_num: 39,
    mml1: '<math>  <msub>  <mi> w </mi>  <mrow>  <mi> i </mi>  <mi> j </mi>  </mrow>  </msub>  <mo> = </mo>  <mn> 1 </mn>  <mo> &#x2212; <!-- â\x88\x92 -->  </mo>  <mrow>  <mo> &#x27E8; </mo>  <msub>  <mi>  </mi>  <mo> , </mo>  </msub>  <mstyle scriptlevel="1">   <mn>   <mtr>  <mtd>  <mi> r </mi>  <mrow>  <mi> i </mi>  <mi> n </mi>  </mrow>  <mi> D </mi>  <mi> B </mi>  </mtd>  </mtr>  <mtr>  <mtd>  <mi> r </mi>  <mo> = </mo>  <mi> v </mi>  <mo> : </mo>  <msub>  <mi> n </mi>  <mi> i </mi>  </msub>  <mo> &#x2192; <!-- â\x86\x92 -->  </mo>  <msub>  <mi> n </mi>  <mi> j </mi>  </msub>  </mtd>  </mtr>   <mn>   </mstyle>  <mo> &#x27E9; </mo>  </mrow>  <mo> ( </mo>  <mn> 1 </mn>  <mo> &#x2212; <!-- â\x88\x92 -->  </mo>  <msubsup>  <mi> p </mi>  <mrow>  <mi> i </mi>  <mi> j </mi>  </mrow>  <mrow>  <mo> ( </mo>  <mi> v </mi>  <mo> ) </mo>  </mrow>  </msubsup>  <mo> ) </mo>  </math> \n',
    mml2: '<math> <msub> <mi> w </mi> <mrow> <mi> i </mi> <mi> j </mi> </mrow> </msub> <mo> = </mo> <mn> 1 </mn> <mo> &#x2212; <!-- â\x88\x92 --> </mo> <mrow> <mo> &#x27E8; </mo> <msub> <mi> </mi> <mo> , </mo> </msub> <mi> r </mi> <mo> = </mo> <mi> v </mi> <mo> &#x27E9; </mo> </mrow> <mrow> <mo> &#x27E8; </mo> <msub> <mi> </mi> <mo> , </mo> </msub> <mi> r </mi> <mo> = </mo> <mi> v </mi> <mo> &#x27E9; </mo> </mrow> <mo> ( </mo> <mn> 1 </mn> <mo> &#x2212; <!-- â\x88\x92 --> </mo> <msubsup> <mi> p </mi> <mrow> <mi> i </mi> <mi> j </mi> </mrow> <mrow> <mo> ( </mo> <mi> v </mi> <mo> ) </mo> </mrow> </msubsup> <mo> ) </mo> </math>\n'
  },
  {
    eqn_num: 40,
    mml1: '<math>  <msup>  <mrow>  <mrow>  <mover>  <mi> R </mi>  <mo> &#x007E; <!-- ~ -->  </mo>  </mover>  </mrow>  </mrow>  <mn> 2 </mn>  </msup>  <mo> ( </mo>  <munder>   <mi>  sup </mo>  <mrow>  <msub>  <mi> B </mi>  <mrow>  <mrow>  <mover>  <mi> R </mi>  <mo> &#x007E; <!-- ~ -->  </mo>  </mover>  </mrow>  </mrow>  </msub>  <mo> ( </mo>  <mn> 0 </mn>  <mo> ) </mo>  </mrow>  </munder>  <mi> u </mi>  <msup>  <mo> ) </mo>  <mrow>  <mi> &#x03B2; <!-- Î² -->  </mi>  </mrow>  </msup>  <mo> &#x00D7; <!-- Ã\x97 -->  </mo>  <msub>  <mrow>  <mi> i </mi>  <mi> n </mi>  <mi> f </mi>  </mrow>  <mrow>  <msub>  <mi> B </mi>  <mrow>  <mn> 3 </mn>  <mrow>  <mrow>  <mover>  <mi> R </mi>  <mo> &#x007E; <!-- ~ -->  </mo>  </mover>  </mrow>  </mrow>  </mrow>  </msub>  <mo> ( </mo>  <mn> 0 </mn>  <mo> ) </mo>  </mrow>  </msub>  <mi> u </mi>  <mo> &#x2A7D; <!-- â©½ -->  </mo>  <mi> c </mi>  <mo> = </mo>  <mi> c </mi>  <mo> ( </mo>  <mi> a </mi>  <mo> , </mo>  <mi> b </mi>  <mo> , </mo>  <mi> A </mi>  <mo> , </mo>  <mi> B </mi>  <mo> , </mo>  <mi> &#x03B2; <!-- Î² -->  </mi>  <mo> ) </mo>  </math> \n',
    mml2: '<math> <msup> <mrow> <mover> <mi> R </mi> <mo> &#x007E; <!-- ~ --> </mo> </mover> </mrow> <mn> 2 </mn> </msup> <mo> ( </mo> <munder> <mi> sup </mo> <mrow> <msub> <mi> B </mi> <mi> R </mi> </msub> <mo> ( </mo> <mn> 0 </mn> <mo> ) </mo> </mrow> </munder> <mi> u </mi> <msup> <mo> ) </mo> <mi> &#x03B2; <!-- Î² --> </mi> </msup> <mo> &#x00D7; <!-- Ã\x97 --> </mo> <msub> <mrow> <mi> i </mi> <mi> n </mi> <mi> f </mi> </mrow> <mrow> <msub> <mi> B </mi> <mrow> <mn> 3 </mn> <mi> R </mi> </mrow> </msub> <mo> ( </mo> <mn> 0 </mn> <mo> ) </mo> </mrow> </msub> <mi> u </mi> <mo> &#x2A7D; <!-- â©½ --> </mo> <mi> c </mi> <mo> = </mo> <mi> c </mi> <mo> ( </mo> <mi> a </mi> <mo> , </mo> <mi> b </mi> <mo> , </mo> <mi> A </mi> <mo> , </mo> <mi> B </mi> <mo> , </mo> <mi> &#x03B2;\n'
  },
  {
    eqn_num: 41,
    mml1: '<math>  <mrow>   <mi>  w </mi>  </mrow>  <mo> ( </mo>  <mi> a </mi>  <mi> &#x03B1; <!-- Î± -->  </mi>  <mo> ) </mo>  <mo> &#x22C5; <!-- â\x8b\x85 -->  </mo>  <mrow>   <mi>  w </mi>  </mrow>  <mo> ( </mo>  <mi> b </mi>  <mi> &#x03B2; <!-- Î² -->  </mi>  <mo> ) </mo>  <mo> = </mo>   <mstyle>   <mrow>  <mfrac>  <mn> 1 </mn>  <mi> d </mi>  </mfrac>  </mrow>  <mtext> &#xA0; </mtext>  <mrow>  <mi> f </mi>  <mi> o </mi>  <mi> r </mi>  </mrow>  <mtext> &#xA0; </mtext>  <mi> a </mi>  <mo> &#x2260; </mo>  <mi> b </mi>  </mstyle>  </math> \n',
    mml2: '<math> <mrow> <mi> w </mi> </mrow> <mo> ( </mo> <mi> a </mi> <mi> &#x03B1; <!-- Î± --> </mi> <mo> ) </mo> <mo> &#x22C5; <!-- â\x8b --> </mo> <mrow> <mi> w </mi> </mrow> <mo> ( </mo> <mi> b </mi> <mi> &#x03B2; <!-- Î² --> </mi> <mo> ) </mo> <mo> = </mo> <mstyle> <mrow> <mfrac> <mn> 1 </mn> <mi> d </mi> </mfrac> </mrow> <mstyle> <mtext> &#xA0;for&#xA0; </mtext> </mstyle> <mi> a </mi> <mo> &#x2260; <!-- â\x89 --> </mo> <mi> b </mi> </mstyle> </math>\n'
  },
  {
    eqn_num: 42,
    mml1: '<math>  <msubsup>  <mrow>  <mrow>  <mover>  <mi> &#x03A9; <!-- Î© -->  </mi>  <mo> &#x007E; <!-- ~ -->  </mo>  </mover>  </mrow>  </mrow>  <mrow>  <mi> P </mi>  </mrow>  <mrow>  <mn> 1 </mn>  </mrow>  </msubsup>  <mo> = </mo>  <mo> ( </mo>  <msubsup>  <mi> x </mi>  <mrow>  <mi> a </mi>  </mrow>  <mo> &#x2033; </mo>  </msubsup>  <mo> &#x2212; <!-- â\x88\x92 -->  </mo>  <msubsup>  <mi> x </mi>  <mrow>  <mi> a </mi>  </mrow>  <mo> &#x2032; </mo>  </msubsup>  <msub>  <mo> ) </mo>  <mrow>  <mi> a </mi>  </mrow>  </msub>  <mo> &#x2286; <!-- â\x8a\x86 -->  </mo>  <mi> P </mi>  <msub>  <mo> &#x2297; <!-- â\x8a\x97 -->  </mo>  <mrow>  <mi> K </mi>  </mrow>  </msub>  <mi> P </mi>  </math> \n',
    mml2: '<math> <msubsup> <mrow> <mover> <mi> &#x03A9; <!-- Î© --> </mi> <mo> &#x007E; <!-- ~ --> </mo> </mover> </mrow> <mi> P </mi> <mn> 1 </mn> </msubsup> <mo> = </mo> <mo> ( </mo> <msubsup> <mi> x </mi> <mi> a </mi> <mo> &#x2033; </mo> </msubsup> <mo> &#x2212; <!-- â\x88\x92 --> </mo> <msubsup> <mi> x </mi> <mi> a </mi> <mo> &#x2032; </mo> </msubsup> <msub> <mo> ) </mo> <mi> a </mi> </msub> <mo> &#x2286; <!-- â\x8a\x86 --> </mo> <mi> P </mi> <msub> <mo> &#x2297; <!-- â\x8a\x97 --> </mo> <mi> K </mi> </msub> <mi> P </mi> </math>\n'
  },
  {
    eqn_num: 43,
    mml1: '<math>  <mi> u </mi>  <mrow>  <mi> i </mi>  <mi> n </mi>  </mrow>  <msup>  <mi> L </mi>  <mrow>  <mi> &#x221E; <!-- â\x88\x9e -->  </mi>  </mrow>  </msup>  <mo> ( </mo>  <mo> ( </mo>  <mn> 0 </mn>  <mo> , </mo>   <mo>   <mi> T </mi>  <mo> ) </mo>  <mo> ; </mo>  <msup>  <mi> L </mi>  <mrow>  <mn> 2 </mn>  </mrow>  </msup>  <mo> ( </mo>  <mi> &#x03A9; <!-- Î© -->  </mi>  <mo> ) </mo>  <mo> ) </mo>  <mo> &#x2229; <!-- â\x88© -->  </mo>  <msup>  <mi> L </mi>  <mrow>  <mn> 2 </mn>  </mrow>  </msup>  <mo> ( </mo>  <mo> ( </mo>  <mn> 0 </mn>  <mo> , </mo>   <mo>   <mi> T </mi>  <mo> ) </mo>  <mo> ; </mo>   <mo>   <msup>  <mi> H </mi>  <mrow>  <mi> &#x03B1; <!-- Î± -->  </mi>  </mrow>  </msup>  <mo> ( </mo>  <mi> &#x03A9; <!-- Î© -->  </mi>  <mo> ) </mo>  <mo> ) </mo>  </math> \n',
    mml2: '<math> <mi> u </mi> <mrow> <mi> i </mi> <mi> n </mi> </mrow> <msup> <mi> L </mi> <mi> &#x221E; <!-- â\x88\x9e --> </mi> </msup> <mo> ( </mo> <mo> ( </mo> <mn> 0 </mn> <mo> , </mo> <mi> <mi> T </mi> <mo> ) </mo> <mo> ; </mo> <msup> <mi> L </mi> <mn> 2 </mn> </msup> <mo> ( </mo> <mi> &#x03A9; <!-- Î© --> </mi> <mo> ) </mo> <mo> ) </mo> <mo> &#x2229; <!-- â\x88© --> </mo> <msup> <mi> L </mi> <mn> 2 </mn> </msup> <mo> ( </mo> <mo> ( </mo> <mn> 0 </mn> <mo> , </mo> <mi> <mi> T </mi> <mo> ) </mo> <mo> ; </mo> <mi> <msup> <mi> H </mi> <mi> &#x03B1; <!-- Î± --> </mi> </msup> <mo> ( </mo> <mi> &#x03A9; <!-- Î© --> </mi> <mo> ) </mo> <mo> ) </mo> </math>\n'
  },
  {
    eqn_num: 44,
    mml1: '<math>  <mi> &#x03B1; <!-- Î± -->  </mi>  <mo> = </mo>  <msub>  <mi> &#x03B1; <!-- Î± -->  </mi>  <mrow>  <mo> + </mo>  </mrow>  </msub>  <mo> + </mo>  <msub>  <mi> &#x03B1; <!-- Î± -->  </mi>  <mrow>  <mo> &#x2212; <!-- â\x88\x92 -->  </mo>  </mrow>  </msub>  </math> \n',
    mml2: '<math> <mi> &#x03B1; <!-- Î± --> </mi> <mo> = </mo> <msub> <mi> &#x03B1; <!-- Î± --> </mi> <mo> + </mo> </msub> <mo> + </mo> <msub> <mi> &#x03B1; <!-- Î± --> </mi> <mo> &#x2212; <!-- â\x88\x92 --> </mo> </msub> </math>\n'
  },
  {
    eqn_num: 45,
    mml1: '<math>  <msub>  <mi> &#x039B; <!-- Î\x9b -->  </mi>  <mi> J </mi>  </msub>  <mo> = </mo>  <msup>  <mn> 10 </mn>  <mrow>  <mn> 2 </mn>  </mrow>  </msup>  </math> \n',
    mml2: '<math> <msub> <mi> &#x039B; <!-- Î\x9b --> </mi> <mi> J </mi> </msub> <mo> = </mo> <msup> <mn> 10 </mn> <mn> 2 </mn> </msup> </math>\n'
  },
  {
    eqn_num: 46,
    mml1: '<math>  <msubsup>  <mi> &#x03D6; <!-- Ï\x96 -->  </mi>  <mrow>  <mo> &#x00B1; <!-- Â± -->  </mo>  </mrow>  <mn> 2 </mn>  </msubsup>  <mo> = </mo>  <mi> ln </mi>  <mo> &#x2061; <!-- â\x81¡ -->  </mo>  <mrow>  <mo> ( </mo>   <mstyle>   <mrow>  <mfrac>  <mrow>  <msup>  <mi> e </mi>  <mrow>  <mo> &#x00B1; <!-- Â± -->  </mo>  <mi> i </mi>  <mi> &#x03C0; <!-- Ï\x80 -->  </mi>  </mrow>  </msup>   <mo>   <mn> 2 </mn>  </mrow>  <msup>  <mi> g </mi>  <mn> 2 </mn>  </msup>  </mfrac>  </mrow>  </mstyle>  <mo> ) </mo>  </mrow>  <mo> = </mo>  <msup>  <mi> &#x03D6; <!-- Ï\x96 -->  </mi>  <mn> 2 </mn>  </msup>  <mo> &#x00B1; <!-- Â± -->  </mo>  <mi> i </mi>  <mi> &#x03C0; <!-- Ï\x80 -->  </mi>  <mo> , </mo>   <mo>   <msup>  <mi> &#x03D6; <!-- Ï\x96 -->  </mi>  <mn> 2 </mn>  </msup>  <mo> = </mo>  <mi> ln </mi>  <mo> &#x2061; <!-- â\x81¡ -->  </mo>  <mrow>  <mo> ( </mo>   <mstyle>   <mrow>  <mfrac>  <mn> 2 </mn>  <msup>  <mi> g </mi>  <mn> 2 </mn>  </msup>  </mfrac>  </mrow>  </mstyle>  <mo> ) </mo>  </mrow>  </math> \n',
    mml2: '<math> <msubsup> <mi> &#x03D6; <!-- Ï\x96 --> </mi> <mo> &#x00B1; <!-- Â± --> </mo> <mn> 2 </mn> </msubsup> <mo> = </mo> <mi> ln </mi> <mo> &#x2061; <!-- â\x81¡ --> </mo> <mrow> <mo> ( </mo> <mstyle> <mrow> <mfrac> <mrow> <msup> <mi> e </mi> <mrow> <mo> &#x00B1; <!-- Â± --> </mo> <mi> i </mi> <mstyle> <mrow> <msub> <mi> p </mi> <mi> i </mi> </msub> </mrow> </mstyle> </mrow> </msup> <mstyle> <mn> 2 </mn> </mrow> <msup> <mi> g </mi> <mn> 2 </mn> </msup> </mfrac> </mrow> </mstyle> <mo> ) </mo> </mrow> <mo> = </mo> <msup> <mi> &#x03D6; <!-- Ï\x96 --> </mi> <mn> 2 </mn> </msup> <mo> &#x00B1; <!-- Â± --> </mo> <mi> i </mi> <mstyle> <mrow> <msub> <mi> p </mi> <mi> i </mi> </msub> </mrow> </mstyle> <mo> , </mo> <mstyle> <msup> <mi> &#x03D6; <!-- Ï\x96 --> </mi> <mn> 2 </mn> </msup> <mo> = </mo> <mi> ln </mi> <mo> &#x2061; <!-- â\x81¡ --> </mo> <mrow> <mo>\n'
  },
];