eqn_src = [
  {
    eqn_num: 2529,
    mml1: '<math>  <msub>  <mi> a </mi>  <mrow>  <mo> , </mo>  <mi> &#x03B7; <!-- Î· -->  </mi>  </mrow>  </msub>  <mo> = </mo>  <mi> a </mi>   <mi>   <mi> d </mi>  <mi> a </mi>  <mrow>  <mo> / </mo>  </mrow>  <mi> d </mi>  <mi> t </mi>  <mo> &#x2261; <!-- â\x89¡ -->  </mo>  <mi> a </mi>  <mrow>  <mover>  <mi> a </mi>  <mo> &#x02D9; <!-- Ë\x99 -->  </mo>  </mover>  </mrow>  </math> \n',
    mml2: '<math> <msub> <mi> a </mi> <mrow> <mo> , </mo> <mi> &#x03B7; <!-- Î· --> </mi> </mrow> </msub> <mo> = </mo> <mi> a </mi> <mstyle> <mi> d </mi> <mi> a </mi> <mrow> <mo> / </mo> </mrow> <mi> d </mi> <mi> t </mi> <mo> &#x2261; <!-- â\x89¡ --> </mo> <mi> a </mi> <mrow> <mover> <mi> a </mi> <mo> &#x02D9; <!-- Ë\x99 --> </mo> </mover> </mrow> </math>\n'
  },
  {
    eqn_num: 1622,
    mml1: '<math>  <mo> &lt; </mo>  <msub>  <mi> I </mi>  <mrow>  <mi> &#x03BB; <!-- Î» -->  </mi>  <mo> , </mo>  <mrow>  <mi> e </mi>  <mi> s </mi>  <mi> c </mi>  </mrow>  </mrow>  </msub>  <mo> &gt;= </mo>   <mstyle>   <mrow>  <mfrac>  <mrow>  <mo> &#x2211; <!-- â\x88\x91 -->  </mo>  <msub>  <mi> I </mi>  <mrow>  <mi> &#x03BB; <!-- Î» -->  </mi>  <mo> , </mo>  <mi> e </mi>  <mi> s </mi>  <mi> c </mi>  <mo> , </mo>  <mi> i </mi>  </mrow>  </msub>  <msub>  <mi> &#x03A9; <!-- Î© -->  </mi>  <mrow>  <mi> H </mi>  <mi> P </mi>  <mo> , </mo>  <mi> E </mi>  <mi> M </mi>  <mo> , </mo>  <mi> i </mi>  </mrow>  </msub>  </mrow>  <msub>  <mi> &#x03A9; <!-- Î© -->  </mi>  <mrow>  <mrow>  <mi> H </mi>  <mi> P </mi>  <mo> , </mo>  <mi> M </mi>  <mi> S </mi>  </mrow>  </mrow>  </msub>  </mfrac>  </mrow>  </mstyle>  </math> \n',
    mml2: '<math> <mo> &lt; </mo> <msub> <mi> I </mi> <mrow> <mi> &#x03BB; <!-- Î» --> </mi> <mo> , </mo> <mrow> <mi> e </mi> <mi> s </mi> <mi> c </mi> </mrow> </mrow> </msub> <mo> &gt;= </mo> <mstyle> <mrow> <mfrac> <mrow> <mo> &#x2211; <!-- â\x88\x91 --> </mo> <msub> <mi> I </mi> <mrow> <mi> &#x03BB; <!-- Î» --> </mi> <mo> , </mo> <mi> e </mi> <mi> s </mi> <mi> s </mi> <mi> i </mi> </mrow> </msub> <msub> <mi> &#x03A9; <!-- Î© --> </mi> <mrow> <mi> H </mi> <mi> P </mi> <mo> , </mo> <mi> E </mi> <mi> M </mi> <mo> , </mo> <mi> i </mi> </mrow> </msub> </mrow> <msub> <mi> &#x03A9; <!-- Î© --> </mi> <mrow> <mi> H </mi> <mi> P </mi> <mo> , </mo> <mi> M </mi> <mi> S </mi> </mrow> </msub> </mfrac> </mrow> </mstyle> </math>\n'
  },
  {
    eqn_num: 1863,
    mml1: '<math>  <mi> V </mi>  <mi> m </mi>  <mi> a </mi>  <mi> x </mi>  <mo> = </mo>  <mn> 78 </mn>   <mo>   </math> \n',
    mml2: '<math> <mi> V </mi> <mi> m </mi> <mi> a </mi> <mi> x </mi> <mo> = </mo> <mn> 78 </mn> </math>\n'
  },
  {
    eqn_num: 3326,
    mml1: '<math>  <msub>  <mrow>  <mi> H </mi>  </mrow>  <mn> 0 </mn>  </msub>  <mo> ( </mo>  <msup>  <mi> k </mi>  <mo> + </mo>  </msup>  <mo> ) </mo>  <mo> = </mo>  <mn> 2 </mn>   <mstyle>   <mrow>  <msub>  <mi> p </mi>  <mi> i </mi>  </msub>  </mrow>  </mstyle>   <mstyle>   <msubsup>  <mo> &#x222B; <!-- â\x88« -->  </mo>  <mrow>  <mo> &#x2212; <!-- â\x88\x92 -->  </mo>  <mi> &#x221E; <!-- â\x88\x9e -->  </mi>  </mrow>  <mn> 0 </mn>  </msubsup>   <mstyle>   <mi> &#x03F1; <!-- Ï± -->  </mi>   <mstyle>   </math> \n',
    mml2: '<math> <msub> <mrow> <mi> H </mi> </mrow> <mn> 0 </mn> </msub> <mo> ( </mo> <msup> <mi> k </mi> <mo> + </mo> </msup> <mo> ) </mo> <mo> = </mo> <mn> 2 </mn> <mstyle> <mrow> <msub> <mi> p </mi> <mi> i </mi> </msub> </mrow> </mstyle> <msubsup> <mo> &#x222B; <!-- â\x88« --> </mo> <mrow> <mo> &#x2212; <!-- â\x88\x92 --> </mo> <mi> &#x221E; <!-- â\x88\x9e --> </mi> </mrow> <mn> 0 </mn> </msubsup> <mi> &#x03F1; <!-- Ï± --> </mi> </math>\n'
  },
  {
    eqn_num: 3934,
    mml1: '<math>  <mo> &#x222B; <!-- â\x88« -->  </mo>  <msub>  <mi> f </mi>  <mi> S </mi>  </msub>  <mo> ( </mo>  <mi> x </mi>  <mo> ) </mo>  <mi> d </mi>  <mrow>  <mover>  <mi> &#x03BB; <!-- Î» -->  </mi>  <mo> &#x007E; <!-- ~ -->  </mo>  </mover>  </mrow>  <mo> ( </mo>  <mi> x </mi>  <mo> ) </mo>  <mo> &#x2A7D; <!-- â©½ -->  </mo>  <msub>  <mi> &#x03B1; <!-- Î± -->  </mi>  <mrow>  <mi> &#x03BB; <!-- Î» -->  </mi>  </mrow>  </msub>  <mo> ( </mo>  <mi> G </mi>  <mo> ) </mo>  <mi> &#x03B4; <!-- Î´ -->  </mi>  <mo> ( </mo>  <mi> S </mi>  <mo> ) </mo>  </math> \n',
    mml2: '<math> <mo> &#x222B; <!-- â\x88« --> </mo> <msub> <mi> f </mi> <mi> S </mi> </msub> <mo> ( </mo> <mi> x </mi> <mo> ) </mo> <mi> d </mi> <mrow> <mover> <mi> &#x03BB; <!-- Î» --> </mi> <mo> &#x007E; <!-- ~ --> </mo> </mover> </mrow> <mo> ( </mo> <mi> x </mi> <mo> ) </mo> <mo> &#x2A7D; <!-- â©½ --> </mo> <msub> <mi> &#x03B1; <!-- Î± --> </mi> <mi> &#x03BB; <!-- Î» --> </mi> </msub> <mo> ( </mo> <mi> G </mi> <mo> ) </mo> <mi> &#x03B4; <!-- Î´ --> </mi> <mo> ( </mo> <mi> S </mi> <mo> ) </mo> </math>\n'
  },
  {
    eqn_num: 3410,
    mml1: '<math>  <msubsup>  <mi> &#x03C8; <!-- Ï\x88 -->  </mi>  <mrow>  <mn> 0 </mn>  </mrow>  <mo> &#x2032; </mo>  </msubsup>  <mo> ( </mo>  <msup>  <mi> x </mi>  <mo> &#x2032; </mo>  </msup>  <mo> , </mo>  <msup>  <mi> &#x03BE; <!-- Î¾ -->  </mi>  <mo> &#x2032; </mo>  </msup>  <mo> , </mo>  <mi> t </mi>  <mo> ) </mo>  <mo> := </mo>  <msub>  <mi> &#x03C6; <!-- Ï\x86 -->  </mi>  <mn> 1 </mn>  </msub>  <mo> ( </mo>  <msup>  <mi> x </mi>  <mo> &#x2032; </mo>  </msup>  <mo> , </mo>  <msup>  <mi> &#x03BE; <!-- Î¾ -->  </mi>  <mo> &#x2032; </mo>  </msup>  <mo> , </mo>  <mi> t </mi>  <mo> ) </mo>  <mo> ; </mo>  </math> \n',
    mml2: '<math> <msubsup> <mi> &#x03C8; <!-- Ï\x88 --> </mi> <mn> 0 </mn> <mo> &#x2032; </mo> </msubsup> <mo> ( </mo> <msup> <mi> x </mi> <mo> &#x2032; </mo> </msup> <mo> , </mo> <msup> <mi> &#x03BE; <!-- Î¾ --> </mi> <mo> &#x2032; </mo> </msup> <mo> , </mo> <mi> t </mi> <mo> ) </mo> <mo> := </mo> <msub> <mi> &#x03C6; <!-- Ï\x86 --> </mi> <mn> 1 </mn> </msub> <mo> ( </mo> <msup> <mi> x </mi> <mo> &#x2032; </mo> </msup> <mo> , </mo> <msup> <mi> &#x03BE; <!-- Î¾ --> </mi> <mo> &#x2032; </mo> </msup> <mo> , </mo> <mi> t </mi> <mo> ) </mo> <mo> ; </mo> </math>\n'
  },
  {
    eqn_num: 2873,
    mml1: '<math>  <mi> A </mi>  <mo> ( </mo>  <mi> T </mi>  <mo> ) </mo>  <mo> &#x221D; <!-- â\x88\x9d -->  </mo>   <mstyle>   <mrow>  <mfrac>  <mrow>  <msub>  <mi> &#x03B5; <!-- Îµ -->  </mi>  <mi> I </mi>  </msub>  <mrow>  <mo> / </mo>  </mrow>  <mo> ( </mo>  <mi> &#x0394; <!-- Î\x94 -->  </mi>  <mo> ( </mo>  <mi> T </mi>  <mo> ) </mo>  <mo> + </mo>  <msub>  <mi> &#x03F0; <!-- Ï° -->  </mi>  <mi> B </mi>  </msub>  <mi> T </mi>  <mrow>  <mo> / </mo>  </mrow>  <mn> 2 </mn>  <mo> ) </mo>  </mrow>  <mrow>  <mn> 1 </mn>  <mo> + </mo>  <mi> &#x03B3; <!-- Î³ -->  </mi>  <msqrt>   <mstyle>   <mrow>  <mfrac>  <mrow>  <mn> 2 </mn>  <msub>  <mi> &#x03F0; <!-- Ï° -->  </mi>  <mi> B </mi>  </msub>  <mi> T </mi>  </mrow>  <mrow>   <mstyle>   <mrow>  <msub>  <mi> p </mi>  <mi> i </mi>  </msub>  </mrow>  </mstyle>  <mi> &#x0394; <!-- Î\x94 -->  </mi>  <mo> ( </mo>  <mi> T </mi>  <mo> ) </mo>  </mrow>  </mfrac>  </mrow>  </mstyle>  </msqrt>  <mi> e </mi>  <mi> x </mi>  <mi> p </mi>  <mo> ( </mo>  <mo> &#x2212; <!-- â\x88\x92 -->  </mo>  <mi> &#x0394; <!-- Î\x94 -->  </mi>  <mo> ( </mo>  <mi> T </mi>  <mo> ) </mo>  <mrow>  <mo> / </mo>  </mrow>  <msub>  <mi> &#x03F0; <!-- Ï° -->  </mi>  <mi> B </mi>  </msub>  <mi> T </mi>  <mo> ) </mo>  </mrow>  </mfrac>  </mrow>  </mstyle>  </math> \n',
    mml2: '<math> <mi> A </mi> <mo> ( </mo> <mi> T </mi> <mo> ) </mo> <mo> &#x221D; <!-- â\x88\x9d --> </mo> <mstyle> <mrow> <mfrac> <mrow> <msub> <mi> &#x03B5; <!-- Îµ --> </mi> <mi> I </mi> </msub> <mrow> <mo> / </mo> </mrow> <mo> ( </mo> <mi> &#x0394; <!-- Î\x94 --> </mi> <mo> ( </mo> <mi> T </mi> <mo> ) </mo> <mo> + </mo> <msub> <mi> &#x03F0; <!-- Ï° --> </mi> <mi> B </mi> </msub> <mi> T </mi> <mrow> <mo> / </mo> </mrow> <mn> 2 </mn> <mo> ) </mo> </mrow> <mrow> <mstyle> <mrow> <msub> <mi> p </mi> <mi> i </mi> </msub> </mrow> </mstyle> <mi> &#x0394; <!-- Î\x94 --> </mi> <mo> ( </mo> <mi> f </mi> <mo> ) </mo> </mrow> </mfrac> </mrow> <mi> e </mi> <mi> x </mi> <mi> p </mi> <mo> ( </mo> <mo> &#x2212; <!-- â\x88\x92 --> </mo> <mi> &#x0394; <!-- Î\x94 --> </mi> <mo> ( </mo> <mi> T </mi> <mo> ) </mo>\n'
  },
  {
    eqn_num: 3098,
    mml1: '<math>  <msup>  <mrow>  <mi> E </mi>  </mrow>  <mrow>  <mi> &#x03B2; <!-- Î² -->  </mi>  </mrow>  </msup>  <mo> := </mo>  <msup>  <mi> C </mi>  <mrow>  <mi> &#x03B2; <!-- Î² -->  </mi>  <mo> , </mo>  <mn> 0 </mn>  </mrow>  </msup>  <mo> ( </mo>  <mo> [ </mo>  <mn> 0 </mn>  <mo> , </mo>  <mi> T </mi>  <mo> ] </mo>  <mo> &#x00D7; <!-- Ã\x97 -->  </mo>  <mi> K </mi>  <mo> ; </mo>  <msup>  <mrow>   <mi>  R </mi>  </mrow>  <mi> d </mi>  </msup>  <mo> ) </mo>  </math> \n',
    mml2: '<math> <msup> <mrow> <mi> E </mi> </mrow> <mrow> <mi> &#x03B2; <!-- Î² --> </mi> </mrow> </msup> <mo> := </mo> <msup> <mi> C </mi> <mrow> <mi> &#x03B2; <!-- Î² --> </mi> <mo> , </mo> <mn> 0 </mn> </mrow> </msup> <mo> ( </mo> <mo> [ </mo> <mn> 0 </mn> <mo> , </mo> <mi> T </mi> <mo> ] </mo> <mo> &#x00D7; <!-- Ã\x97 --> </mo> <mi> K </mi> <mo> ; </mo> <msup> <mrow> <mi> R </mi> </mrow> <mrow> <mi> d </mi> </mrow> </msup> <mo> ) </mo> </math>\n'
  },
  {
    eqn_num: 1835,
    mml1: '<math>  <mi> w </mi>  <mrow>  <mi> i </mi>  <mi> n </mi>  </mrow>  <mi> &#x039B; <!-- Î\x9b -->  </mi>  <mi> &#x03A6; <!-- Î¦ -->  </mi>  <mo> ( </mo>  <msub>  <mi> x </mi>  <mi> n </mi>  </msub>  <mo> ) </mo>  <msub>  <mi> g </mi>  <mrow>  <msub>  <mi> t </mi>  <mi> n </mi>  </msub>  </mrow>  </msub>  <msub>  <mi> &#x03A6; <!-- Î¦ -->  </mi>  <mrow>  <mi> n </mi>  </mrow>  </msub>  <mo> ( </mo>  <mi> x </mi>  <mo> ) </mo>  </math> \n',
    mml2: '<math> <mi> w </mi> <mrow> <mi> i </mi> <mi> n </mi> </mrow> <mi> &#x039B; <!-- Î\x9b --> </mi> <mi> &#x03A6; <!-- Î¦ --> </mi> <mo> ( </mo> <msub> <mi> x </mi> <mi> n </mi> </msub> <mo> ) </mo> <msub> <mi> g </mi> <mrow> <msub> <mi> t </mi> <mi> n </mi> </msub> </mrow> </msub> <msub> <mi> &#x03A6; <!-- Î¦ --> </mi> <mi> n </mi> </msub> <mo> ( </mo> <mi> x </mi> <mo> ) </mo> </math>\n'
  },
  {
    eqn_num: 3899,
    mml1: '<math>  <msub>  <mi> V </mi>  <mi> &#x03BB; <!-- Î» -->  </mi>  </msub>  <mo> = </mo>  <munder>  <mo> &#x2A01; <!-- â¨\x81 -->  </mo>  <mrow>  <mi> w </mi>  <mrow>  <mi> i </mi>  <mi> n </mi>  </mrow>  <mi> F </mi>  </mrow>  </munder>  <mrow>  <msub>  <mi> W </mi>  <mi> w </mi>  </msub>  </mrow>  </math> \n',
    mml2: '<math> <msub> <mi> V </mi> <mi> &#x03BB; <!-- Î» --> </mi> </msub> <mo> = </mo> <munder> <mo> &#x2A01; <!-- â¨\x81 --> </mo> <mrow> <mi> w </mi> <mrow> <mi> i </mi> <mi> n </mi> </mrow> <mi> F </mi> </mrow> </munder> <msub> <mi> W </mi> <mi> w </mi> </msub> </math>\n'
  },
  {
    eqn_num: 1568,
    mml1: '<math>  <msub>  <mi> &#x0394; <!-- Î\x94 -->  </mi>  <mi> t </mi>  </msub>  <mo> ( </mo>  <msub>  <mi> S </mi>  <mrow>   <mi>  &#x03BB; <!-- Î» -->  </mi>  </mrow>  </msub>  <mo> ) </mo>  <mo> = </mo>  <mrow>  <mo> | </mo>  </mrow>  <msub>  <mi> S </mi>  <mrow>   <mi>  &#x03BB; <!-- Î» -->  </mi>  </mrow>  </msub>  <msup>  <mrow>  <mo> | </mo>  </mrow>  <mi> t </mi>  </msup>  <msub>  <mi> S </mi>  <mrow>   <mstyle>   <mrow>  <msub>  <mi> p </mi>  <mi> i </mi>  </msub>  </mrow>  </mstyle>  </mrow>  </msub>  <mrow>  <mo> | </mo>  </mrow>  <msub>  <mi> S </mi>  <mrow>   <mi>  &#x03BB; <!-- Î» -->  </mi>  </mrow>  </msub>  <msup>  <mrow>  <mo> | </mo>  </mrow>  <mrow>  <mn> 1 </mn>  <mo> &#x2212; <!-- â\x88\x92 -->  </mo>  <mi> t </mi>  </mrow>  </msup>  </math> \n',
    mml2: '<math> <msub> <mi> &#x0394; <!-- Î\x94 --> </mi> <mi> t </mi> </msub> <mo> ( </mo> <msub> <mi> S </mi> <mrow> <mi> &#x03BB; <!-- Î» --> </mi> </mrow> </msub> <mo> ) </mo> <mo> = </mo> <mrow> <mo> | </mo> </mrow> <msub> <mi> S </mi> <mrow> <mi> &#x03BB; <!-- Î» --> </mi> </mrow> </msub> <msup> <mrow> <mo> | </mo> </mrow> <mi> t </mi> </msup> <msub> <mi> S </mi> <mstyle> <mrow> <msub> <mi> p </mi> <mi> i </mi> </msub> </mrow> </mstyle> </msub> <mrow> <mo> | </mo> </mrow> <msub> <mi> S </mi> <mrow> <mi> &#x03BB; <!-- Î» --> </mi> </mrow> </msub> <msup> <mrow> <mo> | </mo> </mrow> <mrow> <mn> 1 </mn> <mo> &#x2212; <!-- â\x88\x92 --> </mo> <mi> t </mi> </mrow> </msup> </math>\n'
  },
  {
    eqn_num: 4692,
    mml1: '<math>  <mi> s </mi>  <mo> = </mo>   <mo>  &#x2308; <!-- â\x8c\x88 -->  </mo>  <msub>  <mi> ln </mi>  <mi> q </mi>  </msub>  <mo> &#x2061; <!-- â\x81¡ -->  </mo>  <mo> ( </mo>  <mn> 2 </mn>  <mi> D </mi>  <mo> + </mo>  <mn> 1 </mn>  <mo> ) </mo>   <mo>  &#x2309; <!-- â\x8c\x89 -->  </mo>  </math> \n',
    mml2: '<math> <mi> s </mi> <mo> = </mo> <mo> &#x2308; <!-- â\x8c\x88 --> </mo> <msub> <mi> log </mi> <mi> q </mi> </msub> <mo> &#x2061; <!-- â\x81¡ --> </mo> <mo> ( </mo> <mn> 2 </mn> <mi> D </mi> <mo> + </mo> <mn> 1 </mn> <mo> ) </mo> <mo> &#x2309; <!-- â\x8c\x89 --> </mo> </math>\n'
  },
  {
    eqn_num: 898,
    mml1: '<math>  <mo> ( </mo>  <mn> 1 </mn>  <mo> &#x2212; <!-- â\x88\x92 -->  </mo>  <mi> q </mi>  <mo> ) </mo>  <msubsup>  <mi> &#x2113; <!-- â\x84\x93 -->  </mi>  <mrow>  <mi> T </mi>  </mrow>  <mn> 1 </mn>  </msubsup>  <mo> + </mo>  <mi> q </mi>  <msubsup>  <mi> &#x2113; <!-- â\x84\x93 -->  </mi>  <mrow>  <mi> T </mi>  </mrow>  <mn> 2 </mn>  </msubsup>  <mo> &#x2A7E; <!-- â©¾ -->  </mo>  <mi> &#x03BD; <!-- Î½ -->  </mi>  <mo> ( </mo>  <mi> q </mi>  <mo> ) </mo>  </math> \n',
    mml2: '<math> <mo> ( </mo> <mn> 1 </mn> <mo> &#x2212; <!-- â\x88\x92 --> </mo> <mi> q </mi> <mo> ) </mo> <msubsup> <mi> &#x2113; <!-- â\x84\x93 --> </mi> <mrow> <mi> T </mi> </mrow> <mn> 1 </mn> </msubsup> <mo> + </mo> <mi> q </mi> <msubsup> <mi> &#x2113; <!-- â\x84\x93 --> </mi> <mi> T </mi> <mn> 2 </mn> </msubsup> <mo> &#x2A7E; <!-- â©¾ --> </mo> <mi> &#x03BD; <!-- Î½ --> </mi> <mo> ( </mo> <mi> q </mi> <mo> ) </mo> </math>\n'
  },
  {
    eqn_num: 4812,
    mml1: '<math>  <msub>  <mi> &#x2202; <!-- â\x88\x82 -->  </mi>  <mrow>  <msub>  <mi> &#x03BE; <!-- Î¾ -->  </mi>  <mn> 2 </mn>  </msub>  </mrow>  </msub>  <msub>  <mi> r </mi>  <mn> 0 </mn>  </msub>  <mrow>  <mo> ( </mo>  <msub>  <mi> x </mi>  <mn> 2 </mn>  </msub>  <mo> , </mo>  <mi> &#x03BE; <!-- Î¾ -->  </mi>  <mo> , </mo>  <mi> &#x03B5; <!-- Îµ -->  </mi>  <mo> , </mo>   <mstyle>   <mrow>  <mfrac>  <msup>  <mi> h </mi>  <mn> 2 </mn>  </msup>  <mi> &#x03B5; <!-- Îµ -->  </mi>  </mfrac>  </mrow>  </mstyle>  <mo> ) </mo>  </mrow>  <mo> = </mo>  <msub>  <mi> &#x2202; <!-- â\x88\x82 -->  </mi>  <mrow>  <msub>  <mi> &#x03BE; <!-- Î¾ -->  </mi>  <mn> 2 </mn>  </msub>  </mrow>  </msub>   <mo>  &#x27E8; <!-- â\x9f¨ -->  </mo>  <mrow>  <mi> q </mi>   <mo>  &#x27E9; <!-- â\x9f© -->  </mo>  </mrow>  <mo> ( </mo>  <mi> &#x03BE; <!-- Î¾ -->  </mi>  <mo> ) </mo>  <mo> + </mo>  <mrow>  <mi> O </mi>  </mrow>  <mrow>  <mo> ( </mo>  <mi> &#x03B5; <!-- Îµ -->  </mi>  <mo> + </mo>   <mstyle>   <mrow>  <mfrac>  <msup>  <mi> h </mi>  <mn> 2 </mn>  </msup>  <mi> &#x03B5; <!-- Îµ -->  </mi>  </mfrac>  </mrow>  </mstyle>  <mo> ) </mo>  </mrow>  </math> \n',
    mml2: '<math> <msub> <mi> &#x2202; <!-- â\x88\x82 --> </mi> <mrow> <msub> <mi> &#x03BE; <!-- Î¾ --> </mi> <mn> 2 </mn> </msub> </mrow> </msub> <msub> <mi> r </mi> <mn> 0 </mn> </msub> <mrow> <mo> ( </mo> <msub> <mi> x </mi> <mn> 2 </mn> </msub> <mo> , </mo> <mi> &#x03BE; <!-- Î¾ --> </mi> <mo> , </mo> <mi> &#x03B5; <!-- Îµ --> </mi> <mo> , </mo> <mstyle> <mrow> <mfrac> <msup> <mi> h </mi> <mn> 2 </mn> </msup> <mi> &#x03B5; <!-- Îµ --> </mi> </mfrac> </mrow> </mstyle> <mo> ) </mo> </mrow> <mo> = </mo> <msub> <mi> &#x2202; <!-- â\x88\x82 --> </mi> <mrow> <msub> <mi> &#x03BE; <!-- Î¾ --> </mi> <mn> 2 </mn> </msub> </mrow> </msub> <mo> ( </mo> <mi> q </mi> <mo> ) </mo> <mo> ( </mo> <mi> &#x03BE; <!-- Î¾ --> </mi> <mo> ) </mo> <mo> + </mo> <mrow> <mi> O </mi> </mrow> <mrow> <mo> ( </mo> <mi> &#x03B5; <!-- Îµ --> </mi>\n'
  },
  {
    eqn_num: 2810,
    mml1: '<math>  <msub>  <mi> &#x03B4; <!-- Î´ -->  </mi>  <mrow>  <mrow>  <mi> T </mi>  <mi> S </mi>  <mi> M </mi>  </mrow>  </mrow>  </msub>  <mstyle scriptlevel="0">  <mrow>   <mi>  ( </mo>  </mrow>  </mstyle>  <msubsup>  <mi> G </mi>  <mi> k </mi>  <mo> + </mo>  </msubsup>  <mo> , </mo>  <msubsup>  <mi> G </mi>  <mi> k </mi>  <mo> &#x2212; <!-- â\x88\x92 -->  </mo>  </msubsup>  <mstyle scriptlevel="0">  <mrow>   <mi>  ) </mo>  </mrow>  </mstyle>  <mo> = </mo>  </math> \n',
    mml2: '<math> <msub> <mi> &#x03B4; <!-- Î´ --> </mi> <mrow> <mi> T </mi> <mi> S </mi> <mi> M </mi> </mrow> </msub> <mstyle scriptlevel="0"> <mrow> <mi> ( </mo> </mrow> </mstyle> <msubsup> <mi> G </mi> <mi> k </mi> <mo> + </mo> </msubsup> <mo> , </mo> <msubsup> <mi> G </mi> <mi> k </mi> <mo> &#x2212; <!-- â\x88\x92 --> </mo> </msubsup> <mstyle scriptlevel="0"> <mrow> <mi> ) </mo> </mrow> </mstyle> <mo> = </mo> </math>\n'
  },
  {
    eqn_num: 68,
    mml1: '<math>  <msup>  <mi> g </mi>  <mrow>  <mi> &#x03BC; <!-- Î¼ -->  </mi>  <mi> &#x03BD; <!-- Î½ -->  </mi>  </mrow>  </msup>  <msub>  <mi> R </mi>  <mi> &#x03BC; <!-- Î¼ -->  </mi>  </msub>  <msub>  <mi> R </mi>  <mi> &#x03BD; <!-- Î½ -->  </mi>  </msub>  <mo> = </mo>  <msup>  <mi> N </mi>  <mrow>  <mo> &#x2212; <!-- â\x88\x92 -->  </mo>  <mn> 2 </mn>  </mrow>  </msup>  <msup>  <mrow>  <mover>  <mi> R </mi>  <mo> &#x02D9; <!-- Ë\x99 -->  </mo>  </mover>  </mrow>  <mn> 2 </mn>  </msup>  <mo> &#x2212; <!-- â\x88\x92 -->  </mo>  <msup>  <mi> a </mi>  <mrow>  <mo> &#x2212; <!-- â\x88\x92 -->  </mo>  <mn> 2 </mn>  </mrow>  </msup>  <msup>  <mi> R </mi>  <mrow>  <mi> &#x2032; <!-- â\x80² -->  </mi>  <mn> 2 </mn>  </mrow>  </msup>  <mo> &lt; </mo>  <mn> 0 </mn>  </math> \n',
    mml2: '<math> <msup> <mi> g </mi> <mrow> <mi> &#x03BC; <!-- Î¼ --> </mi> <mi> &#x03BD; <!-- Î½ --> </mi> </mrow> </msup> <msub> <mi> R </mi> <mi> &#x03BC; <!-- Î¼ --> </mi> </msub> <msub> <mi> R </mi> <mi> &#x03BD; <!-- Î½ --> </mi> </msub> <mo> = </mo> <msup> <mi> N </mi> <mrow> <mo> &#x2212; <!-- â\x88\x92 --> </mo> <mn> 2 </mn> </mrow> </msup> <msup> <mrow> <mover> <mi> R </mi> <mo> &#x02D9; <!-- Ë\x99 --> </mo> </mover> </mrow> <mn> 2 </mn> </msup> <mo> &#x2212; <!-- â\x88\x92 --> </mo> <msup> <mi> a </mi> <mrow> <mo> &#x2212; <!-- â\x88\x92 --> </mo> <mn> 2 </mn> </mrow> </msup> <msup> <mi> R </mi> <mrow> <mo> &#x2032; </mo> <mn> 2 </mn> </mrow> </msup> <mo> &lt; </mo> <mn> 0 </mn> </math>\n'
  },
  {
    eqn_num: 1012,
    mml1: '<math>  <mi> F </mi>  <mo> ( </mo>  <mi> I </mi>  <mo> ( </mo>  <mrow>   <mn>  1 </mn>  </mrow>  <mo> ) </mo>  <mo> ) </mo>  <mo> = </mo>  <munder>  <mo> &#x2A01; <!-- â¨\x81 -->  </mo>  <mrow>  <mi> X </mi>  <mrow>  <mi> i </mi>  <mi> n </mi>  </mrow>  <mrow>   <mi>  O </mi>  </mrow>  <mo> ( </mo>  <mrow>  <mi> C </mi>  </mrow>  <mo> ) </mo>  </mrow>  </munder>  <mi> X </mi>  <mo> &#x2297; <!-- â\x8a\x97 -->  </mo>  <mrow>   <mn>  1 </mn>  </mrow>  <mo> &#x2297; <!-- â\x8a\x97 -->  </mo>  <msup>  <mi> X </mi>  <mo> &#x2217; <!-- â\x88\x97 -->  </mo>  </msup>   <mi>   </math> \n',
    mml2: '<math> <mi> F </mi> <mo> ( </mo> <mi> I </mi> <mo> ( </mo> <mrow> <mn> 1 </mn> </mrow> <mo> ) </mo> <mo> ) </mo> <mo> = </mo> <munder> <mo> &#x2A01; <!-- â¨\x81 --> </mo> <mrow> <mi> X </mi> <mrow> <mi> i </mi> <mi> n </mi> </mrow> <mrow> <mi> Q </mi> </mrow> <mo> ( </mo> <mrow> <mi> C </mi> </mrow> <mo> ) </mo> </mrow> </munder> <mi> X </mi> <mo> &#x2297; <!-- â\x8a\x97 --> </mo> <mrow> <mn> 1 </mn> </mrow> <mo> &#x2297; <!-- â\x8a\x97 --> </mo> <msup> <mi> X </mi> <mo> &#x2217; <!-- â\x88\x97 --> </mo> </msup> </math>\n'
  },
  {
    eqn_num: 2873,
    mml1: '<math>  <mi> A </mi>  <mo> ( </mo>  <mi> T </mi>  <mo> ) </mo>  <mo> &#x221D; <!-- â\x88\x9d -->  </mo>   <mstyle>   <mrow>  <mfrac>  <mrow>  <msub>  <mi> &#x03B5; <!-- Îµ -->  </mi>  <mi> I </mi>  </msub>  <mrow>  <mo> / </mo>  </mrow>  <mo> ( </mo>  <mi> &#x0394; <!-- Î\x94 -->  </mi>  <mo> ( </mo>  <mi> T </mi>  <mo> ) </mo>  <mo> + </mo>  <msub>  <mi> &#x03F0; <!-- Ï° -->  </mi>  <mi> B </mi>  </msub>  <mi> T </mi>  <mrow>  <mo> / </mo>  </mrow>  <mn> 2 </mn>  <mo> ) </mo>  </mrow>  <mrow>  <mn> 1 </mn>  <mo> + </mo>  <mi> &#x03B3; <!-- Î³ -->  </mi>  <msqrt>   <mstyle>   <mrow>  <mfrac>  <mrow>  <mn> 2 </mn>  <msub>  <mi> &#x03F0; <!-- Ï° -->  </mi>  <mi> B </mi>  </msub>  <mi> T </mi>  </mrow>  <mrow>   <mstyle>   <mrow>  <msub>  <mi> p </mi>  <mi> i </mi>  </msub>  </mrow>  </mstyle>  <mi> &#x0394; <!-- Î\x94 -->  </mi>  <mo> ( </mo>  <mi> T </mi>  <mo> ) </mo>  </mrow>  </mfrac>  </mrow>  </mstyle>  </msqrt>  <mi> e </mi>  <mi> x </mi>  <mi> p </mi>  <mo> ( </mo>  <mo> &#x2212; <!-- â\x88\x92 -->  </mo>  <mi> &#x0394; <!-- Î\x94 -->  </mi>  <mo> ( </mo>  <mi> T </mi>  <mo> ) </mo>  <mrow>  <mo> / </mo>  </mrow>  <msub>  <mi> &#x03F0; <!-- Ï° -->  </mi>  <mi> B </mi>  </msub>  <mi> T </mi>  <mo> ) </mo>  </mrow>  </mfrac>  </mrow>  </mstyle>  </math> \n',
    mml2: '<math> <mi> A </mi> <mo> ( </mo> <mi> T </mi> <mo> ) </mo> <mo> &#x221D; <!-- â\x88\x9d --> </mo> <mstyle> <mrow> <mfrac> <mrow> <msub> <mi> &#x03B5; <!-- Îµ --> </mi> <mi> I </mi> </msub> <mrow> <mo> / </mo> </mrow> <mo> ( </mo> <mi> &#x0394; <!-- Î\x94 --> </mi> <mo> ( </mo> <mi> T </mi> <mo> ) </mo> <mo> + </mo> <msub> <mi> &#x03F0; <!-- Ï° --> </mi> <mi> B </mi> </msub> <mi> T </mi> <mrow> <mo> / </mo> </mrow> <mn> 2 </mn> <mo> ) </mo> </mrow> <mrow> <mstyle> <mrow> <msub> <mi> p </mi> <mi> i </mi> </msub> </mrow> </mstyle> <mi> &#x0394; <!-- Î\x94 --> </mi> <mo> ( </mo> <mi> f </mi> <mo> ) </mo> </mrow> </mfrac> </mrow> <mi> e </mi> <mi> x </mi> <mi> p </mi> <mo> ( </mo> <mo> &#x2212; <!-- â\x88\x92 --> </mo> <mi> &#x0394; <!-- Î\x94 --> </mi> <mo> ( </mo> <mi> T </mi> <mo> ) </mo>\n'
  },
  {
    eqn_num: 280,
    mml1: '<math>  <msub>  <mo> &#x222B; <!-- â\x88« -->  </mo>  <mi> X </mi>  </msub>  <mo> ( </mo>  <mrow>  <mi> o </mi>  </mrow>  <mo> + </mo>  <mi> i </mi>  <mi> &#x2202; <!-- â\x88\x82 -->  </mi>  <mover>  <mi> &#x2202; <!-- â\x88\x82 -->  </mi>  <mo> &#x00AF; <!-- Â¯ -->  </mo>  </mover>  <mi> v </mi>  <msup>  <mo> ) </mo>  <mi> n </mi>  </msup>  <mo> &#x2A7D; <!-- â©½ -->  </mo>  <msub>  <mo> &#x222B; <!-- â\x88« -->  </mo>  <mrow>  <mi> X </mi>  </mrow>  </msub>  <msup>  <mrow>  <mi> o </mi>  </mrow>  <mi> n </mi>  </msup>  <mo> = </mo>  <mo> ( </mo>  <mi> X </mi>  <mo> ) </mo>  </math> \n',
    mml2: '<math> <msub> <mo> &#x222B; <!-- â\x88« --> </mo> <mi> X </mi> </msub> <mo> ( </mo> <mrow> <mi> o </mi> </mrow> <mo> + </mo> <mi> i </mi> <mi> &#x2202; <!-- â\x88\x82 --> </mi> <mover> <mi> &#x2202; <!-- â\x88\x82 --> </mi> <mo> &#x00AF; <!-- Â¯ --> </mo> </mover> <mi> v </mi> <msup> <mo> ) </mo> <mi> n </mi> </msup> <mo> &#x2A7D; <!-- â©½ --> </mo> <msub> <mo> &#x222B; <!-- â\x88« --> </mo> <mi> X </mi> </msub> <msup> <mrow> <mi> o </mi> </mrow> <mi> n </mi> </msup> <mo> = </mo> <mo> ( </mo> <mi> X </mi> <mo> ) </mo> </math>\n'
  },
  {
    eqn_num: 2264,
    mml1: '<math>  <msub>  <mi> S </mi>  <mi> l </mi>  </msub>  <mo> = </mo>  <munderover>  <mo> &#x2211; <!-- â\x88\x91 -->  </mo>  <mrow>  <mi> i </mi>  <mo> = </mo>  <mn> 1 </mn>  </mrow>  <mrow>  <mi> l </mi>  </mrow>  </munderover>  <msub>  <mi> X </mi>  <mi> i </mi>  </msub>  <mo> &#x2A7D; <!-- â©½ -->  </mo>  <mn> 2 </mn>  <mo> ( </mo>  <mn> 1 </mn>  <mo> + </mo>  <mi> Z </mi>  <mo> ) </mo>  <munderover>  <mo> &#x2211; <!-- â\x88\x91 -->  </mo>  <mrow>  <mi> i </mi>  <mo> = </mo>  <mn> 1 </mn>  </mrow>  <mi> l </mi>  </munderover>  <msub>  <mi> a </mi>  <mi> i </mi>  </msub>  </math> \n',
    mml2: '<math> <msub> <mi> S </mi> <mi> l </mi> </msub> <mo> = </mo> <munderover> <mo> &#x2211; <!-- â\x88\x91 --> </mo> <mrow> <mi> i </mi> <mo> = </mo> <mn> 1 </mn> </mrow> <mi> l </mi> </munderover> <msub> <mi> X </mi> <mi> i </mi> </msub> <mo> &#x2A7D; <!-- â©½ --> </mo> <mn> 2 </mn> <mo> ( </mo> <mn> 1 </mn> <mo> + </mo> <mi> Z </mi> <mo> ) </mo> <munderover> <mo> &#x2211; <!-- â\x88\x91 --> </mo> <mrow> <mi> i </mi> <mo> = </mo> <mn> 1 </mn> </mrow> <mi> l </mi> </munderover> <msub> <mi> a </mi> <mi> i </mi> </msub> </math>\n'
  },
];