eqn_src = [
  {
    eqn_num: 617,
    mml1: '<math>   <mstyle>    <mstyle>   <mrow>  <mfrac>  <mi> d </mi>  <mrow>  <mi> d </mi>  <mi> t </mi>  </mrow>  </mfrac>  </mrow>  <msub>  <mi> I </mi>  <mrow>  <mi> &#x221E; <!-- â\x88\x9e -->  </mi>  </mrow>  </msub>  <mo> ( </mo>  <mi> &#x03B1; <!-- Î± -->  </mi>  <mo> ( </mo>  <mi> t </mi>  <mo> ) </mo>  <mo> ) </mo>  <mo> = </mo>   <mstyle>    <mstyle>   <mrow>  <mfrac>  <msup>  <mi> t </mi>  <mrow>  <mi> n </mi>  <mo> &#x2212; <!-- â\x88\x92 -->  </mo>  <mn> 2 </mn>  <mi> s </mi>  <mo> &#x2212; <!-- â\x88\x92 -->  </mo>  <mn> 1 </mn>  </mrow>  </msup>  <mn> 2 </mn>  </mfrac>  </mrow>  <mo> ( </mo>  <mi> n </mi>  <mo> &#x2212; <!-- â\x88\x92 -->  </mo>  <mn> 2 </mn>  <mi> s </mi>  <mo> ) </mo>  <mo> ( </mo>  <mn> 1 </mn>  <mo> &#x2212; <!-- â\x88\x92 -->  </mo>  <msup>  <mi> t </mi>  <mrow>  <mn> 2 </mn>  <mi> s </mi>  </mrow>  </msup>  <mo> ) </mo>   <mstyle>   <mo> &#x222B; <!-- â\x88« -->  </mo>  <mrow>  <mo> | </mo>  </mrow>  <mo> ( </mo>  <mo> &#x2212; <!-- â\x88\x92 -->  </mo>  <mi> &#x0394; <!-- Î\x94 -->  </mi>  <msup>  <mo> ) </mo>  <mrow>  <mi> s </mi>  <mrow>  <mo> / </mo>  </mrow>  <mn> 2 </mn>  </mrow>  </msup>  <mi> w </mi>  <msup>  <mrow>  <mo> | </mo>  </mrow>  <mrow>  <mn> 2 </mn>  </mrow>  </msup>  </mstyle>  </mstyle>  </mstyle>  </mstyle>  </mstyle>  </math> \n',
    mml2: '<math> <mstyle> <mrow> <mfrac> <mi> d </mi> <mrow> <mi> d </mi> <mi> t </mi> </mrow> </mfrac> </mrow> <msub> <mi> I </mi> <mrow> <mi> &#x221E; <!-- â\x88\x9e --> </mi> </mrow> </msub> <mo> ( </mo> <mi> &#x03B1; <!-- Î± --> </mi> <mo> ( </mo> <mi> t </mi> <mo> ) </mo> <mo> ) </mo> <mo> = </mo> <mstyle> <mrow> <mfrac> <msup> <mi> t </mi> <mrow> <mi> n </mi> <mo> &#x2212; <!-- â\x88\x92 --> </mo> <mn> 2 </mn> <mi> s </mi> <mo> &#x2212; <!-- â\x88\x92 --> </mo> <mn> 1 </mn> </mrow> </msup> <mn> 2 </mn> </mfrac> </mrow> <mo> ( </mo> <mi> n </mi> <mo> &#x2212; <!-- â\x88\x92 --> </mo> <mn> 2 </mn> <mi> s </mi> <mo> ) </mo> <mo> ( </mo> <mn> 1 </mn> <mo> &#x2212; <!-- â\x88\x92 --> </mo> <msup> <mi> t </mi> <mrow> <mn> 2 </mn> <mi> s </mi> </mrow> </msup> <mo> ) </mo> <mo> &#x222B; <!-- â\x88« --> </mo> <mrow> <mo>\n'
  },
  {
    eqn_num: 2013,
    mml1: '<math>  <mi> n </mi>  <mo> + </mo>  <mover>  <mi> e </mi>  <mo> &#x00AF; <!-- Â¯ -->  </mo>  </mover>  <mo> &#x2194; <!-- â\x86\x94 -->  </mo>  <mi> p </mi>  <mo> + </mo>  <msub>  <mover>  <mi> &#x03BD; <!-- Î½ -->  </mi>  <mo> &#x00AF; <!-- Â¯ -->  </mo>  </mover>  <mi> e </mi>  </msub>  <mo> , </mo>  <mtext> &#xA0; </mtext>  <mi> n </mi>  <mo> + </mo>  <msub>  <mi> &#x03BD; <!-- Î½ -->  </mi>  <mi> e </mi>  </msub>  <mo> &#x2194; <!-- â\x86\x94 -->  </mo>  <mi> p </mi>  <mo> + </mo>  <mi> e </mi>  <mo> , </mo>  <mtext> &#xA0; </mtext>  </math> \n',
    mml2: '<math> <mi> n </mi> <mo> + </mo> <mover> <mi> e </mi> <mo> &#x00AF; <!-- Â¯ --> </mo> </mover> <mo> &#x2194; <!-- â\x86\x94 --> </mo> <mi> p </mi> <mo> + </mo> <msub> <mover> <mi> &#x03BD; <!-- Î½ --> </mi> <mo> &#x00AF; <!-- Â¯ --> </mo> </mover> <mi> e </mi> </msub> <mo> , </mo> <mtext> &#xA0; </mtext> <mi> n </mi> <mo> + </mo> <msub> <mi> &#x03BD; <!-- Î½ --> </mi> <mi> e </mi> </msub> <mo> &#x2194; <!-- â\x86\x94 --> </mo> <mi> p </mi> <mo> + </mo> <mi> e </mi> <mo> , </mo> <mstyle> </math>\n'
  },
  {
    eqn_num: 1023,
    mml1: '<math>  <mrow>  <mrow>  <mi> Z </mi>  </mrow>  </mrow>  <mo> ( </mo>  <mi> &#x03A3; <!-- Î£ -->  </mi>  <mo> , </mo>  <mi> X </mi>  <mo> , </mo>  <mi> Y </mi>  <mo> , </mo>  <mi> z </mi>  <mo> , </mo>  <mi> z </mi>  <mo> &#x2212; <!-- â\x88\x92 -->  </mo>  <mi> z </mi>  <mo> ( </mo>  <mi> Y </mi>  <mo> ) </mo>  <mo> , </mo>  <mo> , </mo>  <mo> &#x2026; <!-- â\x80¦ -->  </mo>  <mo> , </mo>  <mo> ) </mo>  <mo> = </mo>  <mo> ( </mo>  <mi> z </mi>  <mo> ( </mo>  <mi> Y </mi>  <mo> ) </mo>  <mo> &#x2212; <!-- â\x88\x92 -->  </mo>  <mi> z </mi>  <mo> ( </mo>  <mi> X </mi>  <mo> ) </mo>  <msup>  <mo> ) </mo>  <mrow>  <mi> h </mi>  <mo> &#x2212; <!-- â\x88\x92 -->  </mo>  <msub>  <mi> h </mi>  <mi> X </mi>  </msub>  <mo> &#x2212; <!-- â\x88\x92 -->  </mo>  <msub>  <mi> h </mi>  <mi> Y </mi>  </msub>  </mrow>  </msup>  <mrow>  <mo> ( </mo>  <munderover>  <mo> &#x2211; <!-- â\x88\x91 -->  </mo>  <mrow>  <mi> k </mi>  <mo> = </mo>  <mn> 0 </mn>  </mrow>  <mi> n </mi>  </munderover>  <msub>  <mrow>  <mrow>  <mi> Z </mi>  </mrow>  </mrow>  <mi> k </mi>  </msub>  <mo> ( </mo>  <mi> &#x03A3; <!-- Î£ -->  </mi>  <mo> , </mo>  <mi> X </mi>  <mo> , </mo>  <mi> z </mi>  <mo> , </mo>  <mo> , </mo>  <mo> &#x2026; <!-- â\x80¦ -->  </mo>  <mo> , </mo>  <mo> ) </mo>  <mo> ( </mo>  <mi> z </mi>  <mo> ( </mo>  <mi> Y </mi>  <mo> ) </mo>  <mo> &#x2212; <!-- â\x88\x92 -->  </mo>  <mi> z </mi>  <mo> ( </mo>  <mi> X </mi>  <mo> ) </mo>  <msup>  <mo> ) </mo>  <mi> k </mi>  </msup>  <mo> + </mo>  <mi> O </mi>  <mo> ( </mo>  <mo> ( </mo>  <mi> z </mi>  <mo> ( </mo>  <mi> Y </mi>  <mo> ) </mo>  <mo> &#x2212; <!-- â\x88\x92 -->  </mo>  <mi> z </mi>  <mo> ( </mo>  <mi> X </mi>  <mo> ) </mo>  <msup>  <mo> ) </mo>  <mrow>  <mi> n </mi>  <mo> + </mo>  <mn> 1 </mn>  </mrow>  </msup>  <mo> ) </mo>  <mo> ) </mo>  </mrow>  </math> \n',
    mml2: '<math> <mrow> <mi> Z </mi> </mrow> <mo> ( </mo> <mi> &#x03A3; <!-- Î£ --> </mi> <mo> , </mo> <mi> X </mi> <mo> , </mo> <mi> Y </mi> <mo> , </mo> <mi> z </mi> <mo> , </mo> <mi> z </mi> <mo> &#x2212; <!-- â\x88\x92 --> </mo> <mi> z </mi> <mo> ( </mo> <mi> Y </mi> <mo> ) </mo> <mo> , </mo> <mo> &#x2026; <!-- â\x80¦ --> </mo> <mo> ) </mo> <mo> = </mo> <mo> ( </mo> <mi> z </mi> <mo> ( </mo> <mi> Y </mi> <mo> ) </mo> <mo> &#x2212; <!-- â\x88\x92 --> </mo> <mi> z </mi> <mo> ( </mo> <mi> X </mi> <mo> ) </mo> <msup> <mo> ) </mo> <mrow> <mi> h </mi> <mo> &#x2212; <!-- â\x88\x92 --> </mo> <msub> <mi> h </mi> <mi> X </mi> </msub> <mo> &#x2212; <!-- â\x88\x92 --> </mo> <msub> <mi> h </mi> <mi> Y </mi> </msub> </mrow> </msup> <mrow> <mo> ( </mo> <munderover> <mo> &#x2211;\n'
  },
  {
    eqn_num: 621,
    mml1: '<math>   <mo>  &#x2016; <!-- â\x80\x96 -->  </mo>  <mi> f </mi>  <msub>   <mo>  &#x2016; <!-- â\x80\x96 -->  </mo>  <mrow>  <msup>  <mi> C </mi>  <mrow>  <mn> 1 </mn>  <mo> , </mo>  <mi> &#x03B1; <!-- Î± -->  </mi>  </mrow>  </msup>  </mrow>  </msub>  <mo> &#x2A7D; <!-- â©½ -->  </mo>  <mi> c </mi>   <mo>  &#x2016; <!-- â\x80\x96 -->  </mo>  <mi> f </mi>  <msub>   <mo>  &#x2016; <!-- â\x80\x96 -->  </mo>  <mrow>  <msubsup>  <mi> H </mi>  <mi> p </mi>  <mrow>  <mn> 1 </mn>  <mo> + </mo>  <mi> &#x03B4; <!-- Î´ -->  </mi>  </mrow>  </msubsup>  </mrow>  </msub>  <mo> , </mo>   <mstyle>    <mo>  &#x2016; <!-- â\x80\x96 -->  </mo>  <mi> &#x2207; <!-- â\x88\x87 -->  </mi>  <mi> f </mi>  <msub>   <mo>  &#x2016; <!-- â\x80\x96 -->  </mo>  <mrow>  <msup>  <mi> C </mi>  <mrow>  <mn> 0 </mn>  <mo> , </mo>  <mi> &#x03B1; <!-- Î± -->  </mi>  </mrow>  </msup>  </mrow>  </msub>  <mo> &#x2A7D; <!-- â©½ -->  </mo>  <mi> c </mi>   <mo>  &#x2016; <!-- â\x80\x96 -->  </mo>  <mi> &#x2207; <!-- â\x88\x87 -->  </mi>  <mi> f </mi>  <msub>   <mo>  &#x2016; <!-- â\x80\x96 -->  </mo>  <mrow>  <msubsup>  <mi> H </mi>  <mi> p </mi>  <mrow>  <mi> &#x03B4; <!-- Î´ -->  </mi>  </mrow>  </msubsup>  </mrow>  </msub>  </math> \n',
    mml2: '<math> <mo> &#x2016; <!-- â\x80\x96 --> </mo> <mi> f </mi> <msub> <mo> &#x2016; <!-- â\x80\x96 --> </mo> <mrow> <msup> <mi> C </mi> <mrow> <mn> 1 </mn> <mo> , </mo> <mi> &#x03B1; <!-- Î± --> </mi> </mrow> </msup> </mrow> </msub> <mo> &#x2A7D; <!-- â©½ --> </mo> <mi> c </mi> <mo> &#x2016; <!-- â\x80\x96 --> </mo> <mi> f </mi> <msub> <mo> &#x2016; <!-- â\x80\x96 --> </mo> <mrow> <msubsup> <mi> H </mi> <mi> p </mi> <mrow> <mn> 1 </mn> <mo> + </mo> <mi> &#x03B4; <!-- Î´ --> </mi> </mrow> </msubsup> </mrow> </msub> <mo> , </mo> <mo> <mo> &#x2016; <!-- â\x80\x96 --> </mo> <mi> &#x2207; <!-- â\x88\x87 --> </mi> <mi> f </mi> <msub> <mo> &#x2016; <!-- â\x80\x96 --> </mo> <mrow> <msup> <mi> C </mi> <mrow> <mn> 0 </mn> <mo> , </mo> <mi> &#x03B1; <!-- Î± --> </mi> </mrow> </msup> </mrow> </msub> <mo> &#x2A7D; <!-- â©½ --> </mo> <mi> c </mi> <mo> &#x2016; <!-- â\x80\x96\n'
  },
  {
    eqn_num: 2315,
    mml1: '<math>  <msub>  <mrow>  <mover>  <mi> N </mi>  <mo> &#x007E; <!-- ~ -->  </mo>  </mover>  </mrow>  <mrow>  <mi> F </mi>  <mo> ( </mo>  <mi> A </mi>  <mo> ) </mo>  </mrow>  </msub>  <mo> ( </mo>  <mi> k </mi>  <mo> , </mo>  <mi> x </mi>  <mo> , </mo>  <mrow>   <mi>  R </mi>  </mrow>  <mo> ) </mo>  <mo> = </mo>  <mo> &#x222B; <!-- â\x88« -->  </mo>  <msup>  <mi> d </mi>  <mn> 2 </mn>  </msup>  <mrow>   <mi>  r </mi>  </mrow>   <mi>   </math> \n',
    mml2: '<math> <msub> <mrow> <mover> <mi> N </mi> <mo> &#x007E; <!-- ~ --> </mo> </mover> </mrow> <mrow> <mi> F </mi> <mo> ( </mo> <mi> A </mi> <mo> ) </mo> </mrow> </msub> <mo> ( </mo> <mi> k </mi> <mo> , </mo> <mi> x </mi> <mo> , </mo> <mrow> <mi> R </mi> </mrow> <mo> ) </mo> <mo> = </mo> <mo> &#x222B; <!-- â\x88« --> </mo> <msup> <mi> d </mi> <mn> 2 </mn> </msup> <mrow> <mi> r </mi> </mrow> </math>\n'
  },
  {
    eqn_num: 3307,
    mml1: '<math>  <mi> f </mi>  <mo> ( </mo>  <msub>  <mrow>   <mi>  s </mi>  </mrow>  <mrow>  <mo> [ </mo>  <mi> &#x03F0; <!-- Ï° -->  </mi>  <mo> , </mo>  <mi> l </mi>  <mo> ] </mo>  </mrow>  </msub>  <mi> x </mi>  <mo> ) </mo>  <mo> = </mo>  <mi> f </mi>  <mo> ( </mo>  <msubsup>  <mrow>   <mi>  s </mi>  </mrow>  <mrow>  <mi> &#x03BC; <!-- Î¼ -->  </mi>  </mrow>  <mrow>  <mi> l </mi>  </mrow>  </msubsup>  <msubsup>  <mrow>   <mi>  s </mi>  </mrow>  <mrow>  <mi> l </mi>  </mrow>  <mrow>  <mi> &#x03F0; <!-- Ï° -->  </mi>  </mrow>  </msubsup>  <msubsup>  <mrow>   <mi>  s </mi>  </mrow>  <mrow>  <mi> &#x03F0; <!-- Ï° -->  </mi>  </mrow>  <mrow>  <mi> &#x03BC; <!-- Î¼ -->  </mi>  </mrow>  </msubsup>  <msub>  <mrow>   <mi>  c </mi>  </mrow>  <mrow>  <mi> &#x03BC; <!-- Î¼ -->  </mi>  </mrow>  </msub>  <mi> x </mi>  <mo> ) </mo>   <mn>   </math> \n',
    mml2: '<math> <mi> f </mi> <mo> ( </mo> <msub> <mrow> <mi> s </mi> </mrow> <mrow> <mo> [ </mo> <mi> &#x03F0; <!-- Ï° --> </mi> <mo> , </mo> <mi> l </mi> <mo> ] </mo> </mrow> </msub> <mi> x </mi> <mo> ) </mo> <mo> = </mo> <mi> f </mi> <mo> ( </mo> <msubsup> <mrow> <mi> s </mi> </mrow> <mrow> <mi> &#x03BC; <!-- Î¼ --> </mi> </mrow> <mrow> <mi> l </mi> </mrow> </msubsup> <msubsup> <mrow> <mi> s </mi> </mrow> <mrow> <mi> l </mi> </mrow> <mrow> <mi> &#x03F0; <!-- Ï° --> </mi> </mrow> </msubsup> <msubsup> <mrow> <mi> s </mi> </mrow> <mrow> <mi> &#x03F0; <!-- Ï° --> </mi> </mrow> <mrow> <mi> &#x03BC; <!-- Î¼ --> </mi> </mrow> </msubsup> <msub> <mrow> <mi> c </mi> </mrow> <mrow> <mi> &#x03BC; <!-- Î¼ --> </mi> </mrow> </msub> <mi> x </mi> <mo> ) </mo> </math>\n'
  },
  {
    eqn_num: 1275,
    mml1: '<math>  <mo> ( </mo>   <mi>  max </mo>   <mo>  { </mo>  <mi> a </mi>  <mo> &#x2212; <!-- â\x88\x92 -->  </mo>  <mi> b </mi>  <mo> , </mo>  <mn> 0 </mn>   <mo>  } </mo>  <mo> + </mo>  <mi> c </mi>  <msup>  <mo> ) </mo>  <mn> 2 </mn>  </msup>   <mi>   </math> \n',
    mml2: '<math> <mo> ( </mo> <mi> max </mo> <mo> { </mo> <mi> a </mi> <mo> &#x2212; <!-- â\x88\x92 --> </mo> <mi> b </mi> <mo> , </mo> <mn> 0 </mn> <mo> } </mo> <mo> + </mo> <mi> c </mi> <msup> <mo> ) </mo> <mn> 2 </mn> </msup> </math>\n'
  },
  {
    eqn_num: 1903,
    mml1: '<math>  <msub>  <mi> G </mi>  <mrow>  <mi> m </mi>  <mi> i </mi>  <mi> n </mi>  </mrow>  </msub>  <mo> ( </mo>  <msub>  <mi> L </mi>  <mi> v </mi>  </msub>  <mo> , </mo>  <mi> q </mi>  <mo> ) </mo>  <mo> = </mo>  <munder>   <mi>  min </mo>  <mrow>  <msubsup>  <mi> E </mi>  <mi> i </mi>  <mi> x </mi>  </msubsup>  <mrow>  <mi> i </mi>  <mi> n </mi>  </mrow>  <msub>  <mi> L </mi>  <mi> v </mi>  </msub>  </mrow>  </munder>  <mrow>  <msubsup>  <mi> G </mi>  <mi> i </mi>  <mi> x </mi>  </msubsup>  <mo> ( </mo>  <msup>  <mi> r </mi>  <mi> x </mi>  </msup>  <mo> , </mo>  <mi> q </mi>  <mo> ) </mo>  </mrow>  </math> \n',
    mml2: '<math> <msub> <mi> G </mi> <mrow> <mi> m </mi> <mi> i </mi> <mi> n </mi> </mrow> </msub> <mo> ( </mo> <msub> <mi> L </mi> <mi> v </mi> </msub> <mo> , </mo> <mi> q </mi> <mo> ) </mo> <mo> = </mo> <munder> <mi> min </mo> <mrow> <msubsup> <mi> E </mi> <mi> i </mi> <mi> x </mi> </msubsup> <mrow> <mi> i </mi> <mi> n </mi> </mrow> <msub> <mi> L </mi> <mi> v </mi> </msub> </mrow> </munder> <msubsup> <mi> G </mi> <mi> i </mi> <mi> x </mi> </msubsup> <mo> ( </mo> <msup> <mi> r </mi> <mi> x </mi> </msup> <mo> , </mo> <mi> q </mi> <mo> ) </mo> </math>\n'
  },
  {
    eqn_num: 1581,
    mml1: '<math>  <msubsup>  <mi> q </mi>  <mrow>  <mn> 1 </mn>  <mi> A </mi>  <mn> 1 </mn>  </mrow>  <mi> A </mi>  </msubsup>  <mo> + </mo>  <msubsup>  <mi> q </mi>  <mrow>  <mn> 1 </mn>  <mi> A </mi>  <mn> 2 </mn>  </mrow>  <mi> A </mi>  </msubsup>  <mo> = </mo>  <msub>  <mi> q </mi>  <mrow>  <mn> 1 </mn>  <mi> A </mi>  </mrow>  </msub>  <mo> , </mo>   <mi>   </math> \n',
    mml2: '<math> <msubsup> <mi> q </mi> <mrow> <mn> 1 </mn> <mi> A </mi> <mn> 1 </mn> </mrow> <mi> A </mi> </msubsup> <mo> + </mo> <msubsup> <mi> q </mi> <mrow> <mn> 1 </mn> <mi> A </mi> <mn> 2 </mn> </mrow> <mi> A </mi> </msubsup> <mo> = </mo> <msub> <mi> q </mi> <mrow> <mn> 1 </mn> <mi> A </mi> </mrow> </msub> <mo> , </mo> <mstyle> </math>\n'
  },
  {
    eqn_num: 64,
    mml1: '<math>  <mn> 2 </mn>  <mo> &#x2212; <!-- â\x88\x92 -->  </mo>  <mn> 2 </mn>  <mi> g </mi>  <mo> = </mo>  <mrow>  <mo> | </mo>  </mrow>  <mi> G </mi>  <mrow>  <mo> | </mo>  </mrow>  <mrow>  <mo> ( </mo>   <mstyle>   <mrow>  <mfrac>  <mn> 1 </mn>  <mi> r </mi>  </mfrac>  </mrow>  <mo> + </mo>   <mstyle>   <mrow>  <mfrac>  <mn> 1 </mn>  <mi> s </mi>  </mfrac>  </mrow>  <mo> + </mo>   <mstyle>   <mrow>  <mfrac>  <mn> 1 </mn>  <mi> t </mi>  </mfrac>  </mrow>  <mo> &#x2212; <!-- â\x88\x92 -->  </mo>  <mn> 1 </mn>  </mstyle>  </mstyle>  </mstyle>  <mo> ) </mo>  </mrow>  </math> \n',
    mml2: '<math> <mn> 2 </mn> <mo> &#x2212; <!-- â\x88\x92 --> </mo> <mn> 2 </mn> <mi> g </mi> <mo> = </mo> <mrow> <mo> | </mo> </mrow> <mi> G </mi> <mrow> <mo> | </mo> </mrow> <mrow> <mo> ( </mo> <mstyle> <mrow> <mfrac> <mn> 1 </mn> <mi> r </mi> </mfrac> </mrow> <mo> + </mo> <mstyle> <mrow> <mfrac> <mn> 1 </mn> <mi> s </mi> </mfrac> </mrow> <mo> + </mo> <mstyle> <mrow> <mfrac> <mn> 1 </mn> <mi> t </mi> </mfrac> </mrow> <mo> &#x2212; <!-- â\x88\x92 --> </mo> <mn> 1 </mn> </mstyle> </mstyle> <mo> ) </mo> </mrow> </mstyle> </math>\n'
  },
  {
    eqn_num: 65,
    mml1: '<math>  <mi> f </mi>  <mo> ( </mo>  <mi> r </mi>  <mo> ) </mo>  <mo> = </mo>  <msup>  <mi> g </mi>  <mn> 2 </mn>  </msup>  <msup>  <mi> r </mi>  <mn> 2 </mn>  </msup>  <mo> &#x2212; <!-- â\x88\x92 -->  </mo>  <mn> 1 </mn>  <mo> + </mo>   <mstyle>   <mrow>  <mfrac>  <mrow>  <mn> 2 </mn>  <mi> M </mi>  </mrow>  <mi> r </mi>  </mfrac>  </mrow>  <mo> &#x2212; <!-- â\x88\x92 -->  </mo>   <mstyle>   <mrow>  <mfrac>  <msup>  <mi> Q </mi>  <mn> 2 </mn>  </msup>  <msup>  <mi> r </mi>  <mn> 2 </mn>  </msup>  </mfrac>  </mrow>  <mtext> &#xA0; </mtext>  </mstyle>  </mstyle>  </math> \n',
    mml2: '<math> <mi> f </mi> <mo> ( </mo> <mi> r </mi> <mo> ) </mo> <mo> = </mo> <msup> <mi> g </mi> <mn> 2 </mn> </msup> <msup> <mi> r </mi> <mn> 2 </mn> </msup> <mo> &#x2212; <!-- â\x88\x92 --> </mo> <mn> 1 </mn> <mo> + </mo> <mstyle> <mrow> <mfrac> <mrow> <mn> 2 </mn> <mi> M </mi> </mrow> <mi> r </mi> </mfrac> </mrow> <mo> &#x2212; <!-- â\x88\x92 --> </mo> <mstyle> <mrow> <mfrac> <msup> <mi> Q </mi> <mn> 2 </mn> </msup> <msup> <mi> r </mi> <mn> 2 </mn> </msup> </mfrac> </mrow> </mstyle> </mstyle> </math>\n'
  },
  {
    eqn_num: 1555,
    mml1: '<math>  <msub>  <mi> v </mi>  <mi> i </mi>  </msub>  <mo> ( </mo>  <mi> x </mi>  <mo> + </mo>  <mi> y </mi>  <msup>  <mo> ) </mo>  <mrow>  <mi> s </mi>  <mo> + </mo>  <mi> r </mi>  <mo> &#x2212; <!-- â\x88\x92 -->  </mo>  <mn> 2 </mn>  <mo> &#x2212; <!-- â\x88\x92 -->  </mo>  <mn> 2 </mn>  <mi> i </mi>  </mrow>  </msup>  <mo> = </mo>  <munderover>  <mo> &#x2211; <!-- â\x88\x91 -->  </mo>  <mrow>  <mi> k </mi>  <mo> = </mo>  <mn> 0 </mn>  </mrow>  <mi> i </mi>  </munderover>  <munderover>  <mo> &#x2211; <!-- â\x88\x91 -->  </mo>  <mrow>  <mi> j </mi>  <mo> = </mo>  <mn> 0 </mn>  </mrow>  <mi> i </mi>  </munderover>   <mstyle>   <msub>  <mi> &#x03BD; <!-- Î½ -->  </mi>  <mi> k </mi>  </msub>  <mrow>  <mstyle scriptlevel="0">  <mrow>   <mi>  ( </mo>  </mrow>  </mstyle>   <mfrac>   <mrow>  <mi> s </mi>  <mo> + </mo>  <mi> r </mi>  <mo> &#x2212; <!-- â\x88\x92 -->  </mo>  <mn> 2 </mn>  <mo> &#x2212; <!-- â\x88\x92 -->  </mo>  <mn> 2 </mn>  <mi> i </mi>  </mrow>  <mrow>  <mi> r </mi>  <mo> &#x2212; <!-- â\x88\x92 -->  </mo>  <mn> 1 </mn>  <mo> &#x2212; <!-- â\x88\x92 -->  </mo>  <mi> i </mi>  <mo> &#x2212; <!-- â\x88\x92 -->  </mo>  <mi> j </mi>  <mo> + </mo>  <mi> k </mi>  </mrow>  </mfrac>  <mstyle scriptlevel="0">  <mrow>   <mi>  ) </mo>  </mrow>  </mstyle>  </mrow>  <msup>  <mi> x </mi>  <mrow>  <mi> r </mi>  <mo> &#x2212; <!-- â\x88\x92 -->  </mo>  <mn> 1 </mn>  <mo> &#x2212; <!-- â\x88\x92 -->  </mo>  <mi> j </mi>  </mrow>  </msup>  <msup>  <mi> y </mi>  <mrow>  <mi> s </mi>  <mo> &#x2212; <!-- â\x88\x92 -->  </mo>  <mn> 1 </mn>  <mo> &#x2212; <!-- â\x88\x92 -->  </mo>  <mi> i </mi>  <mo> + </mo>  <mi> j </mi>  </mrow>  </msup>   <mstyle>   </math> \n',
    mml2: '<math> <msub> <mi> v </mi> <mi> i </mi> </msub> <mo> ( </mo> <mi> x </mi> <mo> + </mo> <mi> y </mi> <msup> <mo> ) </mo> <mrow> <mi> s </mi> <mo> + </mo> <mi> r </mi> <mo> &#x2212; <!-- â\x88\x92 --> </mo> <mn> 2 </mn> <mo> &#x2212; <!-- â\x88\x92 --> </mo> <mn> 2 </mn> <mi> i </mi> </mrow> </msup> <mo> = </mo> <munderover> <mo> &#x2211; <!-- â\x88\x91 --> </mo> <mrow> <mi> k </mi> <mo> = </mo> <mn> 0 </mn> </mrow> <mi> i </mi> </munderover> <munderover> <mo> &#x2211; <!-- â\x88\x91 --> </mo> <mrow> <mi> j </mi> <mo> = </mo> <mn> 0 </mn> </mrow> <mi> i </mi> </munderover> <msub> <mi> &#x03BD; <!-- Î½ --> </mi> <mi> k </mi> </msub> <mrow> <mstyle scriptlevel="0"> <mrow> <mi> ( </mo> </mrow> </mstyle> <mfrac> <mrow> <mi> s </mi> <mo> + </mo> <mi> r </mi> <mo> &#x2212; <!-- â\x88\x92 --> </mo> <mn> 2 </mn> <mo> &#x2212; <!-- â\x88\x92 -->\n'
  },
  {
    eqn_num: 290,
    mml1: '<math>  <msup>  <mi> S </mi>  <mrow>  <mo> ( </mo>  <mo> ) </mo>  </mrow>  </msup>  <mo> = </mo>  <mo> &#x2212; <!-- â\x88\x92 -->  </mo>  <mo> &#x222B; <!-- â\x88« -->  </mo>  <msup>  <mi> d </mi>  <mn> 4 </mn>  </msup>  <mi> x </mi>  <msqrt>  <mo> &#x2212; <!-- â\x88\x92 -->  </mo>  <mi> g </mi>  </msqrt>   <mstyle>   <mrow>  <mi> L </mi>  </mrow>  <mtext> &#xA0; </mtext>  </math> \n',
    mml2: '<math> <msup> <mi> S </mi> <mrow> <mo> ( </mo> <mo> ) </mo> </mrow> </msup> <mo> = </mo> <mo> &#x2212; <!-- â\x88\x92 --> </mo> <mo> &#x222B; <!-- â\x88« --> </mo> <msup> <mi> d </mi> <mn> 4 </mn> </msup> <mi> x </mi> <msqrt> <mo> &#x2212; <!-- â\x88\x92 --> </mo> <mi> g </mi> </msqrt> <mstyle> <mrow> <mi> L </mi> </mrow> </math>\n'
  },
  {
    eqn_num: 2364,
    mml1: '<math>  <msub>  <mi> &#x03C7; <!-- Ï\x87 -->  </mi>  <mn> 2 </mn>  </msub>  <mo> ( </mo>  <mi> G </mi>  <mo> ) </mo>  <mo> &#x2A7D; <!-- â©½ -->  </mo>  <mi> &#x03C7; <!-- Ï\x87 -->  </mi>  <mo> ( </mo>  <mi> G </mi>  <mo> ) </mo>  <mo> + </mo>  <mi> e </mi>  <mo> ( </mo>  <mn> 1 </mn>  <mo> + </mo>  <mi> log </mi>  <mo> &#x2061; <!-- â\x81¡ -->  </mo>  <mo> ( </mo>  <msup>  <mi> d </mi>  <mn> 2 </mn>  </msup>  <mo> + </mo>  <mn> 1 </mn>  <mo> ) </mo>  <mo> ) </mo>  </math> \n',
    mml2: '<math> <msub> <mi> &#x03C7; <!-- Ï\x87 --> </mi> <mn> 2 </mn> </msub> <mo> ( </mo> <mi> G </mi> <mo> ) </mo> <mo> &#x2A7D; <!-- â©½ --> </mo> <mi> &#x03C7; <!-- Ï\x87 --> </mi> <mo> ( </mo> <mi> G </mi> <mo> ) </mo> <mo> + </mo> <mi> e </mi> <mo> ( </mo> <mn> 1 </mn> <mo> + </mo> <mi> ln </mi> <mo> &#x2061; <!-- â\x81¡ --> </mo> <mo> ( </mo> <msup> <mi> d </mi> <mn> 2 </mn> </msup> <mo> + </mo> <mn> 1 </mn> <mo> ) </mo> <mo> ) </mo> </math>\n'
  },
  {
    eqn_num: 2611,
    mml1: '<math>  <msubsup>  <mi> x </mi>  <mn> 1 </mn>  <mn> 2 </mn>  </msubsup>  <mo> ( </mo>  <msub>  <mi> &#x03C4; <!-- Ï\x84 -->  </mi>  <mn> 1 </mn>  </msub>  <mo> ) </mo>  <mo> = </mo>   <mstyle>   <mrow>  <mfrac>  <mrow>  <mi> &#x03B4; <!-- Î´ -->  </mi>  <mo> &#x2212; <!-- â\x88\x92 -->  </mo>  <mn> 1 </mn>  <mo> + </mo>  <msqrt>  <msup>  <mi> &#x03B4; <!-- Î´ -->  </mi>  <mn> 2 </mn>  </msup>  <mo> + </mo>  <mo> ( </mo>  <mn> 4 </mn>  <msubsup>  <mi> c </mi>  <mn> 1 </mn>  <mn> 2 </mn>  </msubsup>  <mo> + </mo>  <mn> 2 </mn>  <mo> ) </mo>  <mi> &#x03B4; <!-- Î´ -->  </mi>  <mo> + </mo>  <mn> 1 </mn>  </msqrt>  </mrow>  <mrow>  <mn> 2 </mn>  <mi> &#x03B4; <!-- Î´ -->  </mi>  </mrow>  </mfrac>  </mrow>  </mstyle>  </math> \n',
    mml2: '<math> <msubsup> <mi> x </mi> <mn> 1 </mn> <mn> 2 </mn> </msubsup> <mo> ( </mo> <msub> <mi> &#x03C4; <!-- Ï\x84 --> </mi> <mn> 1 </mn> </msub> <mo> ) </mo> <mo> = </mo> <mstyle> <mrow> <mfrac> <mrow> <mi> &#x03B4; <!-- Î´ --> </mi> <mo> &#x2212; <!-- â\x88\x92 --> </mo> <mn> 1 </mn> <mo> + </mo> <msqrt> <msup> <mi> &#x03B4; <!-- Î´ --> </mi> <mn> 2 </mn> </msup> <mo> + </mo> <mo> ( </mo> <mn> 4 </mn> <msubsup> <mi> c </mi> <mn> 7 </mn> <mn> 2 </mn> </msubsup> <mo> + </mo> <mn> 2 </mn> <mo> ) </mo> <mi> &#x03B4; <!-- Î´ --> </mi> <mo> + </mo> <mn> 1 </mn> </msqrt> </mrow> <mrow> <mn> 2 </mn> <mi> &#x03B4; <!-- Î´ --> </mi> </mrow> </mfrac> </mrow> </mstyle> </math>\n'
  },
  {
    eqn_num: 1012,
    mml1: '<math>  <msub>  <mi> u </mi>  <mi> i </mi>  </msub>  <mo> ( </mo>  <mi> x </mi>  <mo> ) </mo>  <mo> = </mo>  <mo> &#x2212; <!-- â\x88\x92 -->  </mo>  <mn> 2 </mn>  <msub>  <mi> &#x03B2; <!-- Î² -->  </mi>  <mi> i </mi>  </msub>  <mi> ln </mi>  <mo> &#x2061; <!-- â\x81¡ -->  </mo>  <mrow>  <mo> | </mo>  </mrow>  <mi> x </mi>  <mrow>  <mo> | </mo>  </mrow>  <mo> + </mo>  <mi> O </mi>  <mo> ( </mo>  <mn> 1 </mn>  <mo> ) </mo>  <mo> , </mo>   <mo>   <mi> i </mi>  <mo> = </mo>  <mn> 1 </mn>  <mo> , </mo>  <mn> 2 </mn>  <mo> , </mo>  <mi> &#x221E; <!-- â\x88\x9e -->  </mi>  </math> \n',
    mml2: '<math> <msub> <mi> u </mi> <mi> i </mi> </msub> <mo> ( </mo> <mi> x </mi> <mo> ) </mo> <mo> = </mo> <mo> &#x2212; <!-- â\x88\x92 --> </mo> <mn> 2 </mn> <msub> <mi> &#x03B2; <!-- Î² --> </mi> <mi> i </mi> </msub> <mi> ln </mi> <mo> &#x2061; <!-- â\x81¡ --> </mo> <mrow> <mo> | </mo> </mrow> <mi> x </mi> <mrow> <mo> | </mo> </mrow> <mo> + </mo> <mi> O </mi> <mo> ( </mo> <mn> 1 </mn> <mo> ) </mo> <mo> , </mo> <mstyle> <mi> i </mi> <mo> = </mo> <mn> 1 </mn> <mo> , </mo> <mn> 2 </mn> <mo> , </mo> <mi> &#x221E; <!-- â\x88\x9e --> </mi> </math>\n'
  },
  {
    eqn_num: 519,
    mml1: '<math>  <msub>  <mi> s </mi>  <mi> n </mi>  </msub>  <mo> ( </mo>  <mi> x </mi>  <mo> ) </mo>  <mo> = </mo>  <munderover>  <mo> &#x2211; <!-- â\x88\x91 -->  </mo>  <mrow>  <mi> m </mi>  <mo> = </mo>  <mn> 0 </mn>  </mrow>  <mi> n </mi>  </munderover>  <msub>  <mi> C </mi>  <mrow>  <mi> n </mi>  <mo> , </mo>  <mi> m </mi>  </mrow>  </msub>  <msub>  <mi> r </mi>  <mi> m </mi>  </msub>  <mo> ( </mo>  <mi> x </mi>  <mo> ) </mo>   <mstyle>   <mo> ( </mo>  <mi> n </mi>  <mo> &#x2A7E; <!-- â©¾ -->  </mo>  <mn> 0 </mn>  <mo> ) </mo>   <mstyle>   </math> \n',
    mml2: '<math> <msub> <mi> s </mi> <mi> n </mi> </msub> <mo> ( </mo> <mi> x </mi> <mo> ) </mo> <mo> = </mo> <munderover> <mo> &#x2211; <!-- â\x88\x91 --> </mo> <mrow> <mi> m </mi> <mo> = </mo> <mn> 0 </mn> </mrow> <mi> n </mi> </munderover> <msub> <mi> C </mi> <mrow> <mi> n </mi> <mo> , </mo> <mi> m </mi> </mrow> </msub> <msub> <mi> r </mi> <mi> m </mi> </msub> <mo> ( </mo> <mi> x </mi> <mo> ) </mo> <mstyle> <mo> ( </mo> <mi> n </mi> <mo> &#x2A7E; <!-- â©¾ --> </mo> <mn> 0 </mn> <mo> ) </mo> </math>\n'
  },
  {
    eqn_num: 2305,
    mml1: '<math>  <msup>  <mi> h </mi>  <mn> 2 </mn>  </msup>  <mo> = </mo>  <msub>  <mi> c </mi>  <mn> 1 </mn>  </msub>  <msup>  <mi> e </mi>  <mrow>   <mstyle>   <mrow>  <mfrac>  <mn> 3 </mn>  <mn> 2 </mn>  </mfrac>  </mrow>  <msub>  <mi> m </mi>  <mn> 1 </mn>  </msub>  <mi> x </mi>  </mstyle>  </mrow>  </msup>  <mo> + </mo>  <msub>  <mi> c </mi>  <mn> 2 </mn>  </msub>  <msup>  <mi> e </mi>  <mrow>   <mstyle>   <mrow>  <mfrac>  <mn> 3 </mn>  <mn> 2 </mn>  </mfrac>  </mrow>  <msub>  <mi> m </mi>  <mn> 2 </mn>  </msub>  <mi> x </mi>  </mstyle>  </mrow>  </msup>  </math> \n',
    mml2: '<math> <msup> <mi> h </mi> <mn> 2 </mn> </msup> <mo> = </mo> <msub> <mi> c </mi> <mn> 1 </mn> </msub> <msup> <mi> e </mi> <mrow> <mstyle> <mrow> <mfrac> <mn> 5 </mn> <mn> 2 </mn> </mfrac> </mrow> <msub> <mi> m </mi> <mn> 1 </mn> </msub> <mi> x </mi> </mstyle> </mrow> </msup> <mo> + </mo> <msub> <mi> c </mi> <mn> 2 </mn> </msub> <msup> <mi> e </mi> <mrow> <mstyle> <mrow> <mfrac> <mn> 3 </mn> <mn> 2 </mn> </mfrac> </mrow> <msub> <mi> m </mi> <mn> 2 </mn> </msub> <mi> x </mi> </mstyle> </mrow> </msup> </math>\n'
  },
  {
    eqn_num: 429,
    mml1: '<math>  <mo> ( </mo>  <mrow>   <mi>  z </mi>  </mrow>  <mo> , </mo>  <mi> &#x03C4; <!-- Ï\x84 -->  </mi>  <mo> ) </mo>  <mo> &#x22C5; <!-- â\x8b\x85 -->  </mo>  <mo> ( </mo>  <mrow>  <msup>   <mi>  z </mi>  <mo> &#x2032; </mo>  </msup>  </mrow>  <mo> , </mo>  <msup>  <mi> &#x03C4; <!-- Ï\x84 -->  </mi>  <mo> &#x2032; </mo>  </msup>  <mo> ) </mo>  <mo> = </mo>  <mo> ( </mo>  <mo> ( </mo>  <msub>  <mi> z </mi>  <mn> 1 </mn>  </msub>  <mo> + </mo>  <msubsup>  <mi> z </mi>  <mrow>  <msup>  <mi> &#x03C4; <!-- Ï\x84 -->  </mi>  <mrow>  <mo> &#x2212; <!-- â\x88\x92 -->  </mo>  <mn> 1 </mn>  </mrow>  </msup>  <mo> ( </mo>  <mn> 1 </mn>  <mo> ) </mo>  </mrow>  <mo> &#x2032; </mo>  </msubsup>  <mo> , </mo>  <mo> , </mo>  <mo> &#x2026; <!-- â\x80¦ -->  </mo>  <mo> , </mo>  <mo> , </mo>  <msub>  <mi> z </mi>  <mi> n </mi>  </msub>  <mo> + </mo>  <msubsup>  <mi> z </mi>  <mrow>  <msup>  <mi> &#x03C4; <!-- Ï\x84 -->  </mi>  <mrow>  <mo> &#x2212; <!-- â\x88\x92 -->  </mo>  <mn> 1 </mn>  </mrow>  </msup>  <mo> ( </mo>  <mi> n </mi>  <mo> ) </mo>  </mrow>  <mo> &#x2032; </mo>  </msubsup>  <mo> ) </mo>  <mo> , </mo>  <mi> &#x03C4; <!-- Ï\x84 -->  </mi>  <mo> &#x2218; <!-- â\x88\x98 -->  </mo>  <msup>  <mi> &#x03C4; <!-- Ï\x84 -->  </mi>  <mo> &#x2032; </mo>  </msup>  <mo> ) </mo>  </math> \n',
    mml2: '<math> <mo> ( </mo> <mrow> <mi> z </mi> </mrow> <mo> , </mo> <mi> &#x03C4; <!-- Ï\x84 --> </mi> <mo> ) </mo> <mo> &#x22C5; <!-- â\x8b --> </mo> <mo> ( </mo> <mrow> <msup> <mi> z </mi> <mo> &#x2032; </mo> </msup> </mrow> <mo> , </mo> <msup> <mi> &#x03C4; <!-- Ï\x84 --> </mi> <mo> &#x2032; </mo> </msup> <mo> ) </mo> <mo> = </mo> <mo> ( </mo> <mo> ( </mo> <msub> <mi> z </mi> <mn> 1 </mn> </msub> <mo> + </mo> <msubsup> <mi> z </mi> <mrow> <msup> <mi> &#x03C4; <!-- Ï\x84 --> </mi> <mrow> <mo> &#x2212; <!-- â\x88\x92 --> </mo> <mn> 1 </mn> </mrow> </msup> <mo> ( </mo> <mn> 1 </mn> <mo> ) </mo> </mrow> <mo> &#x2032; </mo> </msubsup> <mo> , </mo> <mo> &#x2026; <!-- â\x80¦ --> </mo> <mo> , </mo> <msub> <mi> z </mi> <mi> n </mi> </msub> <mo> + </mo> <msubsup> <mi> z </mi> <mrow> <msup> <mi> &#x03C4; <!-- Ï\x84 --> </mi>\n'
  },
  {
    eqn_num: 2730,
    mml1: '<math>  <mi> e </mi>  <mo> = </mo>  <mrow>  <mo> ( </mo>   <mn>   <mtr>  <mtd>  <mn> 1 </mn>  <mo> &#x2212; <!-- â\x88\x92 -->  </mo>  <mo> ( </mo>  <mn> 1 </mn>  <mo> &#x2212; <!-- â\x88\x92 -->  </mo>  <mi> Q </mi>  <mi> P </mi>  <msup>  <mo> ) </mo>  <mn> 2 </mn>  </msup>  <mi> Q </mi>  <mo> ( </mo>  <mn> 2 </mn>  <mo> &#x2212; <!-- â\x88\x92 -->  </mo>  <mi> P </mi>  <mi> Q </mi>  <mo> ) </mo>  <mo> ( </mo>  <mn> 1 </mn>  <mo> &#x2212; <!-- â\x88\x92 -->  </mo>  <mi> P </mi>  <mi> Q </mi>  <mo> ) </mo>  </mtd>  </mtr>  <mtr>  <mtd>  <mo> ( </mo>  <mn> 1 </mn>  <mo> &#x2212; <!-- â\x88\x92 -->  </mo>  <mi> P </mi>  <mi> Q </mi>  <mo> ) </mo>  <mi> P </mi>  <mi> Q </mi>  <mo> ( </mo>  <mn> 2 </mn>  <mo> &#x2212; <!-- â\x88\x92 -->  </mo>  <mi> P </mi>  <mi> Q </mi>  <mo> ) </mo>  <mo> ( </mo>  <mn> 1 </mn>  <mo> &#x2212; <!-- â\x88\x92 -->  </mo>  <mi> P </mi>  <mi> Q </mi>  <mo> ) </mo>  </mtd>  </mtr>  <mtr>  <mtd>  <mo> ( </mo>  <mn> 1 </mn>  <mo> &#x2212; <!-- â\x88\x92 -->  </mo>  <mi> P </mi>  <mi> Q </mi>  <mo> ) </mo>  <mi> P </mi>  <mo> ( </mo>  <mn> 1 </mn>  <mo> &#x2212; <!-- â\x88\x92 -->  </mo>  <mi> P </mi>  <mi> Q </mi>  <msup>  <mo> ) </mo>  <mn> 2 </mn>  </msup>  </mtd>  </mtr>   <mn>   <mo> ) </mo>  </mrow>  <mtext> &#xA0; </mtext>  <mo> , </mo>   <mstyle>   <msub>  <mi> e </mi>  <mn> 0 </mn>  </msub>  <mo> = </mo>  <mrow>  <mo> ( </mo>   <mn>   <mtr>  <mtd>  <mn> 1 </mn>  <mo> ( </mo>  <mn> 1 </mn>  <mo> &#x2212; <!-- â\x88\x92 -->  </mo>  <mi> P </mi>  <mi> Q </mi>  <msup>  <mo> ) </mo>  <mn> 2 </mn>  </msup>  </mtd>  </mtr>   <mn>   <mo> ) </mo>  </mrow>  <mtext> &#xA0; </mtext>  <mo> , </mo>   <mstyle>   <msub>  <mi> e </mi>  <mn> 0 </mn>  </msub>  <mo> = </mo>  <mrow>  <mo> ( </mo>   <mn>   <mtr>  <mtd>  <mn> 1 </mn>  </mtd>  <mtd>  <mn> 0 </mn>  </mtd>  </mtr>  <mtr>  <mtd>  <mn> 0 </mn>  <mn> 0 </mn>  </mtd>  </mtr>  <mtr>  <mtd>  <mn> 0 </mn>  </mtd>  <mtd>  <mn> 0 </mn>  </mtd>  </mtr>   <mn>   <mo> ) </mo>  </mrow>  <mtext> &#xA0; </mtext>  </math> \n',
    mml2: '<math> <mi> e </mi> <mo> = </mo> <mrow> <mo> ( </mo> <mn> <mtr> <mtd> <mn> 1 </mn> <mo> &#x2212; <!-- â\x88\x92 --> </mo> <mo> ( </mo> <mn> 1 </mn> <mo> &#x2212; <!-- â\x88\x92 --> </mo> <mi> Q </mi> <mi> P </mi> <msup> <mo> ) </mo> <mn> 2 </mn> </msup> <mi> Q </mi> <mo> ( </mo> <mn> 2 </mn> <mo> &#x2212; <!-- â\x88\x92 --> </mo> <mi> P </mi> <mi> Q </mi> <mo> ) </mo> <mo> ( </mo> <mn> 1 </mn> <mo> &#x2212; <!-- â\x88\x92 --> </mo> <mi> P </mi> <mi> Q </mi> <mo> ) </mo> <mo> ( </mo> <mn> 1 </mn> <mo> &#x2212; <!-- â\x88\x92 --> </mo> <mi> P </mi> <mi> Q </mi> <mo> ) </mo> </mtd> </mtr> <mtr> <mtd> <mn> 0 </mn> </mtd> </mtr> <mn> <mo> ) </mo> </mrow> </math>\n'
  },
];