eqn_src = [
  {
    eqn_num: 1973,
    mml1: '<math>  <mi> &#x03C9; <!-- Ï\x89 -->  </mi>  <mo> &lt; </mo>  <mn> 2.3729372 </mn>  </math> \n',
    mml2: '<math> <mi> &#x03C9; <!-- Ï\x89 --> </mi> <mo> &lt; </mo> <mn> <unk> </mn> </math>\n'
  },
  {
    eqn_num: 1830,
    mml1: '<math>  <msub>  <mi> &#x03BE; <!-- Î¾ -->  </mi>  <mrow>  <mo> &#x00B1; <!-- Â± -->  </mo>  </mrow>  </msub>  <mo> := </mo>   <mstyle>   <mrow>  <mfrac>  <mrow>  <mi> &#x03BB; <!-- Î» -->  </mi>  <mo> &#x00B1; <!-- Â± -->  </mo>  <mroot>  <mn> 2 </mn>  <mn> 3 </mn>  </mroot>  <mi> &#x03C4; <!-- Ï\x84 -->  </mi>  </mrow>  <mroot>  <mn> 2 </mn>  <mn> 3 </mn>  </mroot>  </mfrac>  </mrow>  </mstyle>  </math> \n',
    mml2: '<math> <msub> <mi> &#x03BE; <!-- Î¾ --> </mi> <mo> &#x00B1; <!-- Â± --> </mo> </msub> <mo> := </mo> <mstyle> <mrow> <mfrac> <mrow> <mi> &#x03BB; <!-- Î» --> </mi> <mo> &#x00B1; <!-- Â± --> </mo> <mroot> <mn> 2 </mn> <mo> &#x00AF; <!-- Â¯ --> </mo> </mover> <mstyle> <mi> &#x03C4; <!-- Ï\x84 --> </mi> </mrow> <mroot> <mn> 2 </mn> <mn> 3 </mn> </mroot> </mfrac> </mrow> </mstyle> </math>\n'
  },
  {
    eqn_num: 890,
    mml1: '<math>  <mi> S </mi>  <mo> = </mo>  <mo> &#x222B; <!-- â\x88« -->  </mo>  <msup>  <mi> d </mi>  <mrow>  <mn> 4 </mn>  </mrow>  </msup>  <mi> x </mi>  <msqrt>  <mrow>  <mo> | </mo>  </mrow>  <mrow>   <mi>  g </mi>  </mrow>  <mrow>  <mo> | </mo>  </mrow>  </msqrt>   <mo>  { </mo>   <mstyle>   <mrow>  <mfrac>  <mn> 1 </mn>  <mrow>  <mn> 2 </mn>  <msup>  <mi> &#x03F0; <!-- Ï° -->  </mi>  <mrow>  <mn> 2 </mn>  </mrow>  </msup>  </mrow>  </mfrac>  </mrow>  <mi> f </mi>  <mo> ( </mo>  <msubsup>  <mtext> &#xA0; </mtext>  <mrow>  <mi> s </mi>  </mrow>  <mrow>  <mi> F </mi>  </mrow>  </msubsup>  <mi> R </mi>  <mo> , </mo>  <mi> &#x03C7; <!-- Ï\x87 -->  </mi>  <mo> ) </mo>  <mo> + </mo>  </mstyle>  </math> \n',
    mml2: '<math> <mi> S </mi> <mo> = </mo> <mo> &#x222B; <!-- â\x88« --> </mo> <msup> <mi> d </mi> <mn> 4 </mn> </msup> <mi> x </mi> <msqrt> <mrow> <mo> | </mo> </mrow> <mrow> <mi> g </mi> </mrow> <mrow> <mo> | </mo> </mrow> </msqrt> <mo> { </mo> <mstyle> <mrow> <mfrac> <mn> 1 </mn> <mrow> <mn> 2 </mn> <msup> <mi> &#x03F0; <!-- Ï° --> </mi> <mn> 2 </mn> </msup> </mrow> </mfrac> </mrow> <mi> f </mi> <mo> ( </mo> <mstyle> <mrow> <mfrac> <mi> F </mi> <mi> s </mi> </mfrac> </mrow> <mi> R </mi> <mo> , </mo> <mi> &#x03C7; <!-- Ï\x87 --> </mi> <mo> ) </mo> <mo> + </mo> </mstyle> </mstyle> </math>\n'
  },
  {
    eqn_num: 1291,
    mml1: '<math>  <msub>  <mrow>   <mo>  &#x2016; </mo>  <mi> &#x0393; <!-- Î\x93 -->  </mi>  <msub>  <mi> &#x03B6; <!-- Î¶ -->  </mi>  <mi> S </mi>  </msub>  <mo> &#x2212; <!-- â\x88\x92 -->  </mo>  <mi> &#x0393; <!-- Î\x93 -->  </mi>  <msub>  <mi> &#x03B6; <!-- Î¶ -->  </mi>  <mrow>  <msup>  <mi> S </mi>  <mi> c </mi>  </msup>  </mrow>  </msub>   <mo>  &#x2016; </mo>  </mrow>  <mn> 2 </mn>  </msub>  <mo> &#x2A7E; <!-- â©¾ -->  </mo>   <mstyle>   <mrow>  <mfrac>  <mrow>  <msup>  <mi> u </mi>  <mn> 2 </mn>  </msup>  <mi> &#x03B2; <!-- Î² -->  </mi>  </mrow>  <mn> 4 </mn>  </mfrac>  </mrow>  <msub>  <mrow>   <mo>  &#x2016; </mo>  <msub>  <mi> &#x03B6; <!-- Î¶ -->  </mi>  <mi> S </mi>  </msub>  <mo> &#x2212; <!-- â\x88\x92 -->  </mo>  <msub>  <mi> &#x03B6; <!-- Î¶ -->  </mi>  <mrow>  <msup>  <mi> S </mi>  <mi> c </mi>  </msup>  </mrow>  </msub>   <mo>  &#x2016; </mo>  </mrow>  <mn> 2 </mn>  </msub>  <mo> &#x2A7E; <!-- â©¾ -->  </mo>   <mstyle>   <mrow>  <mfrac>  <mrow>  <msup>  <mi> u </mi>  <mn> 2 </mn>  </msup>  <mi> &#x03B2; <!-- Î² -->  </mi>  </mrow>  <mn> 4 </mn>  </mfrac>  </mrow>  <msub>  <mrow>   <mo>  &#x2016; </mo>  <msub>  <mi> &#x03B6; <!-- Î¶ -->  </mi>  <mi> S </mi>  </msub>   <mo>  &#x2016; </mo>  </mrow>  <mn> 2 </mn>  </msub>  <mo> &#x2A7E; <!-- â©¾ -->  </mo>   <mstyle>   <mrow>  <mfrac>  <mrow>  <msup>  <mi> u </mi>  <mn> 2 </mn>  </msup>  <mi> &#x03B2; <!-- Î² -->  </mi>  <msub>  <mrow>   <mo>  &#x2016; </mo>  <msub>  <mi> &#x03B6; <!-- Î¶ -->  </mi>  <mi> S </mi>  </msub>   <mo>  &#x2016; </mo>  </mrow>  <mn> 1 </mn>  </msub>  </mrow>  <mrow>  <mn> 4 </mn>  <msqrt>  <mrow>  <mo> | </mo>  </mrow>  <mi> S </mi>  <mrow>  <mo> | </mo>  </mrow>  </msqrt>  </mrow>  </mfrac>  </mrow>  <mo> = </mo>   <mstyle>   <mrow>  <mfrac>  <mrow>  <msup>  <mi> u </mi>  <mn> 2 </mn>  </msup>  <mi> &#x03B2; <!-- Î² -->  </mi>  </mrow>  <mrow>  <mn> 4 </mn>  <msqrt>  <mrow>  <mo> | </mo>  </mrow>  <mi> S </mi>  <mrow>  <mo> | </mo>  </mrow>  </msqrt>  </mrow>  </mfrac>  </mrow>  </mstyle>  </mstyle>  </mstyle>  </mstyle>  </math> \n',
    mml2: '<math> <mo> &#x2016; <!-- â\x80\x96 --> </mo> <mi> &#x0393; <!-- Î\x93 --> </mi> <msub> <mi> &#x03B6; <!-- Î¶ --> </mi> <mi> S </mi> </msub> <mo> &#x2212; <!-- â\x88\x92 --> </mo> <mi> &#x0393; <!-- Î\x93 --> </mi> <msub> <mi> &#x03B6; <!-- Î¶ --> </mi> <mrow> <msup> <mi> S </mi> <mi> c </mi> </msup> </mrow> </msub> <msub> <mo> &#x2016; <!-- â\x80\x96 --> </mo> <mn> 2 </mn> </msub> <mo> &#x2A7E; <!-- â©¾ --> </mo> <mstyle> <mrow> <mfrac> <mrow> <msup> <mi> u </mi> <mn> 2 </mn> </msup> <mi> &#x03B2; <!-- Î² --> </mi> </mrow> <mn> 4 </mn> </mfrac> </mrow> <mo> &#x2016; <!-- â\x80\x96 --> </mo> <msub> <mi> &#x03B6; <!-- Î¶ --> </mi> <mi> S </mi> </msub> <mo> &#x2212; <!-- â\x88\x92 --> </mo> <msub> <mi> &#x03B6; <!-- Î¶ --> </mi> <mrow> <msup> <mi> S </mi> <mn> 2 </mn> </msup> </mrow> </msub> <msub> <mo> &#x2016; <!-- â\x80\x96 --> </mo> <mn> 2 </mn> </msub> <mo> &#x2A7E; <!--\n'
  },
  {
    eqn_num: 905,
    mml1: '<math>  <mi> u </mi>  <mrow>  <mi> i </mi>  <mi> n </mi>  </mrow>  <msup>  <mi> L </mi>  <mrow>  <mi> &#x221E; <!-- â\x88\x9e -->  </mi>  </mrow>  </msup>  <mo> ( </mo>  <mo> ( </mo>  <mn> 0 </mn>  <mo> , </mo>   <mo>   <mi> T </mi>  <mo> ) </mo>  <mo> ; </mo>  <msup>  <mi> L </mi>  <mrow>  <mn> 2 </mn>  </mrow>  </msup>  <mo> ( </mo>  <mi> &#x03A9; <!-- Î© -->  </mi>  <mo> ) </mo>  <mo> ) </mo>  <mo> &#x2229; <!-- â\x88© -->  </mo>  <msup>  <mi> L </mi>  <mrow>  <mn> 2 </mn>  </mrow>  </msup>  <mo> ( </mo>  <mo> ( </mo>  <mn> 0 </mn>  <mo> , </mo>   <mo>   <mi> T </mi>  <mo> ) </mo>  <mo> ; </mo>   <mo>   <msup>  <mi> H </mi>  <mrow>  <mi> &#x03B1; <!-- Î± -->  </mi>  </mrow>  </msup>  <mo> ( </mo>  <mi> &#x03A9; <!-- Î© -->  </mi>  <mo> ) </mo>  <mo> ) </mo>  </math> \n',
    mml2: '<math> <mi> u </mi> <mrow> <mi> i </mi> <mi> n </mi> </mrow> <msup> <mi> L </mi> <mi> &#x221E; <!-- â\x88\x9e --> </mi> </msup> <mo> ( </mo> <mo> ( </mo> <mn> 0 </mn> <mo> , </mo> <mi> <mi> T </mi> <mo> ) </mo> <mo> ; </mo> <msup> <mi> L </mi> <mn> 2 </mn> </msup> <mo> ( </mo> <mi> &#x03A9; <!-- Î© --> </mi> <mo> ) </mo> <mo> ) </mo> <mo> &#x2229; <!-- â\x88© --> </mo> <msup> <mi> L </mi> <mn> 2 </mn> </msup> <mo> ( </mo> <mo> ( </mo> <mn> 0 </mn> <mo> , </mo> <mi> <mi> T </mi> <mo> ) </mo> <mo> ; </mo> <mi> <msup> <mi> H </mi> <mi> &#x03B1; <!-- Î± --> </mi> </msup> <mo> ( </mo> <mi> &#x03A9; <!-- Î© --> </mi> <mo> ) </mo> <mo> ) </mo> </math>\n'
  },
  {
    eqn_num: 1667,
    mml1: '<math>  <mi> r </mi>  <mo> &lt; </mo>  <mrow>  <mo> | </mo>  </mrow>  <msub>  <mi> y </mi>  <mrow>  <mi> n </mi>  </mrow>  </msub>  <mrow>  <mo> | </mo>  </mrow>  </math> \n',
    mml2: '<math> <mi> r </mi> <mo> &lt; </mo> <mrow> <mo> | </mo> </mrow> <msub> <mi> y </mi> <mi> n </mi> </msub> <mrow> <mo> | </mo> </mrow> </math>\n'
  },
  {
    eqn_num: 1051,
    mml1: '<math>  <mi> &#x03D1; <!-- Ï\x91 -->  </mi>  <mo> = </mo>  <mo> ( </mo>  <mi> T </mi>  <mo> &#x2212; <!-- â\x88\x92 -->  </mo>  <msub>  <mi> T </mi>  <mi> &#x221E; <!-- â\x88\x9e -->  </mi>  </msub>  <mo> ) </mo>  <mrow>  <mo> / </mo>  </mrow>  <msub>  <mi> T </mi>  <mi> &#x221E; <!-- â\x88\x9e -->  </mi>  </msub>  </math> \n',
    mml2: '<math> <mi> &#x03D1; <!-- Ï\x91 --> </mi> <mo> = </mo> <mo> ( </mo> <mi> T </mi> <mo> &#x2212; <!-- â\x88\x92 --> </mo> <msub> <mi> T </mi> <mrow> <mi> &#x221E; <!-- â\x88\x9e --> </mi> </mrow> </msub> <mo> ) </mo> <mrow> <mo> / </mo> </mrow> <msub> <mi> T </mi> <mrow> <mi> &#x221E; <!-- â\x88\x9e --> </mi> </mrow> </msub> </math>\n'
  },
  {
    eqn_num: 2101,
    mml1: '<math>   <mo>  &#x27E8; <!-- â\x9f¨ -->  </mo>  <msup>  <mi> F </mi>  <mrow>  <mn> 6 </mn>  </mrow>  </msup>  <mo> , </mo>  <mi> &#x03C6; <!-- Ï\x86 -->  </mi>  <msub>   <mo>  &#x27E9; <!-- â\x9f© -->  </mo>  <mrow>  <mo> ( </mo>  <msup>  <mi> L </mi>  <mrow>  <mn> 2 </mn>  </mrow>  </msup>  <mo> ( </mo>  <mi> &#x03A9; <!-- Î© -->  </mi>  <mo> ) </mo>  <msup>  <mo> ) </mo>  <mrow>  <mn> 2 </mn>  </mrow>  </msup>  </mrow>  </msub>  <mo> &#x2190; <!-- â\x86\x90 -->  </mo>   <mstyle>   <mfrac>  <mn> 1 </mn>  <msub>  <mi> &#x03C4; <!-- Ï\x84 -->  </mi>  <mrow>  <mn> 0 </mn>  </mrow>  </msub>  </mfrac>  </mstyle>  </math> \n',
    mml2: '<math> <mo> &#x27E8; <!-- â\x9f¨ --> </mo> <msup> <mi> F </mi> <mn> 6 </mn> </msup> <mo> , </mo> <mi> &#x03C6; <!-- Ï\x86 --> </mi> <msub> <mo> &#x27E9; <!-- â\x9f© --> </mo> <mrow> <mo> ( </mo> <msup> <mi> L </mi> <mn> 2 </mn> </msup> <mo> ( </mo> <mi> &#x03A9; <!-- Î© --> </mi> <mo> ) </mo> <msup> <mo> ) </mo> <mn> 2 </mn> </msup> </mrow> </msub> <mo> &#x2190; <!-- â\x86\x90 --> </mo> <mstyle> <mfrac> <mn> 1 </mn> <msub> <mi> &#x03C4; <!-- Ï\x84 --> </mi> <mn> 0 </mn> </msub> </mfrac> </mstyle> </math>\n'
  },
  {
    eqn_num: 1508,
    mml1: '<math>  <mi> &#x03BC; <!-- Î¼ -->  </mi>  <mo> ( </mo>  <msup>  <mi> &#x03C0; <!-- Ï\x80 -->  </mi>  <mrow>  <mo> &#x2212; <!-- â\x88\x92 -->  </mo>  <mn> 1 </mn>  </mrow>  </msup>  <mo> ( </mo>  <mi> V </mi>  <mo> ) </mo>  <mo> ) </mo>  <mo> &gt; </mo>  <mn> 0 </mn>  </math> \n',
    mml2: '<math> <mi> &#x03BC; <!-- Î¼ --> </mi> <mo> ( </mo> <msup> <mstyle> <mrow> <msub> <mi> p </mi> <mi> i </mi> </msub> </mrow> </mstyle> <mrow> <mo> &#x2212; <!-- â\x88\x92 --> </mo> <mn> 1 </mn> </mrow> </msup> <mo> ( </mo> <mi> V </mi> <mo> ) </mo> <mo> ) </mo> <mo> &gt; </mo> <mn> 0 </mn> </math>\n'
  },
  {
    eqn_num: 157,
    mml1: '<math>  <mrow>  <mrow>  <mi> l </mi>  <mi> n </mi>  </mrow>  </mrow>  <mo> ( </mo>  <mi> N </mi>  <mo> ( </mo>  <msub>  <mi> T </mi>  <mi> u </mi>  </msub>  <mo> ) </mo>  <mrow>  <mo> / </mo>  </mrow>  <msub>  <mi> g </mi>  <mi> u </mi>  </msub>  <mo> ) </mo>  <mo> = </mo>  <mrow>  <mrow>  <mi> l </mi>  <mi> n </mi>  </mrow>  </mrow>  <mo> ( </mo>  <msub>  <mi> N </mi>  <mrow>  <mn> 0 </mn>  <mo> , </mo>  <mrow>  <mi> O </mi>  <mi> N </mi>  <mi> E </mi>  </mrow>  </mrow>  </msub>  <mo> ) </mo>  <mo> &#x2212; <!-- â\x88\x92 -->  </mo>   <mstyle>   <mrow>  <mfrac>  <msub>  <mi> T </mi>  <mi> u </mi>  </msub>  <msub>  <mi> T </mi>  <mrow>  <mrow>  <mi> O </mi>  <mi> N </mi>  <mi> E </mi>  </mrow>  </mrow>  </msub>  </mfrac>  </mrow>  </mstyle>  </math> \n',
    mml2: '<math> <mi> ln </mi> <mo> &#x2061; <!-- â\x81¡ --> </mo> <mo> ( </mo> <mi> N </mi> <mo> ( </mo> <msub> <mi> T </mi> <mi> u </mi> </msub> <mo> ) </mo> <mrow> <mo> / </mo> </mrow> <msub> <mi> g </mi> <mi> u </mi> </msub> <mo> ) </mo> <mo> = </mo> <mi> ln </mi> <mo> &#x2061; <!-- â\x81¡ --> </mo> <mo> ( </mo> <msub> <mi> N </mi> <mrow> <mn> 0 </mn> <mo> , </mo> <mi> O </mi> <mi> N </mi> <mi> E </mi> </mrow> </msub> <mo> ) </mo> <mo> &#x2212; <!-- â\x88\x92 --> </mo> <mstyle> <mrow> <mfrac> <msub> <mi> T </mi> <mi> u </mi> </msub> <msub> <mi> T </mi> <mrow> <mi> O </mi> <mi> N </mi> <mi> E </mi> </mrow> </msub> </mfrac> </mrow> </mstyle> </math>\n'
  },
  {
    eqn_num: 1297,
    mml1: '<math>  <mo> &#x222B; <!-- â\x88« -->  </mo>   <mstyle>    <mstyle>   <msub>  <mi> T </mi>  <mrow>  <mi> A </mi>  </mrow>  </msub>  <mrow>  <mi> d </mi>  </mrow>  <mi> &#x03C5; <!-- Ï\x85 -->  </mi>  </math> \n',
    mml2: '<math> <mo> &#x222B; <!-- â\x88« --> </mo> <msub> <mi> T </mi> <mrow> <mi> A </mi> </mrow> </msub> <mrow> <mi> d </mi> </mrow> <mi> &#x03C5; <!-- Ï --> </mi> </math>\n'
  },
  {
    eqn_num: 1506,
    mml1: '<math>  <munderover>  <mo> &#x2211; <!-- â\x88\x91 -->  </mo>  <mrow>  <mi> k </mi>  <mo> = </mo>  <mn> 2 </mn>  </mrow>  <mrow>  <mi> q </mi>  </mrow>  </munderover>  <mrow>  <msub>  <mi> &#x03B6; <!-- Î¶ -->  </mi>  <mi> k </mi>  </msub>  </mrow>  <mo> &lt; </mo>  <mn> 0 </mn>  </math> \n',
    mml2: '<math> <munderover> <mo> &#x2211; <!-- â\x88\x91 --> </mo> <mrow> <mi> k </mi> <mo> = </mo> <mn> 2 </mn> </mrow> <mi> q </mi> </munderover> <msub> <mi> &#x03B6; <!-- Î¶ --> </mi> <mi> k </mi> </msub> <mo> &lt; </mo> <mn> 0 </mn> </math>\n'
  },
  {
    eqn_num: 1733,
    mml1: '<math>  <msup>  <mi> H </mi>  <mrow>  <mi> N </mi>  <mi> L </mi>  <mi> O </mi>  <mtext> &#xA0; </mtext>  <mi> J </mi>  <mi> I </mi>  <mi> M </mi>  <mi> W </mi>  <mi> L </mi>  <mi> K </mi>  </mrow>  </msup>  <mo> = </mo>  <msub>  <mo> &#x222B; <!-- â\x88« -->  </mo>  <mrow>  <mi> x </mi>  <mo> , </mo>  <mi> y </mi>  </mrow>  </msub>  <msub>  <mi> K </mi>  <mrow>  <mn> 2 </mn>  <mo> , </mo>  <mn> 0 </mn>  </mrow>  </msub>  <mo> ( </mo>  <mi> x </mi>  <mo> , </mo>  <mi> y </mi>  <mo> ) </mo>   <mstyle>   <mrow>  <mo> [ </mo>  <msubsup>  <mi> J </mi>  <mi> L </mi>  <mi> a </mi>  </msubsup>  <mo> ( </mo>  <mi> x </mi>  <mo> ) </mo>   <mstyle>   <msubsup>  <mi> J </mi>  <mi> L </mi>  <mi> a </mi>  </msubsup>  <mo> ( </mo>  <mi> y </mi>  <mo> ) </mo>   <mstyle>   <mo> + </mo>   <mstyle>   <msubsup>  <mi> J </mi>  <mi> R </mi>  <mi> a </mi>  </msubsup>  <mo> ( </mo>  <mi> x </mi>  <mo> ) </mo>   <mstyle>   <msubsup>  <mi> J </mi>  <mi> R </mi>  <mi> a </mi>  </msubsup>  <mo> ( </mo>  <mi> y </mi>  <mo> ) </mo>  <mo> ] </mo>  </mrow>   <mstyle>    <mstyle>   </math> \n',
    mml2: '<math> <msup> <mi> H </mi> <mrow> <mi> N </mi> <mi> L </mi> <mi> O </mi> </mrow> </msup> <mstyle> <msub> <mrow>\n'
  },
  {
    eqn_num: 1332,
    mml1: '<math>  <mi> Z </mi>  <mo> ( </mo>  <mi> t </mi>  <mo> , </mo>  <mi> x </mi>  <mo> ) </mo>  <mo> = </mo>  <mi> Y </mi>  <msub>  <mn> 1 </mn>  <mrow>  <mo> ] </mo>  <mi> a </mi>  <mo> , </mo>  <mi> b </mi>  <mo> ] </mo>  </mrow>  </msub>  <mo> ( </mo>  <mi> t </mi>  <mo> ) </mo>  <msub>  <mn> 1 </mn>  <mrow>  <mi> A </mi>  </mrow>  </msub>  <mo> ( </mo>  <mi> x </mi>  <mo> ) </mo>  </math> \n',
    mml2: '<math> <mi> Z </mi> <mo> ( </mo> <mi> t </mi> <mo> , </mo> <mi> x </mi> <mo> ) </mo> <mo> = </mo> <mi> Y </mi> <msub> <mn> 1 </mn> <mrow> <mrow> <mo> | </mo> </mrow> <mi> a </mi> <mo> , </mo> <mi> b </mi> <mo> &#x230B; <!-- â\x8c\x8b --> </mo> </mrow> </msub> <mo> ( </mo> <mi> t </mi> <mo> ) </mo> <msub> <mn> 1 </mn> <mi> A </mi> </msub> <mo> ( </mo> <mi> x </mi> <mo> ) </mo> </math>\n'
  },
  {
    eqn_num: 819,
    mml1: '<math>  <msup>  <mi> ln </mi>  <mn> 2 </mn>  </msup>  <mo> &#x2061; <!-- â\x81¡ -->  </mo>  <mstyle scriptlevel="0">  <mrow>   <mi>  ( </mo>  </mrow>  </mstyle>   <mstyle>   <mrow>  <mfrac>  <mi> x </mi>  <mrow>  <msup>  <mi> &#x03B4; <!-- Î´ -->  </mi>  <mn> 2 </mn>  </msup>  <mi> q </mi>  </mrow>  </mfrac>  </mrow>  <mstyle scriptlevel="0">  <mrow>   <mi>  ) </mo>  </mrow>  </mstyle>  <mo> = </mo>  <msup>  <mi> ln </mi>  <mn> 2 </mn>  </msup>  <mo> &#x2061; <!-- â\x81¡ -->  </mo>  <mstyle scriptlevel="0">  <mrow>   <mi>  ( </mo>  </mrow>  </mstyle>   <mstyle>   <mrow>  <mfrac>  <mi> x </mi>  <msup>  <mi> &#x03B4; <!-- Î´ -->  </mi>  <mn> 2 </mn>  </msup>  </mfrac>  </mrow>  <mstyle scriptlevel="0">  <mrow>   <mi>  ) </mo>  </mrow>  </mstyle>  <mo> + </mo>  <msup>  <mi> ln </mi>  <mn> 2 </mn>  </msup>  <mo> &#x2061; <!-- â\x81¡ -->  </mo>  <mi> q </mi>  <mo> &#x2212; <!-- â\x88\x92 -->  </mo>  <mn> 2 </mn>  <mi> ln </mi>  <mo> &#x2061; <!-- â\x81¡ -->  </mo>  <mstyle scriptlevel="0">  <mrow>   <mi>  ( </mo>  </mrow>  </mstyle>   <mstyle>   <mrow>  <mfrac>  <mi> x </mi>  <msup>  <mi> &#x03B4; <!-- Î´ -->  </mi>  <mn> 2 </mn>  </msup>  </mfrac>  </mrow>  <mstyle scriptlevel="0">  <mrow>   <mi>  ) </mo>  </mrow>  </mstyle>  <mi> ln </mi>  <mo> &#x2061; <!-- â\x81¡ -->  </mo>  <mi> q </mi>  </mstyle>  </mstyle>  </mstyle>  </math> \n',
    mml2: '<math> <msup> <mi> ln </mi> <mn> 2 </mn> </msup> <mo> &#x2061; <!-- â\x81¡ --> </mo> <mrow> <mo> ( </mo> <mstyle> <mrow> <mfrac> <mi> x </mi> <mrow> <msup> <mi> &#x03B4; <!-- Î´ --> </mi> <mn> 2 </mn> </msup> <mi> q </mi> </mrow> </mfrac> </mrow> </mstyle> <mo> ) </mo> </mrow> <mo> = </mo> <msup> <mi> ln </mi> <mn> 2 </mn> </msup> <mo> &#x2061; <!-- â\x81¡ --> </mo> <mrow> <mo> ( </mo> <mstyle> <mrow> <mfrac> <mi> x </mi> <msup> <mi> &#x03B4; <!-- Î´ --> </mi> <mn> 2 </mn> </msup> </mfrac> </mrow> </mstyle> <mo> ) </mo> </mrow> <mo> + </mo> <msup> <mi> ln </mi> <mn> 2 </mn> </msup> <mo> &#x2061; <!-- â\x81¡ --> </mo> <mi> q </mi> <mo> &#x2212; <!-- â\x88\x92 --> </mo> <mn> 2 </mn> <mi> ln </mi> <mo> &#x2061; <!-- â\x81¡ --> </mo> <mrow> <mo> ( </mo> <mstyle> <mrow> <mfrac> <mi> x </mi> <msup> <mi> &#x03B4; <!-- Î´ --> </mi> <mn> 2\n'
  },
  {
    eqn_num: 1879,
    mml1: '<math>  <mrow>  <mo> ( </mo>   <mn>   <mtr>  <mtd>  <msubsup>  <mrow>  <mi> M </mi>  </mrow>  <mn> 2 </mn>  <mo> &#x2217; <!-- â\x88\x97 -->  </mo>  </msubsup>  <msub>  <mrow>  <mi> B </mi>  </mrow>  <mn> 2 </mn>  </msub>  <msub>  <mrow>  <mi> M </mi>  </mrow>  <mn> 2 </mn>  </msub>  <msubsup>  <mrow>  <mi> M </mi>  </mrow>  <mn> 2 </mn>  <mo> &#x2217; <!-- â\x88\x97 -->  </mo>  </msubsup>  <mrow>  <mi> U </mi>  </mrow>  <msub>  <mrow>  <mi> M </mi>  </mrow>  <mn> 1 </mn>  </msub>  </mtd>  </mtr>  <mtr>  <mtd>  <mn> 0 </mn>  <msubsup>  <mrow>  <mi> M </mi>  </mrow>  <mn> 1 </mn>  <mo> &#x2217; <!-- â\x88\x97 -->  </mo>  </msubsup>  <msub>  <mrow>  <mi> B </mi>  </mrow>  <mn> 1 </mn>  </msub>  <msub>  <mrow>  <mi> M </mi>  </mrow>  <mn> 1 </mn>  </msub>  </mtd>  </mtr>   <mn>   <mo> ) </mo>  </mrow>  </math> \n',
    mml2: '<math> <mrow> <mo> ( </mo> <mn> <mtr> <mtd> <msubsup> <mrow> <mi> M </mi> </mrow> <mn> 2 </mn> <mo> &#x2217; <!-- â\x88\x97 --> </mo> </msubsup> <msub> <mrow> <mi> B </mi> </mrow> <mn> 2 </mn> </msub> <msub> <mrow> <mi> M </mi> </mrow> <mn> 2 </mn> </msub> <msubsup> <mrow> <mi> M </mi> </mrow> <mn> 1 </mn> <mo> &#x2217; <!-- â\x88\x97 --> </mo> </msubsup> <msub> <mrow> <mi> U </mi> <mi> M </mi> </mrow> <mn> 1 </mn> </msub> </mtd> </mtr> <mtr> <mtd> <mn> 0 </mn> <msubsup> <mrow> <mi> M </mi> </mrow> <mn> 1 </mn> <mo> &#x2217; <!-- â\x88\x97 --> </mo> </msubsup> <msub> <mrow> <mi> B </mi> </mrow> <mn> 1 </mn> </msub> <msub> <mrow> <mi> M </mi> </mrow> <mn> 1 </mn> </msub> </mtd> </mtr> <mtr> <mtd> <mn> 0 </mn> <msubsup> <mrow> <mi> M </mi> </mrow> <mn> 1 </mn> <mo> &#x2217; <!-- â\x88\x97 --> </mo> </msubsup> <msub> <mrow> <mi> B </mi> </mrow> <mn> 1 </mn> </msub> <msub>\n'
  },
  {
    eqn_num: 1760,
    mml1: '<math>  <msub>  <mi> v </mi>  <mrow>  <mn> 1 </mn>  </mrow>  </msub>  <mo> = </mo>  <mo> &#x2212; <!-- â\x88\x92 -->  </mo>  <msub>  <mi> c </mi>  <mrow>  <mn> 1 </mn>  </mrow>  </msub>  <mrow>  <mo> ( </mo>   <mstyle>   <mrow>  <mfrac>  <mrow>  <msubsup>  <mi> v </mi>  <mrow>  <mn> 0 </mn>  </mrow>  <mrow>  <mi> &#x2032; <!-- â\x80² -->  </mi>  </mrow>  </msubsup>  <mo> + </mo>  <mi> &#x03BB; <!-- Î» -->  </mi>  <msub>  <mi> v </mi>  <mrow>  <mn> 0 </mn>  </mrow>  </msub>  </mrow>  <mi> Q </mi>  </mfrac>  </mrow>  <munderover>  <mo> &#x2211; <!-- â\x88\x91 -->  </mo>  <mrow>  <mi> k </mi>  <mo> = </mo>  <mn> 0 </mn>  </mrow>  <mrow>  <mi> &#x221E; <!-- â\x88\x9e -->  </mi>  </mrow>  </munderover>  <msup>  <mi> &#x03BB; <!-- Î» -->  </mi>  <mrow>  <mi> k </mi>  </mrow>  </msup>  <msup>  <mrow>  <mover>  <mi> X </mi>  <mo> &#x007E; <!-- ~ -->  </mo>  </mover>  </mrow>  <mrow>  <mrow>  <mo> ( </mo>  <mn> 2 </mn>  <mi> k </mi>  <mo> ) </mo>  </mrow>  </mrow>  </msup>  <mo> + </mo>   <mstyle>   <mrow>  <mfrac>  <mi> &#x03BB; <!-- Î» -->  </mi>  <msub>  <mi> v </mi>  <mrow>  <mn> 0 </mn>  </mrow>  </msub>  </mfrac>  </mrow>  <munderover>  <mo> &#x2211; <!-- â\x88\x91 -->  </mo>  <mrow>  <mi> k </mi>  <mo> = </mo>  <mn> 0 </mn>  </mrow>  <mrow>  <mi> &#x221E; <!-- â\x88\x9e -->  </mi>  </mrow>  </munderover>  <msup>  <mi> &#x03BB; <!-- Î» -->  </mi>  <mrow>  <mi> k </mi>  </mrow>  </msup>  <msup>  <mrow>  <mover>  <mi> X </mi>  <mo> &#x007E; <!-- ~ -->  </mo>  </mover>  </mrow>  <mrow>  <mrow>  <mo> ( </mo>  <mn> 2 </mn>  <mi> k </mi>  <mo> + </mo>  <mn> 1 </mn>  <mo> ) </mo>  </mrow>  </mrow>  </msup>  </mstyle>  </mstyle>  <mo> ) </mo>  </mrow>   <mo>   </math> \n',
    mml2: '<math> <msub> <mi> v </mi> <mn> 1 </mn> </msub> <mo> = </mo> <mo> &#x2212; <!-- â\x88\x92 --> </mo> <msub> <mi> c </mi> <mn> 1 </mn> </msub> <mrow> <mo> ( </mo> <mstyle> <mrow> <mfrac> <mrow> <msubsup> <mi> v </mi> <mn> 0 </mn> <mo> &#x2032; </mo> </msubsup> <mo> + </mo> <mi> &#x03BB; <!-- Î» --> </mi> <msub> <mi> v </mi> <mn> 0 </mn> </msub> </mrow> <mi> Q </mi> </mfrac> </mrow> <munderover> <mo> &#x2211; <!-- â\x88\x91 --> </mo> <mrow> <mi> k </mi> <mo> = </mo> <mn> 0 </mn> </mrow> <mi> &#x221E; <!-- â\x88\x9e --> </mi> </munderover> <msup> <mi> &#x03BB; <!-- Î» --> </mi> <mi> k </mi> </msup> <msup> <mrow> <mover> <mi> X </mi> <mo> &#x007E; <!-- ~ --> </mo> </mover> </mrow> <mrow> <mo> ( </mo> <mn> 2 </mn> <mi> k </mi> <mo> ) </mo> </mrow> </msup> <mo> + </mo> <mstyle> <mrow> <mfrac> <mi> &#x03BB; <!-- Î» --> </mi> <msub> <mi> v </mi> <mn>\n'
  },
  {
    eqn_num: 854,
    mml1: '<math>  <mn> 1 </mn>  <msubsup>  <mi> L </mi>  <mo> &#x2212; <!-- â\x88\x92 -->  </mo>  <mi> &#x03B5; <!-- Îµ -->  </mi>  </msubsup>  <msub>  <mi> r </mi>  <mrow>  <mi> i </mi>  <mi> s </mi>  <mi> c </mi>  <mi> o </mi>  </mrow>  </msub>  <mo> &lt; </mo>  <mn> 6 </mn>  </math> \n',
    mml2: '<math> <mn> 1 </mn> <mo> &#x2A7D; <!-- â©½ --> </mo> <msub> <mi> r </mi> <mrow> <mi> i </mi> <mi> s </mi> <mi> c </mi> <mi> o </mi> </mrow> </msub> <mo> &lt; </mo> <mn> 6 </mn> </math>\n'
  },
  {
    eqn_num: 770,
    mml1: '<math>  <mo> &#x223C; <!-- â\x88¼ -->  </mo>  <mn> 10 </mn>  <msub>  <mi> M </mi>  <mrow>  <mo> &#x2299; <!-- â\x8a\x99 -->  </mo>  </mrow>  </msub>  </math> \n',
    mml2: '<math> <mo> &#x223C; <!-- â\x88¼ --> </mo> <mn> 10 </mn> <msub> <mi> M </mi> <mo> &#x2299; <!-- â\x8a\x99 --> </mo> </msub> </math>\n'
  },
  {
    eqn_num: 2112,
    mml1: '<math>  <mo> ( </mo>  <mi> P </mi>  <mo> &#x22C5; <!-- â\x8b\x85 -->  </mo>  <mi> C </mi>  <msub>  <mo> ) </mo>  <mrow>  <mn> 233424 </mn>  </mrow>  </msub>  <mo> = </mo>   <mstyle>   <mrow>  <mfrac>  <mrow>  <mo> ( </mo>  <mi> t </mi>  <mo> &#x2212; <!-- â\x88\x92 -->  </mo>  <mn> 2 </mn>  <mi> &#x03BE; <!-- Î¾ -->  </mi>  <mo> ) </mo>  <msup>  <mrow>  <mi> s </mi>  <mi> i </mi>  <mi> n </mi>  </mrow>  <mn> 2 </mn>  </msup>  <mi> &#x03D1; <!-- Ï\x91 -->  </mi>  <mrow>  <mo> ( </mo>  <mi> t </mi>  <mrow>  <mo> ( </mo>  <mi> t </mi>  <mrow>  <mover>  <mi> &#x03BE; <!-- Î¾ -->  </mi>  <mo> &#x00A8; <!-- Â¨ -->  </mo>  </mover>  </mrow>  <mo> &#x2212; <!-- â\x88\x92 -->  </mo>  <mn> 4 </mn>  <mrow>  <mover>  <mi> &#x03BE; <!-- Î¾ -->  </mi>  <mo> &#x02D9; <!-- Ë\x99 -->  </mo>  </mover>  </mrow>  <mo> ) </mo>  </mrow>  <mo> + </mo>  <mn> 6 </mn>  <mi> &#x03BE; <!-- Î¾ -->  </mi>  <mo> ) </mo>  </mrow>  <mrow>  <mo> ( </mo>  <mi> t </mi>  <mrow>  <mo> ( </mo>  <mn> 2 </mn>  <mi> t </mi>  <mrow>  <mover>  <mi> &#x03BE; <!-- Î¾ -->  </mi>  <mo> &#x00A8; <!-- Â¨ -->  </mo>  </mover>  </mrow>  <mo> &#x2212; <!-- â\x88\x92 -->  </mo>  <mn> 7 </mn>  <mrow>  <mover>  <mi> &#x03BE; <!-- Î¾ -->  </mi>  <mo> &#x02D9; <!-- Ë\x99 -->  </mo>  </mover>  </mrow>  <mo> ) </mo>  </mrow>  <mo> + </mo>  <mn> 9 </mn>  <mi> &#x03BE; <!-- Î¾ -->  </mi>  <mo> ) </mo>  </mrow>  </mrow>  <mrow>  <mn> 18 </mn>  <msup>  <mi> t </mi>  <mn> 3 </mn>  </msup>  </mrow>  </mfrac>  </mrow>  <mo> = </mo>  <mo> ( </mo>  <mi> P </mi>  <mo> &#x22C5; <!-- â\x8b\x85 -->  </mo>  <mi> C </mi>  <msub>  <mo> ) </mo>  <mrow>  <mn> 244323 </mn>  </mrow>  </msub>  <mo> ; </mo>  </mstyle>  </math> \n',
    mml2: '<math> <mo> ( </mo> <mi> P </mi> <mo> &#x22C5; <!-- â\x8b --> </mo> <mi> C </mi> <msub> <mo> ) </mo> <mrow> <mn> <unk> </mn> </mrow> </msub> <mo> = </mo> <mstyle> <mrow> <mfrac> <mrow> <mo> ( </mo> <mi> t </mi> <mo> &#x2212; <!-- â\x88\x92 --> </mo> <mn> 2 </mn> <mi> &#x03BE; <!-- Î¾ --> </mi> <mo> ) </mo> <msup> <mi> sin </mi> <mn> 2 </mn> </msup> <mo> &#x2061; <!-- â\x81¡ --> </mo> <mi> &#x03D1; <!-- Ï\x91 --> </mi> <mrow> <mo> ( </mo> <mi> t </mi> <mrow> <mo> ( </mo> <mrow> <mover> <mi> t </mi> <mo> &#x02D9; <!-- Ë\x99 --> </mo> </mover> </mrow> <mrow> <mover> <mi> &#x03BE; <!-- Î¾ --> </mi> <mo> &#x02D9; <!-- Ë\x99 --> </mo> </mover> </mrow> <mo> &#x2212; <!-- â\x88\x92 --> </mo> <mn> 4 </mn> <mrow> <mover> <mi> &#x03BE; <!-- Î¾ --> </mi> <mo> &#x02D9; <!-- Ë\x99 --> </mo> </mover> </mrow> <mo> ) </mo> </mrow> <mo> + </mo> <mn>\n'
  },
];